### ISSUE TITLE
Deprecated Bootswatch themes

### ISSUE THREAD

**Issue by oliverds** [open-classifieds/openclassifieds2#1042]
Amelia Cupid Pinkiepie Shamrock are deprecated bootswatch themes so they shouldn’t be available anymore on Kamaleon or cZSale themes.

**Comment by oliverds** [comment]
Frist issue with Amelia deprecated Bootswatch theme:

> The login interface is completely dimmed and is hidden when anything on it is clicked. http://awesomescreenshot.com/07549os636

**Comment by SuperChristophe** [comment]
@oliverds : i'm currenty using amelia theme and have the problem ... tell it to open classifieds team via support and they answer : "apologize ... we suggest you to use another theme" :(
Any solution ?

**Comment by oliverds** [comment]
@SuperChristophe We will try to solve this issue but since Amelia Bootswatch was deprecated http://news.bootswatch.com/post/94634387436/new-themes-paper-and-sandstone we can not promise a solution.

**Comment by SuperChristophe** [comment]
(if you are from OC team i mean, excuse me otherwise and thanx to help) I have just bought it ... as you may know. Why do OC let buy this theme featuring this style if you know it's not usable ? 

When will you be able to "tell me" if there is a solution please ? Because i can't stay like this very long ..

**Comment by SuperChristophe** [comment]
the issue concern not only the login interface, but every "little windowed interface" : reviews, ...

**Comment by neo22s** [comment]
Hello @SuperChristophe ,

@oliverds  works with us ;)

We didnt know amelia was deprecated until yesterday, is something we didnt expect at all and we are going to remove it from next release as others skins, no problem at all ;).

He will fix for you the modal. No problem. But please keep the conversation on the Ticket this is a issue for developers. Thanks.

**Comment by SuperChristophe** [comment]
No problem @neo22s. I'm here because i have no answer to the same question on the Ticket however. Thx.

**Comment by neo22s** [comment]
Tana (in the ticket) was unaware of this since we are not sure yet how to proceed. welcome! ;)
