### ISSUE TITLE
Memberships plans to post

### ISSUE THREAD

**Issue by neo22s** [open-classifieds/openclassifieds2#1043]
We will need

- [x] Table plans
    - id_plan
    - name
    - seoname
    - description
    - days
    - price
    - num_ads
   - marketplace_fee
    - status
- [x] Table subscriptions
    - id_plan
    - id_user
    - id_order
    - plan_expire_date
    - num_ads
    - num_ads_left
   - status (1 is the current, 0 no active, 5 expired)
- [x] Controller CRUD plans/subscriptions
- [x] controller pricing to display the price and all the other prices of other products
- [x] allow to use coupons
- [x] controller /plan/checkout order pay if type plan renew plan to user, set expire and amount of ads...
- [x] free plan no checkout with order
- [x] controller new ad, check if user has mambership available, if not redirect. 
- [x] when ad published ++ num_ads_left
- [x] cron to renew notify the plan expires and link to pay, every 5 minutes.
- [x] if marketplace ON then charge the % based on the plan
- [x] controller profile add subscription info

**Comment by neo22s** [comment]
Should we add also number of images? I was asked this before... so different plans different amount of images able to post.

**Comment by neo22s** [comment]
@oliverds 

- [ ] add the profile subscription info in the other themes (I didnt do it since goes with yclas, but is simple )
- [ ] merge at yclas xD

@kotsios5 @oliverds 

Test please!

@kotsios5 I will do a video if I have time today to show how it works. Then you can do documentation ;)

**Comment by neo22s** [comment]
@kotsios5 no time for video :S maybe tomorrow if I get time.

**Comment by kotsios5** [comment]
Ok! I will do the doc tomorrow then!
