### ISSUE TITLE
Improve installer

### ISSUE THREAD

**Issue by neo22s** [open-classifieds/openclassifieds2#1046]
Check awesome job done at october:
https://github.com/octobercms/install

**Comment by oliverds** [comment]
OK after a few concept attempts this is the one I liked most, [video](https://vid.me/JqUA). What do you think?

**Comment by neo22s** [comment]
Wooow!! looks nice! What happens once you click install? appears a progress bar or similar?

Be aware the link in the footer.

Also we need to do the 1 file install that downloads the software. With a download progress would be nice.

**Comment by oliverds** [comment]
Nothing yet. Could be. Mostly the work done so far has been HTML+JS+CSS.

ok, I think that will be the last thing to do.

**Comment by neo22s** [comment]
Also sending you a video on slack ;)

![open classifieds installation](https://cloud.githubusercontent.com/assets/241725/7815575/8b62cae8-03c9-11e5-894e-0fe5c99ca8ec.png)

**Comment by neo22s** [comment]
if theres no file permission to open the css or js this happens:

![open classifieds installation](https://cloud.githubusercontent.com/assets/241725/8034560/1c830bb8-0de9-11e5-93e7-f4bdc9838e90.png)

**Comment by neo22s** [comment]
this is also done?

**Comment by oliverds** [comment]
Sorry but not yet. One file install is still pending.

**Comment by neo22s** [comment]
no hurry ;)
