### ISSUE TITLE
Categories enhancement

### ISSUE THREAD

**Issue by kinanhamwi** [open-classifieds/openclassifieds2#1068]
Step1: create categories using the quick category creator.
Step2: assign category parent manually (this is necessary when the browser doesn't allow moving categories around) http://i.imgur.com/CQgLZvB.png

 http://awesomescreenshot.com/001412ijeb
Step3: publish new

error: when publishing a new ad you will see the new categories in the main categories list: http://i.imgur.com/XSvS80e.png

This can be fixed if the user amends the category order number manually. 

Suggested solutions: 

1- get the categories drag & drop tool to work on all browsers.

2- assign an automatic different order number to the category when its parent is manually edited.

**Comment by neo22s** [comment]
cant reproduce the error :S
