### ISSUE TITLE
Search by distance

### ISSUE THREAD

**Issue by neo22s** [open-classifieds/openclassifieds2#1073]
Related to https://github.com/open-classifieds/openclassifieds2/issues/993

In tables Ad and Location add fields:
Longitude and Latitude

In controller location, display a g.maps, where they can pin point and address or they can write an address and search. This will return Long and Lat to be stored in the location.

In publish new, if address field is active and g.maps, we will store the coords (long, lat) of the advertisement. We will try to position the user using HTML5, and fill the address field for him.

Build a search by distance feature based on trigonometry like tumanitas. First checks for ads and then for ads with locations close to him.

Build a tool to get coords from addresses using g.maps api for old ads. Only ads with address and lat and long === NULL

Googlemaps centered to your location. Would be nice that maps filter ads by current category and location.

Widget subscribe can we add distance?

**Comment by neo22s** [comment]
First round feedback

- map not opening, ads nl2br issue
- display distance to advert?
- review pagination count
- Choose closest location order by distance and put the distance
- create a guide how works, what they need to activate

**Comment by neo22s** [comment]
You have included the Google Maps API multiple times on this page. This may cause unexpected errors.main.js:56

**Comment by neo22s** [comment]
Also can we filter the map by category and location?

**Comment by oliverds** [comment]
Sure we can http://awesomescreenshot.com/09f4o58h2c.

**Comment by neo22s** [comment]
oh yeah!!! nice!

Now the issue is this:
http://awesomescreenshot.com/0514o5dv9d

**Comment by oliverds** [comment]
> Now the issue is this:
> http://awesomescreenshot.com/0514o5dv9d

Noted and fixed.

**Comment by oliverds** [comment]
**Options to Activate**

1. "Auto Locate Visitors" /oc-panel/settings/general (http://awesomescreenshot.com/0d04p1gn5e)
2. "Google Maps in Publish New" /oc-panel/settings/form (http://awesomescreenshot.com/0c14p1hlb0)

**Import Latitude and Longitude to current ads**

/oc-panel/import (http://awesomescreenshot.com/0cb4p1iu3d)
