### ISSUE TITLE
Advanced search view minor enhancement

### ISSUE THREAD

**Issue by kinanhamwi** [open-classifieds/openclassifieds2#1082]
The price from - to fields could look a bit confusing. After looking at the theme you can find that the two fields are not next to each other.

Themes that have this view: CZSale, Moderndeluxe, Bootplus, Reclassifieds

What we could do is to change the location of the second field to have it next to the first one, just as it is with the rest of the themes.

http://awesomescreenshot.com/0014585l00

**Comment by oliverds** [comment]
Can be closed. Commit on [BB](https://bitbucket.org/neo22s/open-classifieds-private/commits/2d138fa33a69be17b953301e9cd02119a6d1b039) and yclas.
