### ISSUE TITLE
Google map not showing all ads

### ISSUE THREAD

**Issue by kinanhamwi** [open-classifieds/openclassifieds2#1092]
Ads with the same address are not showing separately on map

Example

create two ads with address: Barcelona, Spain

go to yourdomain.com/map

Only one ad will be showing in Barcelona, Spain

Intended behavior: 

Ads will be added to a list in that location 

P.S. if we could improve the look of that list it would be also better :)

**Comment by georgeeremia** [comment]
You should make users when they want to insert the adress to specify in maps the street number or postal code by making a required field... it should do the work!

**Comment by neo22s** [comment]
This is already fixed for next 2.4.0, we transform the address into latitude and longitude.
