### ISSUE TITLE
Custom fields for users

### ISSUE THREAD

**Issue by neo22s** [open-classifieds/openclassifieds2#1095]
Like CF for ads, also for users, so you can have mandatory fields to register for example.

In publish new those field will need to be rendered. Also in register.

In edit profile they can change any of the data. In public profile should be displayed.

**Comment by neo22s** [comment]
@oliverds todo:

- Fix UI at themes/default/views/oc-panel/profile/edit.php http://reoc.lo/oc-panel/profile/edit --> form
- Fix date popup not appearing if type date CF
- Fix ui http://reoc.lo/oc-panel/auth/register#register-modal (ocean premium theme) 
- Implement at all premium themes /themes/ocean/views/pages/auth/register-form.php not on default!
- Implement at yclas ;)

**Comment by oliverds** [comment]
OC and premium themes done.
yclas implementation is still pending.

**Comment by neo22s** [comment]
Cool!! :D nice nice nice!
