### ISSUE TITLE
edit ad removes picture

### ISSUE THREAD

**Issue by kinanhamwi** [open-classifieds/openclassifieds2#1109]
When a user publishes an advertisement and goes to edit it through his panel, whatever he changes e.g. advert title then the image that was on the advert is no longer there.

So whenever an ad is edited the picture disappears

**Comment by neo22s** [comment]
which site is happening? updated to 2.3.1? I have fixed this before :S @oliverds  please check it ;) seotitle should not be modified on edited ads.

**Comment by oliverds** [comment]
This one can be closed, on 2.3.1 has been fixed.
