### ISSUE TITLE
Feature ad after publish

### ISSUE THREAD

**Issue by neo22s** [open-classifieds/openclassifieds2#1111]
What if we redirect the user to a check out page after publishing the ad to go featured? only if category is free and featured ad is = on?

**Comment by neo22s** [comment]
Create a landing page with a thanks editable content.

Will display the selected page + featured ad button.

Always redirect new published to this page. Even if they pay for category.

/ad/thanks/IDAD

**Comment by oliverds** [comment]
Only review thanks page, right?

**Comment by neo22s** [comment]
yep, check that works also but seems good ;)

**Comment by oliverds** [comment]
Seems to work good to me too.
