### ISSUE TITLE
Install.MD addendum

### ISSUE THREAD

**Issue by oldhobbyist** [open-classifieds/openclassifieds2#1117]
Would be nice to add instructions for installation via Github.

**Comment by neo22s** [comment]
Sure feel free contributing: https://github.com/open-classifieds/openclassifieds2/blob/master/CONTRIBUTING.md

**Comment by oldhobbyist** [comment]
Thanks! That I think has got the answer to my question.

I guess you don't want the install from Github available for non-devs? Anyway, thank you!

**Comment by neo22s** [comment]
Actually all the files are hosted on github, so by definition you are installing from github:
https://github.com/open-classifieds/openclassifieds2/releases

Thanks!
