### ISSUE TITLE
Notifications of contact

### ISSUE THREAD

**Issue by neo22s** [open-classifieds/openclassifieds2#1126]
Using table views we can know if they have contacted you.

Lets add a notification bar!

**Comment by neo22s** [comment]
What if we add something as cool as this:
http://lab.ejci.net/favico.js/

**Comment by oliverds** [comment]
Sadly Safari browser doesn't show favicons by default also the demo http://lab.ejci.net/favico.js/example-simple/ doesn't work.

**Comment by neo22s** [comment]
still quite cool, no? xD

**Comment by oliverds** [comment]
yeah it looks great.
