### ISSUE TITLE
Improvements for advanced search page

### ISSUE THREAD

**Issue by oliverds** [open-classifieds/openclassifieds2#1144]
On search form:

1. When you select an option from a custom field you cannot unselect it. You can change the option but you cannot reset... The only solution is to reload the page (but users do not thing to do that)

2. When you click on the search button, all custom fields disappear... The category is still selected but all the fields are hidden. So users can't do a second search (except if they reload the page or select a new category).

3. This div for select have a width depending on it's content. If the content (select options) is small, we cannot see the div label (we just have "...") so people can't search.

4. When the page is loading you can see all the fields before it's disappear. It’s appearing again when you select the right category. Is a bit "ugly" to show and hide when you load the page

**Comment by oliverds** [comment]
This issue can be closed. Commit on [BB](https://bitbucket.org/neo22s/open-classifieds-private/commits/085dc8722638fab67e3e1733f9653f9e0db5bb6c).

**Comment by neo22s** [comment]
coool!
