### ISSUE TITLE
Limit custom fields

### ISSUE THREAD

**Issue by oliverds** [open-classifieds/openclassifieds2#1149]
Do research of how many fields can have a mysql table.

**Comment by oliverds** [comment]
Seems that there is not a hard limit on maximum columns:

- http://www.percona.com/blog/2013/04/08/understanding-the-maximum-number-of-columns-in-a-mysql-table/
- http://dev.mysql.com/doc/refman/5.7/en/column-count-limit.html

So let's limit it to 100.

**Comment by neo22s** [comment]
So its based on size not in amount of columns. Yes lets place a limit to avoid issues on customer, I think 50 + the ones already exists that are once you install.
