### ISSUE TITLE
Redirected out of the sub-folder

### ISSUE THREAD

**Issue by Alvarofg** [open-classifieds/openclassifieds2#1154]
I'm running my site under a sub-folder /avisos/  and today I started noticing that I'm getting redirected (not always)  from:
 
mysite/avisos/oc-panel/ 
to 
mysite/oc-panel/

edit to add that the redirect only happens after the page completes loading (I can hit the stop button on the browser and prevent the redirect, that's how I manage to run the update)

running 2.3.1 (just updated from 2.3.0 and the issue remains)

more info:
I'm running wordpress on mysite/

**Comment by neo22s** [comment]
Please read:

https://github.com/open-classifieds/openclassifieds2/blob/master/CONTRIBUTING.md#reporting-issues

**Comment by Alvarofg** [comment]
After deleting all cache (and browser cache too), I can't reproduce it. If I see it again, I'll try to get some proof :) 

PS: The deepest I got while debugging was that:
1) Re sizing the browser was triggering it (as well as reloading)
2) Just before the redirect, there was a call to the Sweet Alert script, but I was not seeing any message on screen.

**Comment by Alvarofg** [comment]
I ran into the issue again, I was able to isolated it to the bootstrap tour files. So far, I got around it by commenting out 

    // Initialize the tour
    // tour.init();

    // Start the tour
    // tour.start();

in both 
https://github.com/open-classifieds/openclassifieds2/blob/23d5e2827f7afb6af75f81d33eec4bec96540b3d/themes/default/js/oc-panel/tour.js
and
https://github.com/open-classifieds/openclassifieds2/blob/23d5e2827f7afb6af75f81d33eec4bec96540b3d/themes/default/js/oc-panel/tour-user.js


![toour bug](https://cloud.githubusercontent.com/assets/5241289/6766561/33139406-cfe1-11e4-9829-f72868c640f3.jpg)
