### ISSUE TITLE
BBCODE on forums not loading

### ISSUE THREAD

**Issue by neo22s** [open-classifieds/openclassifieds2#1195]
at least on reclassifieds, responsive doesnt load

**Comment by oliverds** [comment]
Can be closes. Commit on [BB](https://bitbucket.org/neo22s/open-classifieds-private/commits/2830ece9c4b78b012a4b4ad6fc9e89dbaf80642f).
reclassifieds and responsive themes were the only affected.

**Comment by neo22s** [comment]
hahaha got a good eye!
