### ISSUE TITLE
Categories drag and drop not working

### ISSUE THREAD

**Issue by neo22s** [open-classifieds/openclassifieds2#1198]

**Comment by oliverds** [comment]
Is there any error message or UI issue? because it is working fine for me.

**Tested using Chrome**

![10](https://cloud.githubusercontent.com/assets/7003648/7349494/273f6d58-ecbf-11e4-8d17-e159152932ca.gif)

**Comment by neo22s** [comment]
not any error in the ocnsole, but not working nor reoc or 218.dontcode.com

I will try again probably you are right ;)

**Comment by neo22s** [comment]
works on  firefox, on chrome I have tested in incognito and no luck either :S
