### ISSUE TITLE
Gallery like button

### ISSUE THREAD

**Issue by kotsios5** [open-classifieds/openclassifieds2#1212]
There is an extra '{' next to facebook like button.
http://www.awesomescreenshot.com/image/175607/3726506c793561db8fb8acd9a29e36fa

**Comment by oliverds** [comment]
Issue solved. Commit on [BB](https://bitbucket.org/neo22s/open-classifieds-private/commits/57178ee3019ba0bcf20be9142f3d2a44cb612b55)
