### ISSUE TITLE
Translate Kohana validation messages

### ISSUE THREAD

**Issue by oliverds** [open-classifieds/openclassifieds2#1213]
https://kohanaframework.org/3.3/guide/kohana/files/messages

**Comment by neo22s** [comment]
We can override the function to use the translate tool. Do we have somewhere an example of where is been used? in our code I mean or in KO code.

**Comment by oliverds** [comment]
Could be. On [publish new](https://github.com/open-classifieds/openclassifieds2/blob/master/oc/classes/controller/new.php#L226) we use KO validation function [`errors`](https://github.com/open-classifieds/openclassifieds2/blob/master/oc/kohana/system/classes/Kohana/Validation.php#L479).

**Comment by neo22s** [comment]
I will check tomorrow whats the easiest way ;)
