### ISSUE TITLE
oc-panel: Safari browser and URL with query string issue

### ISSUE THREAD

**Issue by oliverds** [open-classifieds/openclassifieds2#1215]
Strange bug on oc-panel and affecting Safari web browsers. Loading any URL with query string the page is loaded but immediately then go back to previous URL.

![11](https://cloud.githubusercontent.com/assets/7003648/7466930/01327822-f2b3-11e4-968e-cdeb5d7e3f2a.gif)

**Comment by neo22s** [comment]
this is already done I think, no?

**Comment by oliverds** [comment]
Yes, solved by this commit https://github.com/open-classifieds/openclassifieds2/commit/626efb9fa51499f070ecb600093fa1fadd714de6
