### ISSUE TITLE
Import Tool download example

### ISSUE THREAD

**Issue by kotsios5** [open-classifieds/openclassifieds2#1220]
Unable to download example for categories and locations. mega.co.nz asks for decryption key.

**Comment by neo22s** [comment]
I gave you the link before, no?

**Comment by kotsios5** [comment]
You gave me the link to import ads which is working fine.

**Comment by neo22s** [comment]
Damn I do not have them in my mega account, maybe Oliver.

Let me assign it to him. thanks for reporting!
