### ISSUE TITLE
Duplicated title on widget map

### ISSUE THREAD

**Issue by neo22s** [open-classifieds/openclassifieds2#1240]
http://i.imgur.com/AyQAn5K.png

**Comment by neo22s** [comment]
also The map now also displays a picture in the map: http://imgur.com/gNRWk5q,aIWtepC and http://imgur.com/gNRWk5q,aIWtepC#1

**Comment by oliverds** [comment]
>The map now also displays a picture in the map

It's because on the map we show a pointer icon or a category icon if exist.

On 2181.dontcode.com ad http://2181.dontcode.com/59/bike-for-sale.html is in category "mountain-bikes" and that category has http://2181.dontcode.com/images/categories/mountain-bikes.png as icon image.

**Comment by neo22s** [comment]
Maybe can we force the resize? So its not that big?

**Comment by oliverds** [comment]
We use Google Map's ["icon"](https://github.com/open-classifieds/openclassifieds2/blob/master/themes/default/views/pages/maps.php#L27) parameter and there are no parameters to resize icon image.

**Comment by neo22s** [comment]
Damn. Lets leave it then :(

**Comment by oliverds** [comment]
> Damn. Lets leave it then :(

Ok maybe use WP Photon to resize the icon https://github.com/open-classifieds/openclassifieds2/commit/5048a4454fc38a2823871bff4410e0a0250fb4bb#diff-20024ef13276e9ad2214177a2b19d3b2R20

**Comment by neo22s** [comment]
Cool!
