### ISSUE TITLE
Redirect on firefox

### ISSUE THREAD

**Issue by neo22s** [open-classifieds/openclassifieds2#1241]
https://vid.me/Lkkc

**Comment by neo22s** [comment]
Firefox v38.0.1

**Comment by oliverds** [comment]
I can’t reproduce this issue (Firefox, Chrome, Safari latest versions) but that redirect seems to be because of the “Panel Tour”. Panel tour was ended?

**Comment by neo22s** [comment]
debe de ser eso, no?

**Comment by oliverds** [comment]
Sí pero ese redirect está bien si el usuario no ha terminado el tour (manualmente o completando los pasos).
