### ISSUE TITLE
User panel same look and feel as frontend theme

### ISSUE THREAD

**Issue by neo22s** [open-classifieds/openclassifieds2#1245]
Create new controller frontauth, where we load the same look and feel as the front for the profile options. My ads, favorites etc...

Review in all the themes :S

**Comment by oliverds** [comment]
Reviewed in all the themes and it is pretty acceptable.

Mobile theme has issues it requires extra work. Trello task created.

**Comment by neo22s** [comment]
on mobile we can skip it maybe?we could have an option on the theme that says panel_frontend = TRUE/FALSE as a variable in init.php, then on panelauthcontroller if has that on false uses the normal ?

**Comment by neo22s** [comment]
I will test this today ;)

**Comment by neo22s** [comment]
Looks great!

few issues:

- http://reoc.lo/oc-panel/profile/favorites not working Uncaught ReferenceError: swal is not defined
- can we make it full width? so no sidebar only in this pages
- checkout page also full width (maybe a config in the controller that says use full width or no?)
- see https://github.com/open-classifieds/openclassifieds2/issues/1257

**Comment by oliverds** [comment]
> panelauthcontroller if panel_frontend is false on themes use the normal

Not sure how to achieve that. I mean how to use `Auth_Controller` instead of `Auth_Frontcontroller` if `panel_frontend` is false. Or should I copy `Auth_Controller` into `Auth_Frontcontroller` with conditionals for `panel_frontend`?

**Comment by neo22s** [comment]
Right now not sure, leave it for now ;)

**Comment by neo22s** [comment]
this is done, correct?

**Comment by oliverds** [comment]
Mobile theme is pending. Currently the user panel with mobile theme it's broken.

**Comment by neo22s** [comment]
ok! ;)
