### ISSUE TITLE
On publish new, loads categories, locations, custom fields from API.

### ISSUE THREAD

**Issue by neo22s** [open-classifieds/openclassifieds2#1246]

**Comment by akt2014** [comment]
Please take a look at this issue.
http://forums.open-classifieds.com/support/adress-field-display-option.html

**Comment by neo22s** [comment]
@akt2014  thers not any relation with this issue at all. Please follow our guidelines to contribute.

**Comment by oliverds** [comment]
Publish new page now loads categories and locations from API after rewriting new.js several times.

**Pending:**
* Custom fields from API
* Implemented on yclas

**Comment by neo22s** [comment]
Works good categories and locations! congrats!! :D
