### ISSUE TITLE
Coupon system

### ISSUE THREAD

**Issue by neo22s** [open-classifieds/openclassifieds2#1249]
Coupon system (like eshop + be able to generate bulk and export as excel) 

For all products except ad_sell

**Comment by neo22s** [comment]
We need to add to order the id_coupon.

On checkout page only appears the input coupon if there's coupons available. (do it also for OE.)

**Comment by neo22s** [comment]
Missing:
- [] Checkout page in all themes, add coupon form
- Only for premium themes, controller and view
- Export active coupons
- Import coupons
- Generate bulk

**Comment by neo22s** [comment]
@oliverds there's many views of checkout pages that look the same...maybe use only 1? or do we really need one for each theme?

Delete coupon confirm modal you need to do it too ;)

Once we have all we need to move it to yclas:
https://bitbucket.org/neo22s/yclas/issues/390/coupon-system

I can do it no prob ;)

**Comment by neo22s** [comment]
Some improvements:

- [ ] index controller coupon display the product if theres (function product_description on model order) we will need to modify index.php
- [ ] create coupon select use friendly names for product selection
- [ ] edit coupon same as before

**Comment by neo22s** [comment]
Oliver can you do this in jquery? 

 on create, edit and bulk, maybe ask, you want to offer fixed amount or discount? then they click and appears the correct field. Instead of showing both.

**Comment by oliverds** [comment]
> Oliver can you do this in jquery?

Sure! I will take a look.

**Comment by neo22s** [comment]
ok! now its all done! @kotsios5 needs to do the guide. I will explain to you how works.

**Comment by neo22s** [comment]
Features:

- Create single coupon
- Update coupon
- Bulk creation of unique coupons
- You can export coupons (for example to send it to your provider or similar)
- You can import coupons (if your provider sends you the coupons)
- Widget coupons
- Add coupon on checkout
- Add coupon via URL

**Comment by neo22s** [comment]
Coupon fields:

- Name: Unique can not be repeated
- Id Product: Any means will work for any product. If you choose a product that coupon is onyl for that product
- Discount Amount: fixed amount to be discounted, ex 3 (will discount 3$ form the total).
- Discount Percentage: percentage of discount, ex 50, will remove 3$ from a $6 order.
- Number Coupons: number of times that unique coupon can be used. 
- Valid until: until when you can use that coupon
