### ISSUE TITLE
Custom fields not displayed after inserting incorrect captcha 

### ISSUE THREAD

**Issue by maartenklijnstra** [open-classifieds/openclassifieds2#1255]
When publishing an advertisement in a category, which has custom fields, the custom fields are not displayed anymore after a wrong captcha has been entered. 

Example: User posts an advertisement in the category Real Estate, using the real estate custom fields. After having filled out all the necessary fields and inserting an INCORRECT captcha, the user gets the message: "Warning Captcha is not correct". Under that warning message the form for the advertisement is displayed, but not the custom fields, because the category is not selected anymore. 

Furthermore: Previously selected pictures are not selected anymore after having inserted an incorrect captcha. Those need to be uploaded again.

Bug appeared in Firefox 38.0.1
Screen video: https://vid.me/qHo7

**Comment by oliverds** [comment]
@neo22s Now with [ajax captcha validation](https://github.com/open-classifieds/openclassifieds2/commit/f80bbf8bb2f9ba2e1a5b09328d73508aaad9b09e) implementation I think this issue can be market as solved.

**Comment by neo22s** [comment]
Yep it should ;)
