### ISSUE TITLE
Exif rotated images

### ISSUE THREAD

**Issue by telcy** [open-classifieds/openclassifieds2#1257]
I had some problems with exif rotated images and fixed it with this code:

/oc/classes/controller/panel/profile.php

--------------------------------
Replace Line 645-648

```
if (isset($_FILES['image'.$i]))
{
$filename = $form->save_image($_FILES['image'.$i]);
}
```

--------------------------------------
with this code:
```
if (isset($_FILES['image'.$i]))
{
	$filename = $_FILES['image'.$i]['tmp_name'];

	if(function_exists("exif_read_data") && !empty($filename) && in_array(exif_imagetype($filename), array(IMAGETYPE_JPEG,IMAGETYPE_TIFF_II,IMAGETYPE_TIFF_MM))) {
	    $exif = exif_read_data($filename);
	    if (!empty($exif['Orientation'])) {
	        $image = imagecreatefromjpeg($filename);
	        switch ($exif['Orientation']) {
	            case 3:
	                $image = imagerotate($image, 180, 0);
	                break;

	            case 6:
	                $image = imagerotate($image, -90, 0);
	                break;

	            case 8:
	                $image = imagerotate($image, 90, 0);
	                break;
	        }

	        imagejpeg($image, $filename, 100);
	    }
	}

	$filename = $form->save_image($_FILES['image'.$i]);
}
```

**Comment by neo22s** [comment]
Hello!

thanks for contributing. Could you share an image rotated? so we can test it?

**Comment by telcy** [comment]
Sure. This is an image which is rotated by Exif Param.
http://cloudmining-review.com/wp-content/uploads/0217748_rotated.jpg

The current system just ignores the exif param which leads to a misrotated image.

With the fix it will be displayed right after upload.

**Comment by neo22s** [comment]
yeah we need to do this also in the publish new advertisement, thanks!

**Comment by telcy** [comment]
That's right. I have not implented it into publish-new until now.

**Comment by telcy** [comment]
I have added the JPEG and TIFF check in the code to prevent errors with other file types.

**Comment by telcy** [comment]
Thanks. Working great. Only the JS generated Preview (publish new) is still showing wrong rotated. I don't know if this is possible to fix.

**Comment by neo22s** [comment]
Maybe some js could fix it not sure...

**Comment by oliverds** [comment]
Jasny Bootstrap extension needs to be updated. There is an open feature request for [exif orientation](https://github.com/jasny/bootstrap/issues/370).

**Comment by neo22s** [comment]
ok we will wait then.

**Comment by telcy** [comment]
You should add this at the beginning of the rotate function:

```
		if(!function_exists("exif_read_data") && !in_array(exif_imagetype($filename), array(IMAGETYPE_JPEG,IMAGETYPE_TIFF_II,IMAGETYPE_TIFF_MM))) {
			return $this;
		}
```
Otherwise it will fail on png images and servers sometimes do not support exif (or it is not activated).

**Comment by neo22s** [comment]
Also found issue on profile upload picture:
![image](https://cloud.githubusercontent.com/assets/241725/7980841/260ee09e-0aab-11e5-9e95-b606176ba0a9.png)

**Comment by neo22s** [comment]
and uploading ad pictures too
![image](https://cloud.githubusercontent.com/assets/241725/7980884/667cd2e4-0aab-11e5-87ef-48d8b8834c82.png)

![image](https://cloud.githubusercontent.com/assets/241725/7980898/89581792-0aab-11e5-856f-a23bdd2bea40.png)

**Comment by neo22s** [comment]
Also:

ErrorException [ 2 ]: exif_read_data(5570f2ac82f79m1.jpg): Incorrect APP1 Exif Identifier Code ~ APPPATH/common/classes/oc/image.php [ 23 ] in /var/www/yclas/ko332/system/classes/Kohana/Kohana/Exception.php:110
Seems theres something corrupted in the file then crashes, lets put a try/catch and if error return FALSE.

I will fix this.

**Comment by neo22s** [comment]
ok, got all fixed we where not returning $this in case of failure.
