### ISSUE TITLE
Slider doesn't display pictures on Responsive theme

### ISSUE THREAD

**Issue by maartenklijnstra** [open-classifieds/openclassifieds2#1268]
When using the "Responsive" theme on yclas.com, the picture slider on the homepage doesn't show any pictures, while the advertisement actually has one. Changing to another theme, for example "Ocean Premium", does display the picture of the advertisement in the slider. 

See the following two screenshots for an example: 
Responsive: http://imgur.com/oDWSTao,lxzKOyw
Ocean premium: http://imgur.com/oDWSTao,lxzKOyw#1

Bug appears on Firefox, Chrome and Safari.

**Comment by neo22s** [comment]
wow thanks! moved to yclas ;)
