### ISSUE TITLE
Welcome message on Panel for users

### ISSUE THREAD

**Issue by kotsios5** [open-classifieds/openclassifieds2#1272]
Welcome message on Panel for users who missed tour. Something like this: "Welcome _Username_, this is your Panel. You can manage your account and advertisements here."

**Comment by neo22s** [comment]
We need marketign to review this. which message we will place?

**Comment by oliverds** [comment]
This issue was before [User panel same look and feel as frontend theme](https://github.com/open-classifieds/openclassifieds2/issues/1245).

@kotsios5 do you think welcome message is still required?

**Comment by kotsios5** [comment]
I was not sure if it is required from the first place. It's not something important. If can remember there was a couple of suggestions on forum about this, so I created the issue to review it.

**Comment by neo22s** [comment]
lets close it then ;)
