### ISSUE TITLE
Message Conversation System

### ISSUE THREAD

**Issue by telcy** [open-classifieds/openclassifieds2#1275]
A message/conversation system would be nice. That would make the emails just additional as notification.

**Comment by neo22s** [comment]
please before opening a ticket check our other issues and our collaboration documentation:
https://github.com/open-classifieds/openclassifieds2/blob/master/CONTRIBUTING.md#reporting-issues

Duplicated:
https://github.com/open-classifieds/openclassifieds2/issues/708
