### ISSUE TITLE
Improve new/edit ad - Images

### ISSUE THREAD

**Issue by neo22s** [open-classifieds/openclassifieds2#1276]
- Check image size on the browser
- resize image in browser before sending
- start upload to server?

https://github.com/blueimp/jQuery-File-Upload/wiki/Client-side-Image-Resizing
http://www.plupload.com/
http://www.jqueryrain.com/demo/jquery-crop-image-plugin/
https://github.com/gokercebeci/canvasResize
https://blueimp.github.io/jQuery-File-Upload/

**Comment by oliverds** [comment]
jQuery-File-Upload requires to load too many dependancies:

`js/vendor/jquery.ui.widget.js
//blueimp.github.io/JavaScript-Templates/js/tmpl.min.js
//blueimp.github.io/JavaScript-Load-Image/js/load-image.all.min.js
//blueimp.github.io/JavaScript-Canvas-to-Blob/js/canvas-to-blob.min.js
//blueimp.github.io/Gallery/js/jquery.blueimp-gallery.min.js
js/jquery.iframe-transport.js
js/jquery.fileupload.js
js/jquery.fileupload-process.js
js/jquery.fileupload-image.js
js/jquery.fileupload-validate.js
js/jquery.fileupload-ui.js`

* Done file type and image size client-side validation.

* Client-side image resizing is pending.

**Comment by neo22s** [comment]
OMG, then what do we do?

**Comment by oliverds** [comment]
I'm thinking on use https://github.com/gokercebeci/canvasResize to generate a client-side resized base64 image and later somehow parse it on save_image function. That could work.

**Comment by neo22s** [comment]
sounds good to me. And how to upload before they click publish?

**Comment by oliverds** [comment]
That could be done with an ajax call but not really sure how to handle the image on server side, I mean the ad has not been created yet.

**Comment by neo22s** [comment]
lets go step by step ;)

Lets resize the image if possible in the local side.

Some ideas:

   - Upload the images to TMP folder.
   - TMP folder gets deleted every few minutes autmatically normally
   - If that doesnt work we create a folder called /images/tmp and a cron
   to delete the images older than X minutes ;)
   - Naming the images with some unique name like the session + timestamp +
   number of image
   - Something similar they do at segundamano.com

**Comment by neo22s** [comment]
this works awesome!!

@oliverds do we have the captcha validation via ajax? with that we have all in page so no need to upload before...since images are smaller already before sending them to server I mean.

**Comment by oliverds** [comment]
Cool!

Yep ajax captcha validation is working fine now.
