### ISSUE TITLE
Shipping custom field

### ISSUE THREAD

**Issue by neo22s** [open-classifieds/openclassifieds2#1284]
If user creates a custom field called shipping he can specify how much costs to ship the item.

When creating the order we will put the in the checkout the price of the item and another line the price of the shipping. This only for pay ads $order->id_product == Model_Order::PRODUCT_AD_SELL AND $ad->shipping > 0

Then the amount of the order needs to be shipping + price. This is set on controller ad action_buy

This way when comes back to the IPN we check the mc_gross that needs to be the same as order->amount.

Not any other change will be needed.

Todo documentation.

**Comment by neo22s** [comment]
This is in yclas?

**Comment by neo22s** [comment]
I will assign it to constantinos todo the documentation related ;) quite cool feature.

**Comment by oliverds** [comment]
> This is in yclas?

@neo22s I have done it in yclas too but commit on different branch ;)

**Comment by neo22s** [comment]
ok, closing here! lets not forget it!
