### ISSUE TITLE
Featured ads widget + Featured ads slider on listing page

### ISSUE THREAD

**Issue by kotsios5** [open-classifieds/openclassifieds2#1285]
Ads widget (when Type ads to display: Featured ads) and Featured ads widget are not displayed on the frontend.

![featured-ads-issue1](https://cloud.githubusercontent.com/assets/11571490/8005762/39def758-0b96-11e5-897c-3e0a18844c21.png)

![featured-ads-issue2](https://cloud.githubusercontent.com/assets/11571490/8005765/39ea6354-0b96-11e5-9a80-09bea1db264f.png)

On Appearance -> Theme Options, Display slider in listing = Featured, but on listing page slider is displaying all the ads. 

![featured-ads-issue3](https://cloud.githubusercontent.com/assets/11571490/8005763/39e5e194-0b96-11e5-8188-1aa4eeeb0150.png)

![featured-ads-issue5](https://cloud.githubusercontent.com/assets/11571490/8005766/39f08e28-0b96-11e5-958a-680df205b2c0.png)

However, on Settings -> Advertisement, Advertisements in home = Featured ads is working fine.

![featured-ads-issue4](https://cloud.githubusercontent.com/assets/11571490/8005764/39e9d4fc-0b96-11e5-9b89-8e59d81435a1.png)

**Comment by neo22s** [comment]
let me review today ;) thanks.
