### ISSUE TITLE
Replace placehold.it for canvas

### ISSUE THREAD

**Issue by neo22s** [open-classifieds/openclassifieds2#1291]
Canvas Or for a generic image or JS?

http://holderjs.com/ --> uses canvas. http://cdnjs.com/libraries/holder

its faster? more reliable?

**Comment by oliverds** [comment]
Holder.js should be faster since image placeholders are client-side generated and has a good browser support. Let's implement it.

**Comment by neo22s** [comment]
And this is quite nice: https://github.com/imsky/holder#fluid-placeholders
