### ISSUE TITLE
Error on Tools -> Migration

### ISSUE THREAD

**Issue by kotsios5** [open-classifieds/openclassifieds2#1292]
Error
Table oc2_accounts not found

Error
Table oc2_postshits not found

**Comment by neo22s** [comment]
that is because the OC version is below 1.7.x didnt exists those tables who is facing that issue?

**Comment by kotsios5** [comment]
I sent you the ticket. I can see that error too!

**Comment by neo22s** [comment]
She is not migrating from 1.7 to 2.x...
