### ISSUE TITLE
Subscribe widget not displaying the price bar

### ISSUE THREAD

**Issue by neo22s** [open-classifieds/openclassifieds2#1301]
![image](https://cloud.githubusercontent.com/assets/241725/8218711/ee89bef6-1544-11e5-97a8-b8ec4fcb45b9.png)

**Comment by neo22s** [comment]
Breaks all the JS of the page.

**Comment by oliverds** [comment]
Looks fine. Tested on Chrome, FF with default and ocean theme.
![screen shot 2015-06-22 at 18 11 09](https://cloud.githubusercontent.com/assets/7003648/8295420/15860622-190a-11e5-9543-c35f3af2db9a.png)

But something else could break it... What's the page url?

**Comment by neo22s** [comment]
yep working good, was in my local ;) lets close it.
