### ISSUE TITLE
Paypal email for sellers

### ISSUE THREAD

**Issue by neo22s** [open-classifieds/openclassifieds2#1308]
- add new field paypal email
- if exists use this email on view/paypal.php
- also on ipn
- only display in edit profile if User paypal link active

**Comment by neo22s** [comment]
Todo docs.

Works as follows by default

- Owner of site activate paypal link.
- customer creates an ad and puts a price
- customer will receive money in his email (email he registered) unless:

1- In case we create a custom Ad field called paypalaccount then goes here
2- if we create a user custom field called paypalaccount goes here (paypalaccount in ad has preference, this is in case your customer wants to sell form different paypal account)
3- by default we will use the customer normal email

Custom field ad and user
![image](https://cloud.githubusercontent.com/assets/241725/8361946/495cd08e-1b76-11e5-9aa4-f64e8910fe9e.png)


Also in custom fields mention in the footer this "hacks";
http://docs.yclas.com/how-to-publish-different-contact-email/
http://docs.yclas.com/use-shipping-custom-field/

**Comment by kotsios5** [comment]
Which email would be used if someone use both ways? (paypal email on user registration form and paypal email on publish new ad)

**Comment by neo22s** [comment]
In order, if finds one doesn't move forward, its an if :)
1- paypal email from ad
2- paypal email from user
3- email

see code https://github.com/open-classifieds/openclassifieds2/blob/c2fabe4cdbad4da21e68b6d13060227bebb2fba6/oc/classes/model/ad.php#L1421-L1428
