### ISSUE TITLE
Sort by favorites and rating

### ISSUE THREAD

**Issue by neo22s** [open-classifieds/openclassifieds2#1330]
Add sort by num of favorites and rating. 2 different sort.

Available to choose on settings->ads

**Comment by oliverds** [comment]
`ads` table will need a “favorites counter” column in order to sort by favorites, right?

**Comment by neo22s** [comment]
Havent thought about it....

In the orm we could have something like $ad->favorites->count() that will work, but wont work to do the SQL directly or to short by.

Modifying the model_favorite and overwriting the create and delete to ++ the ad field or -- in case is deleted. So yes I think is the best a counter. ;)

**Comment by oliverds** [comment]
Cool! That's what I thought.
