### ISSUE TITLE
Edit category custom fields

### ISSUE THREAD

**Issue by neo22s** [open-classifieds/openclassifieds2#1339]
When editing a category, display which custom fields belong. 

Would be super cool to be able to remove CF or to add directly from there.

**Comment by neo22s** [comment]
The delete function should delete the CF only if that CF has that category, if has more than 1 category just remove it from the category.

The add CF I think would be better like:
- Select of Existing CF and then clicks to add to add the category to an existing CF. 
- Instead of a full form, a button that says create new CF, then we pass as parameter the category to oc-panel/fields/new?id_category=3 or similar

What do you think?

**Comment by oliverds** [comment]
Ok.

Right, I didn't think it that way.

**Comment by neo22s** [comment]
no prob ;)

**Comment by neo22s** [comment]
you think is better too, no?
