### ISSUE TITLE
Select multiple categories/locations on panel

### ISSUE THREAD

**Issue by kotsios5** [open-classifieds/openclassifieds2#1351]
For example a checkbox next to each category or location that allows you to choose more than one if you want to delete, move under a parent, change order etc

**Comment by neo22s** [comment]
really difficult especially with the drag and drop

**Comment by oliverds** [comment]
"Drag and Drop" not easy at all.

Maybe it can't even be done with current JS plugin, we would need to find alternative plugins.

**Comment by neo22s** [comment]
No drag and drop maybe checkboxes?

**Comment by neo22s** [comment]
to make it easier I mean.
