### ISSUE TITLE
Problem with making ads featured

### ISSUE THREAD

**Issue by ThomWensink** [open-classifieds/openclassifieds2#1362]
When making a excisting ad a featured ad oc redirects me to the 'not found' page. 

I experience this on my own theme but also on my default theme. Could be my local dev environment but i dont think so.

**Comment by neo22s** [comment]
Can you paste the URLs? The step by step so we can reproduce it ;)

thanks!

**Comment by ThomWensink** [comment]
1. http://reoc.lo/oc-panel
2. http://reoc.lo/oc-panel/ad
3. Click the edit wheel.
4. Click the blue button of "highlight"
5. Browser question: "highlight?" press ok. (attachment 1)
6. Browser redirect to 404 (attachment 2)

![screenshot_2](https://cloud.githubusercontent.com/assets/11768128/8984705/8d1bda36-36d3-11e5-8ccf-1d3492d25026.png)
![screenshot_3](https://cloud.githubusercontent.com/assets/11768128/8984706/8d1d0f64-36d3-11e5-800b-4932c5ee88b2.png)

**Comment by neo22s** [comment]
Thanks!! :D thats enough for us to know what happens ;)

**Comment by neo22s** [comment]
Damn, I can not reproduce it, to which page redirects you that is a 404? the url.

When I click the feature button (blue one) I go to http://reoc.lo/ad/checkout/44

Is that happening on oc 2.5.0?

**Comment by ThomWensink** [comment]
I get redirected to http://reoc.lo/ad/to_featured/5

**Comment by neo22s** [comment]
did you setup the featured plans? on payment settings?

**Comment by kotsios5** [comment]
I cannot reproduce it too :S

**Comment by ThomWensink** [comment]
@neo22s Indeed resolved once i set up the featured plans on payment settings. This was the issue then.

Nonetheless maybe add a message if the featured plans settings are not configured? So its clearer for the admin that he should configure that in order to let featured ads work.
