### ISSUE TITLE
Confusing display behavior of number of ads in category

### ISSUE THREAD

**Issue by maartenklijnstra** [open-classifieds/openclassifieds2#1366]
Playing around with demo.yclas.com I found some confusing behavior of the number of ads displayed in a certain category.
When I click on the category "Bicycles" on the menu, I see that there are 5 items in the sub-category "Complete bicycles". See screenshot.
![screen shot 2015-07-31 at 09 52 58](https://cloud.githubusercontent.com/assets/5655874/9004084/6d4556ec-3773-11e5-954d-bb05f0b90c3f.jpg)

When I click on "complete bicycles" I get the following page that says there are not any ads in this category. 
![screen shot 2015-07-31 at 09 53 13](https://cloud.githubusercontent.com/assets/5655874/9004109/952e45c4-3773-11e5-8c30-80cb9b05c851.jpg)

This is because I'm in the location "Lyon" and  because there are not any ads in Lyon, nothing is displayed on the page. However, from my point of view the counter in the menu should then also display that there are 0 ads in the category, and not 5.

Desired behavior: display the number of ads in category that also will be displayed on the page, when clicking on the menu item.

**Comment by oliverds** [comment]
I think those category links should always go to listings page without a location selected and if user wants to filter ads by subcategory/location then they can use the sidebar locations widget

**Comment by neo22s** [comment]
So you mean never filter by location? so if I am browsing Spain from amny other countries when I click on  a category will remove the filter?

Clients will kill us I think.

I was thinking to fix the counter. And maybe add somewhere like categories for locations bla bla.

**Comment by oliverds** [comment]
I see, well then let's fix the category counter ;)

**Comment by Chinese1904** [comment]
how you could also solve the issue is by having a main category home page for each location and sub location and then the nav bar could be the total amount of ads without having a location selected.

**Comment by neo22s** [comment]
I tihnk public static function get_category_count() can receive id_location

If theres id_location!==NULL we add a new where statement:

where('a.id_location','=',$id_location)

we will need to replace in all the themes get_category_count() for something like get_category_count((Model_Location::current()->loaded())?Model_Location::current()->lid_location:NULL)

This should work :+1:

**Comment by oliverds** [comment]
ok category counter fixed but not sure where to put “categories for locations” message or maybe there is no need for it.

**Comment by neo22s** [comment]
your code much better than what I told you! well thought ;)

**Comment by neo22s** [comment]
there was 2 errors from before to get the siblings and get the category inside a single ad.

fixed ;)

**Comment by oliverds** [comment]
> there was 2 errors from before to get the siblings and get the category inside a single ad.
> 
> fixed ;)

Cool!

**Comment by neo22s** [comment]
also added cache...should work faster.
