### ISSUE TITLE
Location Front-End View is mixed up

### ISSUE THREAD

**Issue by GeorgeW** [open-classifieds/openclassifieds2#1368]
The back end panel shows correct location and nested locations, but when it shows posting an ad it is not correct. It shows a mix of different nested locations.

**Comment by neo22s** [comment]
Hello,

Please follow our guidelines: https://github.com/open-classifieds/openclassifieds2/blob/master/CONTRIBUTING.md#reporting-issues

Basically use our forum and we will create the issues ;)

thanks
