### ISSUE TITLE
Featured Plan above ad shows go featured for $1 but it's set for $5

### ISSUE THREAD

**Issue by GeorgeW** [open-classifieds/openclassifieds2#1375]
![screen shot 2015-08-01 at 10 53 37 pm](https://cloud.githubusercontent.com/assets/1289487/9024641/f38d6212-389f-11e5-8d28-85411c1d471a.png)

**Comment by neo22s** [comment]
Same as https://github.com/open-classifieds/openclassifieds2/issues/1374
