### ISSUE TITLE
Removing images of an ad

### ISSUE THREAD

**Issue by ThomWensink** [open-classifieds/openclassifieds2#1381]
I'm having trouble with the images of the ads that are being showed. 

1. First of all it is showing 2 images while the ad in the example (attachments) only has 1 image. The second image gives is just an error. 
2. I cannot remove the image of the ad. When i click remove it loads for a short time and just stays on the ad. 

Steps:
1. Go on the oc-panel to ads
![screenshot_1](https://cloud.githubusercontent.com/assets/11768128/9033148/0edc1a92-39c5-11e5-86d9-188d2c911ff2.png)
2. Click the edit button of a ad
3. Now when i scroll down it shows 2 images instead of one. The second image gives an error. 
![screenshot_2](https://cloud.githubusercontent.com/assets/11768128/9033174/35ec4f76-39c5-11e5-9cab-f228b7fc4758.png)
4. I click the remove button
5. Click 'yes, definitely'
![screenshot_3](https://cloud.githubusercontent.com/assets/11768128/9033181/46cf5bb2-39c5-11e5-8be2-b80789fd644f.png)
6. It loads for a very short time (appears to be only the animation, doesnt actually do anything i think) and then goes back to the edit ad screen. The image is still there.

**Comment by neo22s** [comment]
@kotsios5 can you test on 2.5.0 please? thanks

**Comment by kotsios5** [comment]
It doesn't happen on 2.5.0. It works perfect. I also check the db after removing the second image ,on oc_ads has_images = 1

**Comment by ThomWensink** [comment]
@kotsios5 Allright, strange the. Maybe its my local environment. Will let you know if i resolve it

**Comment by kotsios5** [comment]
@ThomWensink  Sure ;)

**Comment by neo22s** [comment]
Maybe file permissions @ThomWensink ? so the image cna not get removed?
