### ISSUE TITLE
Positioning issues on Splash theme

### ISSUE THREAD

**Issue by kotsios5** [open-classifieds/openclassifieds2#1382]
https://www.youtube.com/watch?v=YaYWComOIhs

**Comment by neo22s** [comment]
Happens in our demo too? he has added a lot of extra html or seems.

**Comment by neo22s** [comment]
also better on yclas issues since its a premium theme we do not have the code here ;)

**Comment by kotsios5** [comment]
i will create an issue on yclas, it happens in our demo too
