### ISSUE TITLE
Use a OC page and add its content to contact.html page

### ISSUE THREAD

**Issue by oliverds** [open-classifieds/openclassifieds2#1383]
Let users add content to its search.html page by creating a new config to set a page contact content.

**Comment by kotsios5** [comment]
I just installed OC to have this feature (to write the guide), but there is an issue:
![contact-page](https://cloud.githubusercontent.com/assets/11571490/9083143/77490076-3b60-11e5-8aad-3bf2802aa4c7.png)

**Comment by neo22s** [comment]
woiw! I will fixt it now.

launch in the meantime reoc.lo/oc-panel/update/250 will work ;)

**Comment by oliverds** [comment]
> woiw! I will fixt it now.
> 
> launch in the meantime reoc.lo/oc-panel/update/250 will work ;)

Thanks! forgot to commit modified `install.sql.php`.
