### ISSUE TITLE
Coupons on default theme from url

### ISSUE THREAD

**Issue by kotsios5** [open-classifieds/openclassifieds2#1387]
Coupons can be used on default theme by adding it on the url. On checkout page, only the final price is displayed:

![coupon-default theme](https://cloud.githubusercontent.com/assets/11571490/9089201/daf63eba-3b8b-11e5-86dc-4fd772e5c51a.png)

**Comment by neo22s** [comment]
coupons in free theme are like this on purpose not fully compatible xD only on premium themes will display.
