### ISSUE TITLE
Update button forum topic not working

### ISSUE THREAD

**Issue by maartenklijnstra** [open-classifieds/openclassifieds2#1390]
When clicking on the the 'update' button of a topic on the forum, it directs to the update page on the admin panel, but directly goes to the themes page. With no chance to update the topic. 

See video: https://vid.me/cUmh

The update button of a blog post shows the same incorrect behavior.

**Comment by oliverds** [comment]
It seems a tour redirect.

@maartenklijnstra have you ended the tour by clicking on http://awesomescreenshot.com/05854qls26?

**Comment by maartenklijnstra** [comment]
@oliverds I might have ended the tour by clicking that button yes. But, that must have been weeks/months ago.

**Comment by maartenklijnstra** [comment]
I have this issue also when saving a page on the admin panel. For example: if I changed the settings of advertisements and save the page, then I'm redirected to the themes page. This also happens with other pages, after having made changes.

**Comment by oliverds** [comment]
Can’t reproduce this on local or on 2181.dontcode.com

@neo22s do you have the same issue?

**Comment by neo22s** [comment]
me neither :S super strange, but I see the video :S how is that happening? weird.

**Comment by neo22s** [comment]
@kotsios5 can you reproduce it?

**Comment by kotsios5** [comment]
No! It works fine for me too

**Comment by neo22s** [comment]
ok, I will leave it open until monday to see if we can reproduce it by any chance if not we will delete.

thanks!
