### ISSUE TITLE
Advertisement settings on panel not working

### ISSUE THREAD

**Issue by maartenklijnstra** [open-classifieds/openclassifieds2#1391]
When going to settings --> advertisements on the admin panel, there is an error. See screenshot. http://imgur.com/KXFozmR

**Comment by oliverds** [comment]
Somehow config description_bbcode was missing on update https://github.com/oliverds/openclassifieds2/commit/8aa46ba80410a01ea8d93f59827adaf1f4d52296.

**Comment by neo22s** [comment]
ok! ;)

**Comment by oliverds** [comment]
@maartenklijnstra fixed on your test environment already.
