### ISSUE TITLE
Translation sv_SE

### ISSUE THREAD

**Issue by kotsios5** [open-classifieds/openclassifieds2#1392]
This error appear when I choose this locale sv_SE. I don't know if it's an issue or if it's my local's fault.

http://imgur.com/ZzJv8Md

**Comment by oliverds** [comment]
You are right! Same error activating sv_SE translation.

**Comment by kotsios5** [comment]
I think it doesn't happen on 2.4.1

**Comment by neo22s** [comment]
weird let me check it ;)
