### ISSUE TITLE
On OC update API redirects

### ISSUE THREAD

**Issue by oliverds** [open-classifieds/openclassifieds2#1393]
If OC installation gets updated then URL `/api/v1/categories/1`does a redirect to `/v1/categories?page=1`

Ex. http://2181.dontcode.com/api/v1/categories/1

**Comment by neo22s** [comment]
?¿?¿?¿? how is that even possible? :O

**Comment by oliverds** [comment]
Oh I saw the problem it is because 2181.dontcode.com has enabled migration redirect rules from 1.x to 2.0.x enabled (https://github.com/open-classifieds/openclassifieds2/blob/master/install/samples/example.htaccess#L156)

.htaccess file is not replaced on OC update.

**Comment by neo22s** [comment]
Damn!! htaccess! I will update the file replacing some lines :S hohoho
