### ISSUE TITLE
Settings HTML_Head / Footer not working properly

### ISSUE THREAD

**Issue by neo22s** [open-classifieds/openclassifieds2#1395]
```
<script src="//load.sumome.com/" data-sumo-site-id="7a788679ab29798f496923cf3d11e5de3c32bf6451eb7de9625c118b585a3387" async="async"></script>
```

If I paste this doesnt work but funny part is that we allow HTML in those fields...investigate :S

**Comment by oliverds** [comment]
Problem is on this line https://github.com/open-classifieds/openclassifieds2/blob/master/oc/classes/controller/panel/settings.php#L230 here it checks if config value was modified but it compares sanitised values.

So for `<script src="//load.sumome.com/" data-sumo-site-id="7a788679ab29798f496923cf3d11e5de3c32bf6451eb7de9625c118b585a3387" async="async"></script>` it was comparing an empty string.

**Comment by neo22s** [comment]
Oh. Nice! If you have the fix feel free to push ;)
