### ISSUE TITLE
Index of FAQ page not linking correctly

### ISSUE THREAD

**Issue by maartenklijnstra** [open-classifieds/openclassifieds2#1398]
The FAQ page does not show the correct part of the page when clicking on a link of the index. 

So, an example: 
1) On the FAQ page I click on this link: http://imgur.com/sc59Pcw,fCVbZhr,xGTo0mX
2) I get shown this: http://imgur.com/sc59Pcw,fCVbZhr,xGTo0mX#1
3) While I want to see this: http://imgur.com/sc59Pcw,fCVbZhr,xGTo0mX#2

**Comment by neo22s** [comment]
Seems due to the header of the theme and the scroll, any easy fix?

**Comment by oliverds** [comment]
This issue can be closed. Commit on [BB](https://bitbucket.org/neo22s/open-classifieds-private/commits/c3218ea69500ff128237b6fd549d1e68b2ce46b1).
