### ISSUE TITLE
Quickview on Listing Page

### ISSUE THREAD

**Issue by kotsios5** [open-classifieds/openclassifieds2#1413]
Quickview on Listing Page like http://templatecycle.com/tshop/v-1.4/white/category.html

http://forums.open-classifieds.com/suggestions/quickview.html

**Comment by neo22s** [comment]
what means like a landing?

**Comment by kotsios5** [comment]
if you move cursor on the image of an ad, quickview will appear to click on it

**Comment by neo22s** [comment]
maybe some theme could have it but not in all of them, if customer wants we can develop it to him
