### ISSUE TITLE
Search by user CF for ads

### ISSUE THREAD

**Issue by neo22s** [open-classifieds/openclassifieds2#1415]
On advanced search accept search by user and user CF filtering.

Also update search widget with user CF.

**Comment by neo22s** [comment]
We will need an option for user CF that is searchable that currently does not exists.

**Comment by neo22s** [comment]
ok, we will have option "searchable" important to check that is ISSET and that is TRUE to appear on search form. to avoid any issues

**Comment by neo22s** [comment]
I tihnk we can close this, no?

**Comment by oliverds** [comment]
Yep. Already done.

Commits https://bitbucket.org/neo22s/open-classifieds-private/commits/4647d5cf7deefddb7c6327d7328ea5ea3f1c5bfe and https://github.com/open-classifieds/openclassifieds2/commit/f5f0f925fd6c4c2a6c58cf336ff352b5bf6e13c5
