### ISSUE TITLE
json_encode() expects at most 2 parameters, 3 given on Edit Ad page

### ISSUE THREAD

**Issue by AndreasRicci** [open-classifieds/openclassifieds2#1417]
See title and the suggested the fix here: https://github.com/open-classifieds/openclassifieds2/commit/770d48c807267e92348340758d56273e92a4a8e7#commitcomment-12730054

**Comment by neo22s** [comment]
Thanks! want to do a pull request?

**Comment by neo22s** [comment]
ok, already done, thanks!

**Comment by AndreasRicci** [comment]
No problem! Happy to help.
