### ISSUE TITLE
Not being able to delete categories

### ISSUE THREAD

**Issue by ThomWensink** [open-classifieds/openclassifieds2#1419]
Running OC 2.5.0 and trying to delete categories. (http://pinforest.dontcode.com/)

1. Go to categories. Standard categories are installed there. 
2. Click "delete all categories" 
3. Click delete on popup modal
4. "Success. All categories were deleted. " 
5. Nothing happens. Categories are still there 

![screenshot_1](https://cloud.githubusercontent.com/assets/11768128/9301140/844cbb1c-44cc-11e5-8db4-198904d23ff5.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/11768128/9301139/844c721a-44cc-11e5-8e4e-478f63f19851.png)
![screenshot_3](https://cloud.githubusercontent.com/assets/11768128/9301142/844f5bd8-44cc-11e5-84c3-e7d993506a8f.png)

**Comment by neo22s** [comment]
Did you clean the cache?

**Comment by ThomWensink** [comment]
I did, the categories are still there.

**Comment by neo22s** [comment]
damn I have tried in local in different scenarios and worked good :sa: 
but not in this site, no freaking clue why not :O

**Comment by neo22s** [comment]
ok, clean cache and all went well, I will improve this.

thanks!
