### ISSUE TITLE
Error when updating to 251 - implode(): Invalid arguments passed

### ISSUE THREAD

**Issue by AndreasRicci** [open-classifieds/openclassifieds2#1421]
The error is as follows:

ERROR: ErrorException [ 2 ]: implode(): Invalid arguments passed ~ APPPATH/classes/controller/panel/update.php [ 36 ] in /home/dashta5/public_html/dev/app/oc/kohana/system/classes/Kohana/Kohana/Exception.php:110

It appears to be caused by custom fields which do not have "values", for example a "date" type custom field.

**Comment by AndreasRicci** [comment]
Fix here: https://github.com/DashTask/openclassifieds2-official/commit/bcb1b34a033c04a9ee416f0febf96e86de517388

**Comment by neo22s** [comment]
can you do a pull request?

thanks!

**Comment by AndreasRicci** [comment]
Here you go: https://github.com/open-classifieds/openclassifieds2/pull/1422

**Comment by neo22s** [comment]
thanks!

**Comment by AndreasRicci** [comment]
No problem!
