### ISSUE TITLE
Delete messages

### ISSUE THREAD

**Issue by neo22s** [open-classifieds/openclassifieds2#1423]
How can we delete messages?

Suggestion
http://forums.open-classifieds.com/soporte/messaging-system-online-offline-chat.html

See also:
https://bitbucket.org/neo22s/yclas/issues/434/delete-messages

**Comment by neo22s** [comment]
There's few challenges:
- User can delete (we will archive it), but what happens to the TO user? he may have it in different status
- If there's a reply we should change the status of the parent message?
- If is spam the status should not be changed.
- Can the user remove messages from spam?
- If you have marked a message as spam and they try to send you another one from same TO? we mark it as spam? or we just do not allow to contact you?
- 

Status delete can be fixed with something like this on the parent message:
```
const STATUS_DELETED        = 60;
const STATUS_DELETED_FROM   = 61;
const STATUS_DELETED_TO     = 62;

//this are the status where messages will be displayed
public static $status_display = array(self::STATUS_NOTREAD,
                                        self::STATUS_READ);
```

**Comment by neo22s** [comment]
I need to discuss this with @oliverds since I do not see clearly what we want.

**Comment by oliverds** [comment]
> User can delete (we will archive it), but what happens to the TO user? he may have it in different status

I’m thinking on having two status columns one for receiver and another for sender so we can later mark the message thread status according to the user.

> If there's a reply we should change the status of the parent message?

I think status should be for message threads

> If is spam the status should not be changed.

no?

> Can the user remove messages from spam?

I don't think so. Message thread status can be changed but not as per message

> If you have marked a message as spam and they try to send you another one from same TO? we mark it as spam? or we just do not allow to contact you?

Do nothing. I mean we are not trying to clone an email client. If an user is abusing the system then site administrator should disable that user.

**Comment by neo22s** [comment]
Yes, It's what I thought we will need 2 new statuses. Status_from and status_to ... then remove the normal status so each user can choose. 

Its going to be a bit complex to code since theres few scenarios and we will need to review the API.

Will work on this on the weekend. Lets see.

**Comment by neo22s** [comment]
Also detected that if we have the Id device of the user theres no need of sending the email... since duplicates the message.

**Comment by neo22s** [comment]
Doing a huge refactor of code to avoid duplicated code, and functions receive model_user instead of id_user.

I will post what I have done today :S

**Comment by neo22s** [comment]
testing before moving forward ;)

**Comment by oliverds** [comment]
Oh I see, nice I will take a look.

**Comment by neo22s** [comment]
Working on the status...big mess hohoho I tihnk I will finish tomorrow loads of files :S not sure why I didnt think about this when I was designing it! hehe

**Comment by neo22s** [comment]
@oliverds we need to test this really good. Also we need in the message page add the Alert before they delete or mark as Spam a message.

**Comment by oliverds** [comment]
Complex queries for [get_thread](https://github.com/open-classifieds/openclassifieds2/blob/2e3daa63a530d87106633df531d78609dd364a80/oc/classes/model/message.php#L266).

Nice code! Taking note!
