### ISSUE TITLE
Price field placeholder

### ISSUE THREAD

**Issue by kotsios5** [open-classifieds/openclassifieds2#1425]
Maybe it's confusing some users when they are trying to post ads, when they see "$1.00" but they have to enter "1".

https://yclas.com/panel/support/ticket/2571

**Comment by neo22s** [comment]
he is clearly overreacting....losing many customers? how does he know? :O

we can review it.

**Comment by neo22s** [comment]
actually he has a custom theme, lets change it on his theme. clsoe this open it on bitbubket and we change it ;)
