### ISSUE TITLE
Default theme - location selected is incorrect after failing to post an ad

### ISSUE THREAD

**Issue by AndreasRicci** [open-classifieds/openclassifieds2#1433]
After attempting to post an ad, but failing, the default theme populates the id of the location selected with the category id instead.

**Comment by neo22s** [comment]
Wow! good eye! thanks ;)

**Comment by AndreasRicci** [comment]
You're welcome :)

**Comment by AndreasRicci** [comment]
This can now be closed: https://github.com/open-classifieds/openclassifieds2/commit/91cab34935a63ff21d92dcdbbd0083f5faa5677f
