### ISSUE TITLE
Photo uploads using Internet Explorer 11

### ISSUE THREAD

**Issue by oliverds** [open-classifieds/openclassifieds2#1435]
When using Internet Explorer 11, and uploading images while posting an advertisement, the select image process has to be completed twice in order to see the image uploaded.

*Issue reported at: http://forums.open-classifieds.com/support/photo-uploads-using-internet-explorer-11-1.html*

**Comment by oliverds** [comment]
I still have to reproduce this but I don't have IE.

**Comment by kotsios5** [comment]
I don't have IE either.. I just tried from another computer but I was not able to reproduce this issue. 
> the select image process has to be completed twice in order to see the image uploaded.
I was able to see the image from the first time.

**Comment by oliverds** [comment]
Thanks @kotsios5 

As soon as I have access to an IE browser will test it too.

**Comment by oliverds** [comment]
Ok tested on IE 11 and it seems to be working just fine.

So this issue can be closed.

**Comment by neo22s** [comment]
he ust have a plugin or something installed....

**Comment by oliverds** [comment]
It seems we have [another user](http://market.open-classifieds.com/oc-panel/support/ticket/20066) reporting this issue but I’m unable to reproduce it yet.

Unfortunately currently I don't have any windows computer for testing.

**Comment by oliverds** [comment]
http://dev.modern.ie/tools/vms/mac/ could be useful.

**Comment by neo22s** [comment]
Tomorrow I test in the office, but yeah few customers complaining with the same :S

**Comment by Xav1Arnau** [comment]
![ie bug](https://cloud.githubusercontent.com/assets/3284911/9599813/0d4c4862-5097-11e5-8260-420f084ffabd.png)

**Comment by Xav1Arnau** [comment]
The first time you select a picture it does not show in the preview. If you select it again in a used box it does show.

**Comment by neo22s** [comment]
![image](https://cloud.githubusercontent.com/assets/241725/9599936/f4838d8a-5097-11e5-8eaa-cffd95d8ba29.png)

But all pictures where uploaded :O

**Comment by oliverds** [comment]
Ok it seems a problem with [Jasny File input](http://www.jasny.net/bootstrap/javascript/#fileinput). I will review [new.js](https://github.com/open-classifieds/openclassifieds2/blob/master/themes/default/js/new.js) and try to find what could cause this issue.
