### ISSUE TITLE
Click to feature or bring on top

### ISSUE THREAD

**Issue by kotsios5** [open-classifieds/openclassifieds2#1440]
If featured ads and bring on top are OFF, when I click as admin to feature or bring on top from /oc-panel/ad I receive the message "Page not found."
Maybe it would be better to hide those options if they are switched OFF on settings -> payment, also it will help users to know that those options are OFF.

(there are some tickets related to this on both yclas & oc)

**Comment by neo22s** [comment]
agree ;)
