### ISSUE TITLE
No option to remove Featured from ad

### ISSUE THREAD

**Issue by kotsios5** [open-classifieds/openclassifieds2#1441]
The only way to remove featured from an ad is by changing the Featured value on oc2_ads to NULL on phpmyadmin. There is no option on panel for that.

Also, if the ad is featured, admin still have to option to feature the ad on /oc-panel/ad, by clicking the wheel button

![featured-issue](https://cloud.githubusercontent.com/assets/11571490/9490749/aae4abc2-4bf2-11e5-8a26-f3b59fdfcf9b.png)

**Comment by neo22s** [comment]
Maybe if ad is featured and still featured (<date) then the button should do the function of unfeature?

**Comment by neo22s** [comment]
but risky...what if customer paid for this service?

**Comment by kotsios5** [comment]
I think we had this option before.. Also, this option can be useful if someone featured an ad (obviously mark as paid) by accident. But if it's risky they can unfeature the ad from phpmyadmin.

**Comment by neo22s** [comment]
agree I will take a look ;)
