### ISSUE TITLE
Facebook share ads

### ISSUE THREAD

**Issue by kotsios5** [open-classifieds/openclassifieds2#1445]
Facebook share ads button does not take details from all ads. 
For example, 
it's working fine for this: http://www.clic.nc/electromenager/grille-pain-bosch.html 
but not for this http://www.clic.nc/chaussures/chaussures-de-sport.html

On local it's not working for any ad.

Edit: Link that's not working!

**Comment by neo22s** [comment]
the 2 links are the same. Whats the other link?

**Comment by kotsios5** [comment]
My mistake! I edited the issue.

**Comment by neo22s** [comment]
Strange... I do not think I can do anything here since in the source code we pass the parameters correctly:

```
<meta property="og:image"   content="http://www.clic.nc/images/2015/08/27/19/thumb_chaussures-de-sport_1.jpg"/>
<meta property="og:title"   content="Chaussures de sport - Chaussures - Nouméa - CLIC.NC"/>
<meta property="og:description"   content="Chaussures de sport dans Chaussures sur CLIC.NC"/>
<meta property="og:url"     content="http://www.clic.nc/chaussures/chaussures-de-sport.html"/>
<meta property="og:site_name" content="CLIC.NC"/>
```
