### ISSUE TITLE
Charset issue while formatting prices

### ISSUE THREAD

**Issue by oliverds** [open-classifieds/openclassifieds2#1449]
![safari](https://cloud.githubusercontent.com/assets/7003648/9593395/55427d5a-5013-11e5-8416-d4f47b9cd93c.jpg)

http://demo2.open-classifieds.com/market/smart-fortwo.html?language=ru_RU

**Comment by oliverds** [comment]
Actually with ru_RU translation activated

`localeconv()` returns:

<pre>
array(18) {
  ["decimal_point"]=>
  string(1) ","
  ["thousands_sep"]=>
  string(1) "�"
  ["int_curr_symbol"]=>
  string(4) "RUB "
  ["currency_symbol"]=>
  string(3) "���"
  ["mon_decimal_point"]=>
  string(1) "."
  ["mon_thousands_sep"]=>
  string(1) "�"
  ["positive_sign"]=>
  string(0) ""
  ["negative_sign"]=>
  string(1) "-"
  ["int_frac_digits"]=>
  int(2)
  ["frac_digits"]=>
  int(2)
  ["p_cs_precedes"]=>
  int(0)
  ["p_sep_by_space"]=>
  int(1)
  ["n_cs_precedes"]=>
  int(0)
  ["n_sep_by_space"]=>
  int(1)
  ["p_sign_posn"]=>
  int(1)
  ["n_sign_posn"]=>
  int(1)
  ["grouping"]=>
  array(2) {
    [0]=>
    int(3)
    [1]=>
    int(3)
  }
  ["mon_grouping"]=>
  array(2) {
    [0]=>
    int(3)
    [1]=>
    int(3)
  }
}
</pre>

**Comment by oliverds** [comment]
Issue fixed with https://github.com/oliverds/common/commit/90e56550bf9ba11af7022088926aefceb91e830a

**Comment by neo22s** [comment]
ok, I think is better, and in case the locale doesnt exists we use the dropin....so lets keep what you did ;)
