### ISSUE TITLE
Listing page, infinite scroll, grid view

### ISSUE THREAD

**Issue by kotsios5** [open-classifieds/openclassifieds2#1455]
When grid view is selected and infinite scrolling is enabled, all of the new ads that come into view are in list mode instead of grid mode. 

http://market.open-classifieds.com/oc-panel/support/ticket/20121

I can reproduce this in all themes.

**Comment by oliverds** [comment]
Commit on [BB](https://bitbucket.org/neo22s/open-classifieds-private/commits/3f25903d24aa574c9ef9147d1b30ef9caef11dc0).

I was only able to reproduce this issue on newspaper and splash themes.

New issue https://bitbucket.org/neo22s/yclas/issues/478/
