### ISSUE TITLE
Price field only allows numbers and decimals

### ISSUE THREAD

**Issue by neo22s** [open-classifieds/openclassifieds2#1456]
Some ideas http://stackoverflow.com/questions/469357/html-text-input-allow-only-numeric-input/28838789

numbers + ',' or '.'

**Comment by oliverds** [comment]
Price field is validated by javascript already:

<img width="352" alt="screen shot 2015-09-03 at 09 35 23" src="https://cloud.githubusercontent.com/assets/7003648/9661233/64e2d936-521f-11e5-87db-94f2990589f0.png">

But we should change error message to something like “Please enter only numbers and decimals”

**Comment by neo22s** [comment]
But only when you click on submit no? what I did is use the keyup event so only numbers and '.' its allowed.

**Comment by oliverds** [comment]
> But only when you click on submit no? what I did is use the keyup event so only numbers and '.' its allowed.

JS validation is also done on keyup.

**Comment by neo22s** [comment]
oh damn...then I need to remove what I did :( 

But not sure why was not working to me :S

let me test it again.

**Comment by neo22s** [comment]
ok but it lets you write letters thats what I want to avoid. ;)

The issue I see now is that doesnt accept the ',' since isNumeric of jquery thinks 2324,56 is not numeric :S damn!

**Comment by oliverds** [comment]
Sorry I meant that validation is done on input focus out.

It let you write letters etc. but on focus out displays an error.

Maybe with regex: https://github.com/open-classifieds/openclassifieds2/blob/master/themes/default/js/new.js#L419

**Comment by neo22s** [comment]
or just an if... xD

**Comment by neo22s** [comment]
Damn can not make it work :sa: 

I have tried, regex, ^[0-9]{1,18}([,.]{1}[0-9]{1,3})?$ , var code = e.keyCode || e.which; code = 44

and nothing :S
