### ISSUE TITLE
Option to change the front image of your ad

### ISSUE THREAD

**Issue by kotsios5** [open-classifieds/openclassifieds2#1459]
"Also, it would probably be nice as well to have the option to later on change the picture that your ad is visualized with. Let's say you upload 5 images and you want to change the front picture to a better picture of the puppy that you are selling, then I would be beneficiary for the user to have the option to get it changed."

http://market.open-classifieds.com/oc-panel/support/ticket/20124

**Comment by neo22s** [comment]
good idea!

**Comment by neo22s** [comment]
Just swap the name of the selected image with the first one ;)

In edit ad images a button to make that picture primary.
