### ISSUE TITLE
Don't display list/grid/sort buttons when there are no ads

### ISSUE THREAD

**Issue by kotsios5** [open-classifieds/openclassifieds2#1460]
right now, even though there might not be any ads in a location/category, the list/grid/sort buttons appear, when they shouldn't. 
Just change the code in listing.php from

http://pastebin.com/Uz18PpuY

http://market.open-classifieds.com/oc-panel/support/ticket/20113

**Comment by neo22s** [comment]
Please ask the customer he can collaborate on github better! xD
