### ISSUE TITLE
Flag ads as inappropriate

### ISSUE THREAD

**Issue by kotsios5** [open-classifieds/openclassifieds2#1461]
Option for users to flag ads as inappropriate.

**Comment by neo22s** [comment]
Idea:

- Table flagged
- we store id_user id_ad date
- Only registered users can flag
- Only 1 flag per user/ad
- In advertisements panel we show new column with the count

**Comment by neo22s** [comment]
Nah, just simply goes to contact form with subject and description filed. Goes to admin and he decides.

**Comment by neo22s** [comment]
test message telegram
