### ISSUE TITLE
Increasing space on theme market

### ISSUE THREAD

**Issue by maartenklijnstra** [open-classifieds/openclassifieds2#1465]
When changing categories on the themes market, the space between the description of the theme and the two buttons increases. Not a major issue, but ugly I think.

To reproduce:
1) go to http://open-classifieds.com/market/
2) go to themes
3) go to the cars category
4) go to the realty category
5) go to the cars category
6) go to the realty category
7) etc...
8) see that the space between the description and the two buttons increases

See screen recording: https://vid.me/9U83

**Comment by neo22s** [comment]
Better on trello since this is not related to the software is related to our web xD I will create it now.thanks
