### ISSUE TITLE
Infinite scroll pagination

### ISSUE THREAD

**Issue by kotsios5** [open-classifieds/openclassifieds2#1467]
When infinite scroll is enabled, at the of the page pagination still appear and is clickable.

**Comment by neo22s** [comment]
but I think its ok like this

**Comment by kotsios5** [comment]
Maybe he thought it's a bug http://market.open-classifieds.com/oc-panel/support/ticket/20231

**Comment by neo22s** [comment]
really tell him to use github xD

I will close ;)
