### ISSUE TITLE
Images of new ads on infinite scroll

### ISSUE THREAD

**Issue by kotsios5** [open-classifieds/openclassifieds2#1469]
Images of new ads which don't have image, are not displayed. Instead of the image only alt text is displayed.

![infinite-scroll-image](https://cloud.githubusercontent.com/assets/11571490/9679662/25046ef8-52f9-11e5-9617-2e951815f685.png)

**Comment by oliverds** [comment]
This can be closed since only applies for premium themes. Commit https://bitbucket.org/neo22s/open-classifieds-private/commits/c507c8edee594c180b8938d62f10a3cdc5bfa365
