### ISSUE TITLE
Settings button on infinite scroll

### ISSUE THREAD

**Issue by kotsios5** [open-classifieds/openclassifieds2#1473]
Settings button (gear icon) on infinite scroll is now working for new ads.
![settings-button-infinite-scroll](https://cloud.githubusercontent.com/assets/11571490/9712221/e4710274-5551-11e5-9919-4d9324a84b67.png)

**Comment by neo22s** [comment]
https://bitbucket.org/neo22s/open-classifieds-private/commits/854694193517604dd65a5acdef3587142caffa20
