### ISSUE TITLE
Chrome on Windows 8.1

### ISSUE THREAD

**Issue by kotsios5** [open-classifieds/openclassifieds2#1475]
http://greenlandoasis.com/error/page%20error.gif
http://greenlandoasis.com/error/category%20error.gif
http://greenlandoasis.com/error/category%20error%202.gif
http://greenlandoasis.com/error/login%20error.gif

**Comment by kotsios5** [comment]
I can't find any pc with is using windows 8.1

**Comment by neo22s** [comment]
but this is really strange....they need to update chrome

**Comment by kotsios5** [comment]
he is using the latest version of chrome..

**Comment by neo22s** [comment]
damn...ok we will review if we can :S

**Comment by oliverds** [comment]
> About http://greenlandoasis.com/error/category%20error.gif
Xavi mentioned something like it to me but could not reproduce it.

Will investigate those issues.

**Comment by neo22s** [comment]
I can ask xavi to test it tomorrow

**Comment by Xav1Arnau** [comment]
This is weird because when I told oliver I thought he fixed it because I stopped seeing the bug. I checked now and things work propperly.

x-files

**Comment by neo22s** [comment]
ok, this sucks :S if we can not reproduce it we can not fix it.

**Comment by neo22s** [comment]
@oliverds maybe changing the drag and drop plugin for another one? :(

**Comment by oliverds** [comment]
Or maybe updating the plugin. Latest release is from June 27 https://github.com/johnny/jquery-sortable/releases.

**Comment by neo22s** [comment]
aha let's try that ;)

**Comment by oliverds** [comment]
Bug found on oc-panel tour. It should fix http://greenlandoasis.com/error/page%20error.gif, http://greenlandoasis.com/error/category%20error%202.gif, http://greenlandoasis.com/error/login%20error.gif

Updated assets but I'm not sure if solves the sortable issue.

**Comment by Xav1Arnau** [comment]
Tested and it looks good. From time to time edit or delete buttons don't respond and the script tries a reposition so it occurs to me that maybe it is possible to leave the buttons area outside the "draggable area" to avoid conflicts with buttons. Don't know if it possible but it would help I think.

**Comment by neo22s** [comment]
I tihnk is good idea to disable some draggable parts?

**Comment by oliverds** [comment]
After some trial and error the fix was easier by using delay option.

https://github.com/oliverds/openclassifieds2/commit/e4299c5cdda45c7784d87e25204073634e43c3e2#diff-79b2a5ef11fea4bb29690e1cba048df6R4
