### ISSUE TITLE
how to select multiple categories to ads...

### ISSUE THREAD

**Issue by vimalrajks** [open-classifieds/openclassifieds2#1483]
How to Select Multiple Categories to a ad.

![cat tree](https://cloud.githubusercontent.com/assets/14209911/9779618/2cb70e84-579b-11e5-8b82-decd42692ec1.png)

**Comment by neo22s** [comment]
Please use our forum for any question:
http://forums.open-classifieds.com/

And remember to update your version and theme. regards
