### ISSUE TITLE
Manually change home location

### ISSUE THREAD

**Issue by kotsios5** [open-classifieds/openclassifieds2#1491]
What I would enhance is that users should be able to manually set a home location. For instance, if I change my location to none, then there is no way to set my location back to any until the cookie expires. But also if I am in a different state and I would like to have my actual home location set as the home location, then there is no way to get that set up.

http://market.open-classifieds.com/oc-panel/support/ticket/20529

**Comment by neo22s** [comment]
But what this means?

/?sort=distance

**Comment by kotsios5** [comment]
Edit: remove /?sort=distance

**Comment by Chinese1904** [comment]
In this case I think it would be a good idea to utilize the location widget. Any time a location is pressed, that should alter and localize the home page and it would solve the issue of not being able to change it for the most part.

**Comment by neo22s** [comment]
Lets create a widget to choose another home location

**Comment by neo22s** [comment]
Also be able to change current long and latitude

![image](https://cloud.githubusercontent.com/assets/241725/11566539/32897376-99e3-11e5-82dc-c093a4c854e4.png)

**Comment by neo22s** [comment]
awesome! but how do we select from a map? theres only the location selector.

**Comment by oliverds** [comment]
On listings view there should something like...

![11](https://cloud.githubusercontent.com/assets/7003648/11900195/cd088360-a569-11e5-8265-d0c531d90f04.gif)

**Comment by neo22s** [comment]
ahaaa in gummy doesnt work in olson cool, love itt nice man!! :D

![image](https://cloud.githubusercontent.com/assets/241725/11900329/8f91b060-a5a5-11e5-99c4-1e53e3f5341b.png)

**Comment by oliverds** [comment]
> ahaaa in gummy doesnt work in olson cool, love itt nice man!! :D

Thx. Checking gummy theme then.
