### ISSUE TITLE
LinkedIn Social Auth

### ISSUE THREAD

**Issue by kotsios5** [open-classifieds/openclassifieds2#1493]
Not able to login using LinkedIn. 

This is the error:
Error: please try again! Authentication failed! LinkedIn returned an invalid Token.

**Comment by kotsios5** [comment]
Maybe this is related:
https://github.com/hybridauth/hybridauth/issues/470

**Comment by neo22s** [comment]
ok, lets take a look maybe we need to update the library.

**Comment by neo22s** [comment]
No idea whats wrong :sa: 

I have written in their forums....

**Comment by neo22s** [comment]
anyway I am going to try update the library...lets see if I do not break anything eheheh

**Comment by neo22s** [comment]
updating fixed the linkedin issue, let me see if the otker providers will keep working, testing on forum

**Comment by neo22s** [comment]
ok, seems it works! I will update the library! ;)

**Comment by neo22s** [comment]
https://github.com/open-classifieds/common/commit/4db26c22eb1f9e978f44d985cb8239ecef6447d1
