### ISSUE TITLE
Edit ad + moderation on

### ISSUE THREAD

**Issue by kotsios5** [open-classifieds/openclassifieds2#1495]
When moderation = moderation on, if a user edit his ad, it needs moderation from admin to be published again. If admin confirms this ad, then the ad will be displayed on top again (publish date will change). That makes users to avoid purchase 'Bring on top'.

Source or better explanation:
http://market.open-classifieds.com/oc-panel/support/ticket/20691

**Comment by neo22s** [comment]
Correct. Intended behaviour. Up to the moderator to republish or not ;)
