### ISSUE TITLE
Site description when landing page = listing

### ISSUE THREAD

**Issue by kotsios5** [open-classifieds/openclassifieds2#1500]
Site description (from settings -> general) is not displayed when landing page = listing.

**Comment by neo22s** [comment]
You mean in the source code, no? mmmm a bit complex but can be done.

**Comment by kotsios5** [comment]
On google too!

From forum: http://forums.open-classifieds.com/support/ladning-page-site-description.html

**Comment by neo22s** [comment]
That means is not in the source code in the HTML. Meta description.
