### ISSUE TITLE
New possible upgrades + theme options

### ISSUE THREAD

**Issue by ThomWensink** [open-classifieds/openclassifieds2#1502]
Allright, i had some new ideas that i'd like to pitch to all of you. Here goes: 

1. The first idea i had is a pre selected icon library for category icons. What i've seen lately is that users tend to leave the category icon field empty. This isn's bad, themes work perfectly without the category icons. But it's way easier for new users to overview the homepage if the categories have icons. You can scan the homepage way faster. 

Now the reason this happens (i think) is because it is a upload field. Now having an upload field here should remain this way, but maybe we should add another option here. A button that opens a library with (pre chosen by us) icons that we know will fit nicely. Users dont have to search online for icons themselves and can easily select one in this library. Fact is that normal OC users are not designers and upload icons that are either horrible or just leave the field empty. With this icon library we can offer them a quick solution. Maybe we could implement this upgrade in the next release. 

2. I got this second idea just recently while working with a Wordpress premium theme. This theme offered not just 10 color schemes you could choose from, but instead offered a color selector from where the admin could select their own RGB code. 

This way instead of offering the user like 10 or 20 color schemes you could have a inifite color possibilities. The user selects a primary color and a secondary color and updates the theme under theme options. Maybe we could implement something similar into a premium theme?

3. If something like this is possible, you could extend on this idea with fonts. Now normally we offer a theme with 1 font, the one we implemented. Now Google offers a huge library with google fonts. I'm not sure but i think all of them are license free and they are very easily implemented. We could make a pre selected list of like 20 fonts the user can choose from at theme options and voila, more versatility.

In general i think with these theme options we could make our themes are lot more versatile. We'd see a lot more different different forms of themes (as on other colors schemes, fonts) while they are still running the same theme. 

*Just some ideas i had*

**Comment by neo22s** [comment]
Thanks Thom! I will put this in separated issues on trello since its related to premium themes.
