### ISSUE TITLE
Location and Category description for seo

### ISSUE THREAD

**Issue by kotsios5** [open-classifieds/openclassifieds2#1508]
It will be good if you make location and category description readable for search engine only. 

http://forums.open-classifieds.com/suggestions/location-and-category-descriptuion-for-seo.html

**Comment by oliverds** [comment]
**Not a Google Ranking Factor**

Google announced in September of 2009 that neither meta descriptions nor meta keywords factor into Google's ranking algorithms for web search. Google uses meta descriptions to return results when searchers use advanced search operators to match meta tag content, as well as to pull preview snippets on search result pages, but it's important to note that meta descriptions do not to influence Google's ranking algorithms for normal web search.

https://moz.com/learn/seo/meta-description
