### ISSUE TITLE
Authorize.net review

### ISSUE THREAD

**Issue by kotsios5** [open-classifieds/openclassifieds2#1509]
"Authorize.net says the information that is being sent over from our website does not contain their names just their credit card info."

See: http://market.open-classifieds.com/oc-panel/support/ticket/20752

**Comment by neo22s** [comment]
I need to review this since it may have changed their API.

**Comment by neo22s** [comment]
all seems to be good: https://github.com/AuthorizeNet/sdk-php/blob/master/lib/AuthorizeNetAIM.php#L106 contacted customer.

**Comment by kotsios5** [comment]
"The original issue about processing payments has more to do with how much info authorize.net is getting from us. Currently the pay with card does process payments but it does not include card name or expiration date. authorize.net informed us that the information being sent over does not include names so they cannot label a receipt correctly."

http://market.open-classifieds.com/oc-panel/support/ticket/21220

**Comment by neo22s** [comment]
contacted customer thanks

**Comment by neo22s** [comment]
tested on devel with test environment on authorize and works
