### ISSUE TITLE
Folder per language - login issues

### ISSUE THREAD

**Issue by kotsios5** [open-classifieds/openclassifieds2#1520]
Here is scenario to reproduce the issue
1) UserA is registered on www.mysite.com/en and is assigned with id=1
2) UserB is registered on www.mysite.com/it and is assigned with  id=1 (note id is the same as for UserA on different installation)
3) UserA is registered on www.mysite.com/it and is assigned with id=2 (because id=1 is already assigned to UserB)
4) UserA loggs in EN site
5) UserA is not logged in IT site yet but when UserA types www.mysite.com/it he is displayed as logged in as UserB!!!

http://market.open-classifieds.com/oc-panel/support/ticket/21049

**Comment by neo22s** [comment]
Thats an issue with installations they can not use the same cookie
hash...they need to do clean installs. The users do not share db either.
No? Also we do  not recommend use of folder install they should use sub
domains or different domains.

**Comment by kotsios5** [comment]
I was able to reproduce the issue on local. Clean installations, different database. Another thing that I noticed, when I was logged in both websites, I clicked logout on the website A, I refreshed website B and I was no longer logged in there too.

**Comment by neo22s** [comment]
Aha, that must be because cookies are crossdomain....so we should check if
we can prevent this...

Saludos / Regards, Chema
GarridoDiaz.com
<https://mailtrack.io/trace/link/c4c508c2bca4288f2d7b806ef7be51acc4f8befc?url=http%3A%2F%2Fgarridodiaz.com&signature=95d01f3cfc8f922a>

**Comment by neo22s** [comment]
In the meantime ask customer to install in subfolders much better.

**Comment by neo22s** [comment]
since this wont be until 2.6.0 fixed.

**Comment by neo22s** [comment]
On logout we delete cookies, they better use subdomains I do not see an easy fix for this :S
