### ISSUE TITLE
Image size on bbcode editor on description field

### ISSUE THREAD

**Issue by kotsios5** [open-classifieds/openclassifieds2#1526]
Changing image size on bbcode editor on description field does not affect the image size on the ad page. Even if image is resized on publish new or on edit ad, image is taking its original size after publishing.

Screenshots: http://exite-bd.clarify-it.com/d/3tl9x6

I have reproduced it on local.

**Comment by neo22s** [comment]
Thats not the way to add an image to an AD for taht we have ad images....
