### ISSUE TITLE
Test and prepare for PHP 7

### ISSUE THREAD

**Issue by neo22s** [open-classifieds/openclassifieds2#1537]
See https://github.com/rlerdorf/php7dev

https://github.com/sstalle/php7cc

**Comment by oliverds** [comment]
By using serverpilot for local env it’s quite easy to change PHP version ;)

![8946725](https://cloud.githubusercontent.com/assets/7003648/10527832/f7d959c4-7392-11e5-8665-26afa30ac13f.png)

**Comment by neo22s** [comment]
yup looooot easier! I will test then in PRE :D

**Comment by neo22s** [comment]
http://discourse.kohanaframework.org/t/php-7-will-it-work-with-kohana/817

Testing at php7.yclas.tk
- installation perfect
- Login perfect
- home page


Errors:
ErrorException [ Notice ]: Array to string conversion
APPPATH/common/modules/pagination/classes/kohana/pagination.php [ 121 ]
116 
117 		// Initialize the $config array
118 		$config['group'] = (string) $group;
119 
120 		// Recursively load requested config groups
121 		while (isset($config['group']) AND isset($config_file->$config['group']))
122 		{
123 			// Temporarily store config group name
124 			$group = $config['group'];
125 			unset($config['group']);

**Comment by neo22s** [comment]
see https://github.com/kohana/core/pull/635

**Comment by neo22s** [comment]
http://php7.yclas.tk/oc-panel/settings/general edited exception.php and modules pagination

**Comment by neo22s** [comment]
been testing further and seems all ok I will wait for an answer on the forum of KO.

**Comment by oliverds** [comment]
**PHP7RC5**

>**ErrorException [ Notice ]: Array to string conversion**
>**APPPATH/classes/model/ad.php [ 888 ]**

![2015-10-23 12-55-21](https://cloud.githubusercontent.com/assets/7003648/10690909/5c90e4de-7985-11e5-8e5f-273d3f7c89b8.png)

***http://reoc.lo/cars/ad.html***

**Comment by neo22s** [comment]
ups! weird.

**Comment by neo22s** [comment]
Review PHP RFC: Uniform Variable Syntax. I am sure we have many places code that we use naming variables coming from a variable. like https://github.com/open-classifieds/openclassifieds2/commit/36e29e462014dea860fbb8a46de55e8a4a7a428e#commitcomment-14397636

**Comment by neo22s** [comment]
ok, php 5.x cant use {} so we need to use intermediate variables for resolving the name :(.

I am trying to find places where we have this.

**Comment by neo22s** [comment]
APCU not working on PHP7 on server pilot at least. 

```
sudo pecl7.0-sp install channel://pecl.php.net/apcu-4.0.7
sudo bash -c "echo extension=apcu.so > /etc/php7.0-sp/conf.d/apcu.ini"
sudo service php7.0-fpm-sp restart
```

We get error:
```
compilation terminated.
make: *** [apc.lo] Error 1
ERROR: `make' failed
```

**Comment by neo22s** [comment]
https://github.com/sstalle/php7cc
