### ISSUE TITLE
Chart.js instead of Google Charts?

### ISSUE THREAD

**Issue by oliverds** [open-classifieds/openclassifieds2#1541]
Charts and graphs using Chart.js, a clean and responsive canvas-based chart rendering JavaScript library.

Also eShop.

**Comment by neo22s** [comment]
Cool! maybe we can create or exists something like https://github.com/open-classifieds/common/blob/master/classes/chart.php

So its easy to use from PHP?

**Comment by neo22s** [comment]
take a look to 
- https://morrisjs.github.io/morris.js/
- http://gionkunz.github.io/chartist-js/
- http://n3-charts.github.io/line-chart/#/examples

**Comment by oliverds** [comment]
* morris.js, no responsive feature.
* n3-charts, for AngularJS applications.
* chartist.js, responsive with media queries while Chart.js is fully responsive based on the viewport width.

Chart.js seems a better solution for now.
