### ISSUE TITLE
Message box on license activation

### ISSUE THREAD

**Issue by kotsios5** [open-classifieds/openclassifieds2#1542]
More clear message on license activation

**Comment by oliverds** [comment]
Do you mean to change message "License will be activated in %s domain" to another?

**Comment by oliverds** [comment]
Print "can not be changed" text.

**Comment by oliverds** [comment]
Ok this was already done. https://github.com/open-classifieds/common/commit/c6fe018af0dafd2aa6eaaa180caca173b5d53cc3 **Once activated, your license cannot be changed to another domain.**
