### ISSUE TITLE
Reorganize admin panel

### ISSUE THREAD

**Issue by oliverds** [open-classifieds/openclassifieds2#1544]
Reorganize items in menus, settings etc..to make it more clear and easier to browse.

Also:
I think our Admin Panel looks kinda outdated now and not very friendly to use.

**UI Inspiration**

* http://sharpen.tomaj.sk/v1.3/html5/dashboard.html

* http://themes.getbootstrap.com/products/dashboard

* https://demo.cachethq.io/dashboard

 Username: test@test.com
 Password: test123

**Comment by neo22s** [comment]
ok! lets discuss it and brianstorm next days ;)

**Comment by ThomWensink** [comment]
Starting on this now. Hope to have it finished by the end of the week

**Comment by neo22s** [comment]
Lets do a blog post about the process.

![20151211023152 1](https://cloud.githubusercontent.com/assets/241725/11741789/700e9ed8-9ffb-11e5-84d4-681163d7c033.jpg)
![20151211023152](https://cloud.githubusercontent.com/assets/241725/11741790/71e47408-9ffb-11e5-8665-6446fe9c2067.jpg)

**Comment by neo22s** [comment]
@oliverds and @ThomWensink working on this.

**Comment by oliverds** [comment]
It seems we will be working this on https://github.com/oliverds/openclassifieds2/tree/feature/panel_rearrangement before merging into open-classifieds/openclassifieds2

I will keep that branch updated with open-classifieds/openclassifieds2 master branch

**Comment by neo22s** [comment]
sounds good! maybe give repo access to thom?

**Comment by ThomWensink** [comment]
@oliverds Can i pull everything we have from here?

**Comment by neo22s** [comment]
Wooow looking great!! LOVE ITTTTT

Some feedback:

1. Would be nice if the sidebar menu when we scroll stays there
2. In settings the font is difficult to read, maybe a stronger color?  
3. Save button, could it be a floating element? so you don need to scroll all the way down to click it? 
4. If I click in the breadcrumb configuration opens inside itself: 
![image](https://cloud.githubusercontent.com/assets/241725/13107190/b4eaef2e-d56c-11e5-90c2-427f824e3bb6.png)


![image](https://cloud.githubusercontent.com/assets/241725/13107143/81db34f4-d56c-11e5-8850-02d97324f987.png)

**Comment by oliverds** [comment]
1. Agree would be nice.
2. Yep text colours are still under review.
3. Maybe with tabs for each section would be better to reduce scroll. I'm still reviewing it.
4. Ohh we have this bug also on our current panel.

**Comment by neo22s** [comment]
4. ups hehehe then fix it plese xD

**Comment by oliverds** [comment]
Almost ready.

@ThomWensink will be doing a last test/review and after that, I will prepare the PR.

**Working branch:** https://github.com/oliverds/openclassifieds2/tree/feature/panel_rearrangement

**A few screenshots:**

<img width="1480" alt="screen shot 2016-04-04 at 9 00 32 pm" src="https://cloud.githubusercontent.com/assets/7003648/14269484/c3fd2b9a-faaa-11e5-97b6-3f4207d863a8.png">

<img width="1481" alt="screen shot 2016-04-04 at 9 00 48 pm" src="https://cloud.githubusercontent.com/assets/7003648/14269489/cd37ade8-faaa-11e5-850a-2df2cd2189c3.png">

<img width="1482" alt="screen shot 2016-04-04 at 9 01 29 pm" src="https://cloud.githubusercontent.com/assets/7003648/14269492/d4f7dff8-faaa-11e5-93da-d9c220f8ad77.png">

<img width="1480" alt="screen shot 2016-04-04 at 9 15 55 pm" src="https://cloud.githubusercontent.com/assets/7003648/14269494/da7de35a-faaa-11e5-988e-a195e8d68cb0.png">

**Comment by neo22s** [comment]
this is looking f**** awesome

**Comment by neo22s** [comment]
awesome job guys!

I've been reviewing:

the help modal does not open
maybe the back color the grey should be a bit harder, depends the screen its confusing with the white.
the alerts look weird 
![image](https://cloud.githubusercontent.com/assets/241725/14381847/ae077908-fd89-11e5-8c5d-88dcdeae5170.png)
we should review the alerts for example http://reoc.lo/oc-panel/pool theres not any and just deletes the user

So far this is what I have found ;)

**Comment by neo22s** [comment]
Interactive map 
![image](https://cloud.githubusercontent.com/assets/241725/14383603/7e914462-fd96-11e5-937e-5846ac16337f.png)

selecting regions the select looks bad.

**Comment by oliverds** [comment]
> The help modal does not open

Not sure yet why sometimes it works and sometimes it doesn't.

> maybe the back color the grey should be a bit harder, depends the screen its confusing with the white.

The back color?

> the alerts look weird

Need to find what's wrong because mine looks fine

<img width="811" alt="screen shot 2016-04-08 at 1 06 24 pm" src="https://cloud.githubusercontent.com/assets/7003648/14393119/bd52cd4e-fd8a-11e5-9a61-13f4f89f10d6.png">

> we should review the alerts for example http://reoc.lo/oc-panel/pool theres not any and just deletes the user

Could be but at http://reoc.lo/oc-panel/pool it doesn't deletes the user, it just removes it from spam users.

> Interactive map  "selecting regions the select looks bad."

I think Thom already fixed it.

**Comment by neo22s** [comment]
background color I meant xD its like light grey.

in that page should ask confirmation before deleting the user from the black list ;)

the rest looks awesome!!

**Comment by oliverds** [comment]
> background color I meant xD its like light grey.

Ahhh. As you said it depends on user's screen. I was playing a lot with that and harder color looks distracting to me. I think it should be a very subtle difference.

> in that page should ask confirmation before deleting the user from the black list ;)

Easy. No problem.

**Comment by oliverds** [comment]
Closing this issue and creating a new one with admin panel bugs https://github.com/open-classifieds/openclassifieds2/issues/1826.
