### ISSUE TITLE
%n does not display any symbol currency

### ISSUE THREAD

**Issue by neo22s** [open-classifieds/openclassifieds2#1548]
If you put USD works :S

**Comment by neo22s** [comment]
seems issue with 2.6.0 version on 2.5.1 its working.

**Comment by oliverds** [comment]
Is not that normal? I mean I never had currency symbol printed with just `%n` value.

**Comment by neo22s** [comment]
You should get the one of your locale. So if you are using en_US should be $ if you use es_ES € if you use de_DE € etc... damn

**Comment by neo22s** [comment]
ok, an issue on yclas only
