### ISSUE TITLE
auto location creator only imports alphabetically sometimes 

### ISSUE THREAD

**Issue by Chinese1904** [open-classifieds/openclassifieds2#1561]
This isn't a dramatic issue, just an enhancement towards perfection. About every other time I try to import cities within their regions, they are not completely sorted alphabetically. Instead of being imported starting with the letter "A", it would start anywhere else, like at "P", for example.

**Comment by neo22s** [comment]
You mean the selects that get auto populated, no?

We can review the code for sure that info comes from http://www.geonames.org/

**Comment by Chinese1904** [comment]
The selects that get auto populated are always right, it is when you try to import those, they are not always sorted correctly in alphabetical order. Look at these screenshots
this is how it is supposed to be populated and imported into the database
http://imgur.com/Kxz4gpl
Now, sometimes I gets sorted like this
http://imgur.com/mUdOVTF

**Comment by neo22s** [comment]
Thanks we will fix it ;)

**Comment by Chinese1904** [comment]
Awesome, thanks. Once I get a little more familiar, I hope to contribute more as well. 
Quick question, are you planning on adding a feature that lets you add all import all states, regions, cities at the same time with their order? Would be useful for customers that try to have classifieds sites for countries
