### ISSUE TITLE
auto location items max-height and overflow

### ISSUE THREAD

**Issue by Chinese1904** [open-classifieds/openclassifieds2#1563]
This is how the style looks right now:

![Image of Error]
(http://i.imgur.com/tzVSMEa.png)

I would recommend adding a max-height: 300px; and overflow: scroll; to the list-group style, so it looks a little more compact and clear, instead having all the items break the page.
Look at the enhancements:

![Image of Fix]
(http://i.imgur.com/tjllnpu.png)

What do you think?

**Comment by neo22s** [comment]
@oliverds check if this is ok ;)

**Comment by oliverds** [comment]
Ok so now height of the modal is 80% of the viewport with overflow. This way modal height is adapted for mobile devices too.

**Comment by neo22s** [comment]
@oliverds cool!!
