### ISSUE TITLE
minimal list view

### ISSUE THREAD

**Issue by Chinese1904** [open-classifieds/openclassifieds2#1571]
Within the last few weeks I added a minimal list view which I oftentimes prefer over any other view when I know what I am looking for, because it is a lot more compact.
Look at my example:
http://classilist.org/electronics
What do you think?

**Comment by neo22s** [comment]
Error 404 - Not Found

This is something related to theme probably, no?

**Comment by Chinese1904** [comment]
I am changing to inmotion and the server they provided does not let me upload any files. I'll comment on here when it's online again. So annoying ...

**Comment by neo22s** [comment]
you can not upload files??? thats super strange :O 

ok sure dont worry ;) thanks!

**Comment by Chinese1904** [comment]
Gees, that was horrible to figure out and to finally migrate. But take a look now, I added the list view and enhanced the "Publish new advertisement" div container, so that the category icon is pulled to the right.

**Comment by neo22s** [comment]
Now I get what you mean! but to put this int he default theme?

**Comment by Chinese1904** [comment]
I feel like it would be nice add on for paying customers, but I don't know how many customers you have using premium themes and the standard theme. Either way, I think it is a nice little list view, which makes it easier for craigslist visitors to get used to your site

**Comment by neo22s** [comment]
yeah could work on some themes, like newspaper or similar. @oliverds can you take a look? maybe a theme option?

**Comment by oliverds** [comment]
Created an issue on BitBucket given that "minimal list" will be for premium themes.

**Comment by neo22s** [comment]
cool!
