### ISSUE TITLE
uploaded images size 1200! bigger than the orginal 200

### ISSUE THREAD

**Issue by abselt** [open-classifieds/openclassifieds2#1572]
Images saved in more big size than the orginal thats bad for slow internet and hosting packages how i can change that correctly, feel free to talk in codes, thanks in advance :)

**Comment by neo22s** [comment]
Hello,

This is for development only, for any questions please use our forum http://forums.open-classifieds.com/

Also follow our rules, https://github.com/open-classifieds/openclassifieds2/blob/master/CONTRIBUTING.md#reporting-issues

thanks!
