### ISSUE TITLE
Rental

### ISSUE THREAD

**Issue by kotsios5** [open-classifieds/openclassifieds2#1573]
Enter a daily/weekly/monthly rate and then be able to select dates on a calendar and it will tell you the rate.

http://market.open-classifieds.com/oc-panel/support/ticket/21709

**Comment by neo22s** [comment]
duplicated https://github.com/open-classifieds/openclassifieds2/issues/1550

We will see if we can develop this. He can sponsor the development if he is interested ;)

**Comment by neo22s** [comment]
Also for his case he can use custom fields weekly price monthly etc..
