### ISSUE TITLE
update ad with no stock entered

### ISSUE THREAD

**Issue by Chinese1904** [open-classifieds/openclassifieds2#1575]
there is a warning coming up, when you try to update an ad and leave the stock field blank.
![Error]
(http://i.imgur.com/oFnPzkG.png)
If this is intended behavior, then that is fine, but it should be pretty simple to fix with isset()

**Comment by neo22s** [comment]
No its not :S and the ad will not get updated I think.

**Comment by neo22s** [comment]
Are you using latest version 2.5.1?

I can not reproduce the error. Did you publish the ad without stock? meaning stock= '' empty?

Or you put a number?

**Comment by neo22s** [comment]
I can not reproduce it but I have added some controls so this doesnt happen, mostly verify its a number ;)
