### ISSUE TITLE
Browse Profiles

### ISSUE THREAD

**Issue by neo22s** [open-classifieds/openclassifieds2#1585]
Be able to browse all the profiles/shops of the site.

reoc.lo/users (they can change this in translations)

Review route 'profile' and add the code in controller user.

Also add a search engine, to search in description or in custom fields.

Paginated and display in each user num of ads, reviews etc..

Also allow the home page landing mode to choose the users view.

- [x] view list
- [x] controller index and profile
- [x] route for browsing profiles
- [x] able to choose as landing page
- [x] infinite scroll for users search
- [x] display num of ads next to each profile
- [x] profile display ads but paginated
- [x] header menu item profiles
- [x] widget search in profile
- [ ] fix styles for pages/user/list.php on splash, jobdrop, newspaper, mobile

**Comment by neo22s** [comment]
not closed xD we need to review styles for themes  @oliverds fix styles for pages/user/list.php on splash, jobdrop, newspaper, mobile

also if you want you can take a look to the end result and improve maybe the look and feel.

thanks

**Comment by neo22s** [comment]
once is done we need to move all to yclas. What do you prefer I move all the work done until now? or you do it once all is finished?

**Comment by oliverds** [comment]
Ok. I will review it and when it's done I will move all to yclas.

**Comment by neo22s** [comment]
I can partially move all that is not views related if you want. no issue at all ;)
