### ISSUE TITLE
Use different currency for ads and features

### ISSUE THREAD

**Issue by kotsios5** [open-classifieds/openclassifieds2#1586]
If someone wants to use different currency for ads (price field) and featured or bring on top, it's possible but it's confusing users.
For example, dollar is set as currency format but euro as payment method on Settings -> Payment:

![currency](https://cloud.githubusercontent.com/assets/11571490/11187436/4ec8adbc-8c7e-11e5-852d-1e9b13ff606b.png)
![currency1](https://cloud.githubusercontent.com/assets/11571490/11187451/5a36c238-8c7e-11e5-9dfc-93b27dfeddf1.png)
![currency2](https://cloud.githubusercontent.com/assets/11571490/11187455/5c46d720-8c7e-11e5-83f5-f5a1c6a001f9.png)

It would be better if featured ad and bring on top currency is euro as it was set on Settings -> Payment

**Comment by neo22s** [comment]
Yeah I am aware...problem is that some currencies are not supported on paypal thats why we allow 2 currencies, 1 for the payments which needs to be a valid one for paypal and another for the site. Which can be something like %n. Maybe we should explain it better.

**Comment by neo22s** [comment]
lets improve the docs then for this issue and thats all ;)
