### ISSUE TITLE
moderator being able to edit/delete/spam/deactivate

### ISSUE THREAD

**Issue by Chinese1904** [open-classifieds/openclassifieds2#1588]
In my opinion moderators should also be allowed to edit/delete/spam/deactivate ads from the listings page, whereas right now only admins can do it. I didn't check if it works on default theme

**Comment by neo22s** [comment]
I think they can edit, I need to review this actually.

**Comment by neo22s** [comment]
Yes he can edit ads https://github.com/open-classifieds/openclassifieds2/blob/master/oc/classes/controller/panel/myads.php#L241

and he can delete/spam/deactivate
https://github.com/open-classifieds/openclassifieds2/blob/master/install/samples/install.sql.php#L488

**Comment by Chinese1904** [comment]
Isn't this where moderators are supposed to be able to have those functions?
https://github.com/open-classifieds/openclassifieds2/blob/master/themes/default/views/pages/ad/listing.php#L129

**Comment by neo22s** [comment]
aaaaaaaaaa there you meant!

I was checking in the moderation panel. Well thats another tool yeah we can make it that appears to the moderators too quite simple ;)
