### ISSUE TITLE
Currency converter

### ISSUE THREAD

**Issue by neo22s** [open-classifieds/openclassifieds2#1599]
Ideas:

## 1 - jquery convert from exchange rate
Just a simple config, comma separated currencies and we display int he single.php a button to change currency.

http://curry.netyou.co.il/demo/

They can also select a global currency in the header.

http://www.sitepoint.com/10-jquery-currencyprice-plugins/

## 2 - using custom fields
Use a special type of custom field called currency. And then behaves same as described with jquery plugin but instead of using the exchange rate uses the prices provided by the user in the new.php

**Comment by neo22s** [comment]
We will use the jquery convert plugin.

**Comment by neo22s** [comment]
looks good!

Feedback:

- add a new widget field of comma separated currencies, so if they write currencies there only those will be displayed in the drop down, if none written display all. take a look to languages ;)
- 
![image](https://cloud.githubusercontent.com/assets/241725/15386049/e6a3e6ca-1da5-11e6-8e59-64947be7f190.png)

make it look the same? the select I mean ;)

**Comment by kotsios5** [comment]
This is not closed yet. There's a bug I cannot fix.

If the widget is created, but I am on a page that doesn't have widgets (like new.php or edit ad page), there is a js error which blocks the creation of the dropdown menus for categories and locations.

This is the error: TypeError: $(...).curry(...) is undefined
and I am getting it because the widget is not displayed.

**Comment by neo22s** [comment]
aha! well.... mmmm only load those JS if the widget is loaded?

**Comment by oliverds** [comment]
Also at line https://github.com/open-classifieds/openclassifieds2/blob/master/themes/default/js/theme.init.js#L93 we could have a conditional `if ($('.curry').length)` to make sure an element with class `curry` exist.

**Comment by oliverds** [comment]
Also, I see all `widget_currency.php` views are the same so we should have it only on the default theme.

**Comment by oliverds** [comment]
Issue reopened, I think @kotsios5 want to add symbols, currencies.
