### ISSUE TITLE
Fatal Error after attempting to Mark as paid

### ISSUE THREAD

**Issue by Alvarofg** [open-classifieds/openclassifieds2#1602]
I have an existing ad I wanted to bring to the top (as an admin). I clicked $Mark as Paid (from checkout) and got the following error message:

Fatal error: Can't use function return value in write context in .{localpath}/oc/classes/controller/panel/order.php on line 55

I've tried different ads, all with the same result

I'm running 2.5.1

**Comment by neo22s** [comment]
You need PHP 5.5 at least ;) then the error will be gone.

**Comment by Alvarofg** [comment]
Confirmed fix

**Comment by neo22s** [comment]
please use our forum if you need anything else thanks ;)

http://forums.open-classifieds.com/
