### ISSUE TITLE
pay to post category does not ask for payment

### ISSUE THREAD

**Issue by Chinese1904** [open-classifieds/openclassifieds2#1604]
I changed the setting of a category and set the price to 5.00 (USD).  Now, when I try to post within that category, it is not asking for any payment.

**Comment by neo22s** [comment]
Please we need a lot more info about this. It's working on our end, please read the docs where explains how to properly configure it. Probably you are missing the option in general settings->pay to post.

Github is not to get support, better use the forum please.
