### ISSUE TITLE
Load categories/locations - faster

### ISSUE THREAD

**Issue by neo22s** [open-classifieds/openclassifieds2#1606]
We have a problem in HTML when customers put thousands of categories...this needs to be printed in the HTML and makes the browser unresponsive.

Some solutions:
- retrieve categories on demand using the API
- in home page only display 1st level and 2nd level if its configured this way.
- Search engine categories using api too

Any other suggestion appreciated.

PHP Slow request
```
[0x0000732bcce477a0] find_all() /var/www/oc/classes/model/location.php:424
[0x0000732bcce47640] get_siblings_ids() /var/www/oc/classes/model/location.php:431
[0x0000732bcce474e0] get_siblings_ids() /var/www/oc/classes/model/location.php:431
[0x0000732bcce47310] get_siblings_ids() /var/www/oc/classes/controller/ad.php:154
[0x0000732bcce47100] list_logic() /var/www/oc/classes/controller/ad.php:126
```

**Comment by neo22s** [comment]
Related: https://github.com/open-classifieds/openclassifieds2/issues/1697

**Comment by neo22s** [comment]
Breaking my brain here :s

I am working on a 2 level get_location_count / get_category_count and improving the functions that we used to count this.

for model_location review to remove functions:
- get_by_deep , only used on get_all
- get_alll, only used on theme gummy and yummo, check to replace with other functions
- get_location, never used

for model_category review to remove functions:
- get_by_deep , only used on get_all
- get_alll, only used on theme gummy and yummo, check to replace with other functions

**Comment by neo22s** [comment]
Each point different way of calculating. 
1- Transactions:		         98 hits --> original
2- Transactions:		         148 hits --> only level 0,1 filtered
3- Transactions:		         197 hits --> saving all cats as array
4- Transactions:		         234 hits --> removing cats as array introduced function has_sibling.

Me head will explode. xD

@oliverds I will assign to you this since we need to see what we do at gummy and yummo. We need to get rid off the ::get_all and replace it with other function I guess. I have marked them as deprecated so in a future we see it we will delete them.

**Comment by oliverds** [comment]
Ok. Model_Category::get_all() is also used on a couple of yclas custom themes.

**Comment by neo22s** [comment]
@oliverds I think can be changed, no? its awful shit of bad code xD mostly done by me...

**Comment by oliverds** [comment]
I think so, what is needed is a way to return a collection of categories and their child categories. Yeah not pretty but it was working.

**Comment by neo22s** [comment]
hehehe we have the multidimension function.

**Comment by oliverds** [comment]
Can't remember why I ended up using Model_Category::get_all() instead of Model_Category::get_multidimensional()

Need to really review it.

**Comment by oliverds** [comment]
Ok. Removed Model_Category::get_all() and Model_Location::get_all() usage on OC and yclas themes.
