### ISSUE TITLE
Modal docs.yclas.com over HTTPS

### ISSUE THREAD

**Issue by neo22s** [open-classifieds/openclassifieds2#1611]
If customer uses HTTPS he can not open the docs in the modal.

How can we fix this? maybe if site is https open in _target? 

Mixed Content: The page at 'https://classifiedsbarcelona.com/oc-panel/settings/general' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://docs.yclas.com/allowdisallow-bots-crawlers/'. This request has been blocked; the content must be served over HTTPS.

**Comment by oliverds** [comment]
Actually would be nice to have docs.yclas.com over HTTPS too that way even if customer site uses HTTPS we could open the modal.

**Comment by neo22s** [comment]
They do not offer HTTPS on hosted domains only if you use their domain.

I am checking maybe using cloudflare....let me take  alook

**Comment by neo22s** [comment]
Works on cloudflare we are checking if we can fix it on documentation will be better

**Comment by neo22s** [comment]
@kotsios5 we will fix docs.yclas.com so works on https and then replace in OC all the link to https://docs.yclas.com to //docs.yclas.com

we need to do it on yclas too we do it tomorrow I will help you ;)
