### ISSUE TITLE
Update Cookie Consent CDN

### ISSUE THREAD

**Issue by oliverds** [open-classifieds/openclassifieds2#1612]
**Important update to users of Cookie Consent 2.0**

> As of November 23rd 2015, some old versions of Cookie Consent will stop working. You must make a small change to your code to keep using Cookie Consent.

https://silktide.com/really-important-update-to-users-of-cookie-consent-2/

**Comment by oliverds** [comment]
Sorry this is only for yclas.

**Comment by neo22s** [comment]
damn, happens at oc.com and oe.com already fixed it there.
