### ISSUE TITLE
Spam on forums.open-classifieds.com/oc-panel/ad/moderate

### ISSUE THREAD

**Issue by kotsios5** [open-classifieds/openclassifieds2#1615]
Spam button on forums.open-classifieds.com/oc-panel/ad/moderate is not working. I had to select the topic (check box) and click spam button for selected topics and it worked

**Comment by neo22s** [comment]
ok, found the error

Failed to load resource: the server responded with a status of 404 (Not Found)
http://cdn.jsdelivr.net/sweetalert/1.1.3/sweet-alert.min.js Failed to load resource: the server responded with a status of 404 (Not Found)
5moderation.js:116 Uncaught ReferenceError: swal is not defined
http://cdn.jsdelivr.net/sweetalert/1.1.3/sweet-alert.min.css Failed to load resource: the server responded with a status of 404 (Not Found)
6moderation.js:116 Uncaught ReferenceError: swal is not defined(anonymous function) @ moderation.js:116x.event.dispatch @ jquery-1.10.2.min.js:5v.handle @ jquery-1.10.2.min.js:5

**Comment by oliverds** [comment]
Damn this is my bad. Fixing it. On v1.1.3 they changed filename to sweetalert.min.js and sweetalert.min.css
