### ISSUE TITLE
adblock detection issues

### ISSUE THREAD

**Issue by Chinese1904** [open-classifieds/openclassifieds2#1621]
When I turn on the plugin Adblock Detection, then the ads in listings page are not properly displayed anymore. Look at this issue [right here](http://classilist.org/electronics). Note that I have some featured ads active on that page as well. And as you can see, those are blocked, due to the .featured-**ads** class. IMO those shouldn't be blocked, even with the Adblock message being displayed

**Comment by neo22s** [comment]
Can you put some screenshots please? or video recording?

The adblock detector only displays a warning doesnt disable adblock.

**Comment by Chinese1904** [comment]
This is how it looks on any browser when I have Adblock turned off. And thats how it is supposed to look 
[error 1](http://i.imgur.com/KeikkS9.png)
Now, when I have Adblock turned on it leaves the ads blank that have the div class .featured-ads, because of the "ads" in the class.
[error 2](http://i.imgur.com/KjiWazK.png)
Here is an error with mod_pagespeed when I have adblock turned on as well.
[error 3](http://i.imgur.com/MSznO9G.png)

**Comment by neo22s** [comment]
mmmm seems an issue with modpagespeed. based on the error, but when you mean adblock plugin you mean the plugin on open classifieds panel, no? not the browser plugin. just to be sure we are in the same page.

**Comment by Chinese1904** [comment]
I always have the plugin enabled in OC. When I activate the browser add-on Adblock Plus, thats when the mod_pagespeed error comes up and thats when it looks like in the second image. You see how it leaves the featured ads space blank?

**Comment by neo22s** [comment]
but this is an issue on the adblock plugin on your browser not in our software, no? I mean why is our fault :S ?

Open this issue in their support system or similar since its not working properly, I am so tired of reporting and they never had answer. Horrible plugin so many issues.

**Comment by Chinese1904** [comment]
I am pretty sure if the class was called just .featured or .featured-block or whatever, it would work. I can try to make it work and report tomorrow, but I know that that's the issue. If you modify the that element and get rid of that class, it shows up again

**Comment by Chinese1904** [comment]
Clearly not your fault though haha

**Comment by neo22s** [comment]
yeah I know but we've been doing this hacks for so long now I am soooo
tired of adblock :(

Saludos / Regards, Chema
GarridoDiaz.com
<https://mailtrack.io/trace/link/26d3035c42e37f84869900a95102685508867b80?url=http%3A%2F%2Fgarridodiaz.com&signature=82d69c8005e23b60>

**Comment by Chinese1904** [comment]
I just wish every website wouldn't abuse ads, so there would be no use for adblockers in the first place...
Anyhow, I just realized that these pagespeed errors only come up, when the oc adblock plugin is turned on and there there is even error for the oc adblock plugin thats related to pagespeed. 

![error](http://i.imgur.com/oGnAQFf.png)

**Comment by neo22s** [comment]
If i see a site filled with ads normally i leavr i am.sure not serious ;)

**Comment by emanwebdev** [comment]
@Chinese1904  hi , do you mean AdBlock raises JS errors in the OC2 javascript sections?

**Comment by Chinese1904** [comment]
Yes. It's on the listings page and only when the Adblock oc2 plugin is enabled

**Comment by neo22s** [comment]
This was fixed as far as I know. Can you confirm?
