### ISSUE TITLE
User custom fields on publish new

### ISSUE THREAD

**Issue by kotsios5** [open-classifieds/openclassifieds2#1622]
Maybe it would be better to display required user custom fields on publish new, when publisher is unregister (and account will be created)

**Comment by neo22s** [comment]
Its not like this already?

**Comment by kotsios5** [comment]
No.

![usercf](https://cloud.githubusercontent.com/assets/11571490/11587838/58580810-9a74-11e5-9db1-c2a094180935.png)
![usercf1](https://cloud.githubusercontent.com/assets/11571490/11587839/585b6294-9a74-11e5-9a29-d1a257c580d1.png)

**Comment by neo22s** [comment]
ok, we will review this, thanks ;)

**Comment by oliverds** [comment]
We can close this issue.

User CF are only for premium themes. Commits already on Github private repos.
