### ISSUE TITLE
Location is selected on single ad page

### ISSUE THREAD

**Issue by kotsios5** [open-classifieds/openclassifieds2#1623]
For example I am on an ad single page and click to browse a different category, the results are displayed according to the ad I previously selected.

**Comment by neo22s** [comment]
is not correct? we filter by location. or this causes confusion?

**Comment by kotsios5** [comment]
I like it, I think it's useful! Users can browse categories without selecting their location every time. But maybe it's confusing some others:

http://market.open-classifieds.com/oc-panel/support/ticket/22215

**Comment by neo22s** [comment]
I like it more too ;)

We can modify his theme for him, he can contact us to give him a budget. no possible to modify it in settings.
