### ISSUE TITLE
" in title breaks the title-tag

### ISSUE THREAD

**Issue by Chinese1904** [open-classifieds/openclassifieds2#1625]
For instance, the customer posts an ad with the title "42" TV for sale", then the title of the link is going to be broken. It happens in the listings page.
![error](http://i.imgur.com/22hzA7r.png)

**Comment by neo22s** [comment]
We need to run htmlentities never thought about it.

Maybe is better to create a function called get_title() so we do not repeat same code too many times?

**Comment by oliverds** [comment]
It seems `HTML::chars()` is missing on some views.

Not sure if create `get_title()` is really necessary, we have been using `HTML::chars($ad->title)` within HTML attributes.

**Comment by neo22s** [comment]
ok, then ;)
