### ISSUE TITLE
Select how many ads to display per page

### ISSUE THREAD

**Issue by kotsios5** [open-classifieds/openclassifieds2#1628]
I would recommend having the option for the customer to choose how many ads he would like have displayed. So, that on the bottom or top of the listings page you would have the option to choose from "Show 10, 15, 20, 50, 100" ads. I would maybe think about setting the minimum of displayed ads to be 15, because that way the grid list view (3 ads a column) would be filled up nicely.

https://forums.open-classifieds.com/support/option-to-choose-how-many-ads-to-be-listed.html

**Comment by neo22s** [comment]
This works with the pagination

https://github.com/open-classifieds/openclassifieds2/blob/master/oc/classes/controller/ad.php#L226

Adding something like:
```
'items_per_page' 	=> core::request('items_per_page',core::config('advertisement.advertisements_per_page')),
```

will accept on the url or via post ?items_per_page=20 and then display 20 items.

What we should do in the view is to add a select (button dropdown better) to select the amount of items. http://getbootstrap.com/components/#btn-dropdowns this needs to be donw in all the themes.

This could be even a feature for the pagination.php view, where the select appears next to the pagenumbers? 

This way we will have it anywhere where pagination exists.

**Comment by neo22s** [comment]
See comments here https://github.com/open-classifieds/openclassifieds2/pull/1706
