### ISSUE TITLE
Review yahoo login

### ISSUE THREAD

**Issue by kotsios5** [open-classifieds/openclassifieds2#1632]
Maybe we need to review yahoo login. It always returns this error:

Error: please try again! Undefined index: key

**Comment by neo22s** [comment]
I will review but should work fine.

**Comment by neo22s** [comment]
damn took me a lot of time :s

Lets update the docs, its working good but you need to give API permissions of contact:


Lets update http://docs.yclas.com/how-to-login-using-social-auth-facebook-google-twitter/

Add Yahoo:
Go to https://developer.apps.yahoo.com/dashboard/createKey.html and create a new application.
Fill out any required fields such as the application name and description.
Put your website domain in the Application URL and Application Domain fields.
Set the Kind of Application to Web-based
Choose Contacts API
![image](https://cloud.githubusercontent.com/assets/241725/11690696/367e0dca-9e98-11e5-895c-9bd351672cb8.png)
Go to http://yourdomain.com/oc-panel/social/index
9. Set Yahoo = TRUE
10. Fill ID = Client ID as appears at Yahoo
11. Fill Secret = Client secret as in Yahoo
12. Click Update in the bottom of the page
13. Logout
14. Go to login, Yahoo should appear there
15. Test!

**Comment by kotsios5** [comment]
https://github.com/open-classifieds/documentation/pull/121
