### ISSUE TITLE
Forum - reply button

### ISSUE THREAD

**Issue by kotsios5** [open-classifieds/openclassifieds2#1648]
Unregistered users can see the 'reply' button on a topic page as well as the 'login to reply' button but when reply button is clicked it does nothing, as user need to login to reply.

![forum-reply](https://cloud.githubusercontent.com/assets/11571490/11807294/d3d743ee-a310-11e5-88d2-74889c63aaaa.png)

**Comment by neo22s** [comment]
should open the login modal ;)
