### ISSUE TITLE
Values sent to 2checkout

### ISSUE THREAD

**Issue by kotsios5** [open-classifieds/openclassifieds2#1653]
Maybe we need to review the values are sent to 2checkout. If the price passed with a comma, it will cause error.

https://market.open-classifieds.com/oc-panel/support/ticket/22472

**Comment by neo22s** [comment]
so we can use '.'¿ dot?

**Comment by neo22s** [comment]
does it work did you test it?

**Comment by kotsios5** [comment]
not yet. they replied to a user that this is the issue. Also I can see error code on their knowledge database
http://help.2checkout.com/articles/Knowledge_Article/Error-Code-PE103/?l=en_US&fs=RelatedArticle

**Comment by neo22s** [comment]
thats cause of his locale that uses , instead of . but we can force that should not be an issue.

**Comment by kotsios5** [comment]
maybe it would be better to force that, it would prevent this issue for locales that uses ,

**Comment by neo22s** [comment]
sure! ;)

**Comment by neo22s** [comment]
fixed ;)
