### ISSUE TITLE
SVG to allowed image formats

### ISSUE THREAD

**Issue by kotsios5** [open-classifieds/openclassifieds2#1655]
Add svg option to allowed image formats. This will also allow website owner to upload an svg file as their website logo.

**Comment by neo22s** [comment]
SVG is not indicated as a logo image or similar I think...

**Comment by kotsios5** [comment]
I thought that too, but I can see some posts recommend using svg files for logo. Anyway, it's not necessary to change it, only a guy asked for that, we can see if more people need it.

**Comment by neo22s** [comment]
I think is pretty easy actually

**Comment by oliverds** [comment]
Mmmm but .svg are vector files not images so I don't think we can resize/crop/validate nudity etc. for those files.

.svg can be added to allowed extensions but any image process will be skipped.

**Comment by neo22s** [comment]
then no! xD I will discard this. thanks oliver!
