### ISSUE TITLE
pagination display on mobile devices 

### ISSUE THREAD

**Issue by Chinese1904** [open-classifieds/openclassifieds2#1659]
As you can see in the screenshot, in case there are a lot of pages, it would be easier to have the pagination a little more simple and easy. For instance, I don't think the last pages have to be displayed? A simple next and previous page, would be enough a lot of times in my opinion.

![display](http://i.imgur.com/pRc1SZH.png)

**Comment by neo22s** [comment]
I think in mobile (responsive version) is when this should happen only.
