### ISSUE TITLE
Spam ads - blacklist

### ISSUE THREAD

**Issue by kotsios5** [open-classifieds/openclassifieds2#1660]
User is not appeared in blacklist if any of their ads marked as spam. However, user is added to the blacklist if he is marked as spammer from Users -> Users.

**Comment by neo22s** [comment]
So if I mark and ad as spam he doesnt go to the spam list ?

**Comment by kotsios5** [comment]
The ad goes to the spam list, user is not added to Users -> Blacklist

**Comment by neo22s** [comment]
ok, I tihnk I know why, is the admin or moderator the user? then doesnt got to spam the user ;) if not he wont be able to login heheh

**Comment by kotsios5** [comment]
Yes, you are right, you can close this issue

**Comment by neo22s** [comment]
Well no I will improve the system too, some small fixes XD
