### ISSUE TITLE
Imported ads on stats

### ISSUE THREAD

**Issue by kotsios5** [open-classifieds/openclassifieds2#1663]
Imported ads are not included on website stats. 

I have 8 ads published, 7 of them are imported from tools -> import.
On stats, the first box (ADS) displays "1". This was "0" until I published an ad from publish-new.

![stats](https://cloud.githubusercontent.com/assets/11571490/11935243/b901ad50-a7fe-11e5-9d2b-f0e2a6d865f9.png)

**Comment by oliverds** [comment]
I see you have a date filter from 2015-11-21 to 2015-12-21.

The other 7 ads have published date between 2015-11-21 and 2015-12-21?

**Comment by neo22s** [comment]
ahaaaaaa sure is that ;)

**Comment by kotsios5** [comment]
Oliver is right, only that ad was published between 2015-11-21 and 2015-12-21. I changed the date of another ad and it appears on stats, so there is no issue.
