### ISSUE TITLE
list/grid view menu missing white spaces and minimal icon

### ISSUE THREAD

**Issue by Chinese1904** [open-classifieds/openclassifieds2#1668]
As of right now, list, grid, sort views don't have a whitespace after the icon, which makes the icon look too close to the text.

![error1](http://i.imgur.com/Y0x2nId.png)

As you can see the Map view has the whitespace.

Another quick enhancement I would add is that currently the minimal list view and the list view have the same icon. I would change the Minimal list view icon to this
`<span class="glyphicon glyphicon-list"></span> <?=__('Minimal')?>`

**Comment by oliverds** [comment]
This issue can be closed. Only premium themes were amended.
