### ISSUE TITLE
Fb login - yummo theme

### ISSUE THREAD

**Issue by kotsios5** [open-classifieds/openclassifieds2#1671]
When a user logins using his fb account, it redirects to /themes/yummo/#_=_  
Redirect URL and Callback URL does not include this path.
I reproduced this on local.

**Comment by neo22s** [comment]
Can you make a video or screenshots?

thats really weird almost everyone uses FB login :S we actually use it too

**Comment by kotsios5** [comment]
Deauthorize Callback URL: http://reoc.lo/
Valid OAuth redirect URIs: http://reoc.lo/
Yummo theme is activated.
Login using fb account:

![fb-login](https://cloud.githubusercontent.com/assets/11571490/11975289/1b7b10fa-a964-11e5-86f7-402f9c20e3af.png)

**Comment by neo22s** [comment]
but this only happens on the yummo theme?

**Comment by kotsios5** [comment]
yes!

**Comment by neo22s** [comment]
I tihnk there must be a 404 a file missing or similar @oliverds will take a look, must be that ;)

**Comment by oliverds** [comment]
Not sure what could be wrong. I have just tested FB login with yummo theme enabled and it seems everything ok.

> Deauthorize Callback URL: http://reoc.lo/
> Valid OAuth redirect URIs: http://reoc.lo/
> Yummo theme is activated.
> Login using fb account:

Same config.

Do you have the same issue @neo22s?

**Comment by neo22s** [comment]
no didnt get the error have tried 2 times, weird :S

**Comment by kotsios5** [comment]
Latest version of oc, common and themes, i can reproduce this issue now again.

**Comment by neo22s** [comment]
Maybe is some config?

The user already exists in the DB? or its a new user?

**Comment by kotsios5** [comment]
New installation, new user.

**Comment by neo22s** [comment]
at yclas happens the same?

**Comment by kotsios5** [comment]
on yclas.tk it's not happening, it redirects to http://ttest.yclas.tk//#_=_

**Comment by neo22s** [comment]
any customer had complains about this?

I tihnk is some short of redirect on your cache or similar ?

**Comment by kotsios5** [comment]
i just found the ticket, this is his website but i can't reproduce it there anymore: http://www.tokobaris.com/

I deleted cache from the panel, browser cache, cookies, same issue

**Comment by neo22s** [comment]
got the error in his site too.

Redirected to http://www.tokobaris.com/themes/yummo/#_=_ but loged in.

sort.js:54 Uncaught ReferenceError: google is not defined that seems the issue @oliverds

**Comment by oliverds** [comment]
Will take another look.

Let's see if I can reproduce it on my local.

**Comment by oliverds** [comment]
Fixed `sort.js:54 Uncaught ReferenceError: google is not defined` error.

@kotsios5 could you please test it again on your local because I'm still unable to reproduce this issue?

**Comment by kotsios5** [comment]
@oliverds it still happens. I am redirected to http://reoc.lo/themes/yummo/#_=_ but logged in.

**Comment by oliverds** [comment]
This issue can be closed. Finally I was able to reproduce it and fix it (https://github.com/openclassifieds/themes/commit/25c9e16aa1df70f7b65866aa9caa6d3492927cdb).

**Comment by neo22s** [comment]
nice!
