### ISSUE TITLE
auto locate distance improvements 

### ISSUE THREAD

**Issue by Chinese1904** [open-classifieds/openclassifieds2#1673]
A couple of things I noticed is that If I activate the User Location widget to be in the sidebar, the widget does not show up in the sidebar. 

I also would think it would be a really good idea to use the google maps typeahead suggestions!

Last but not least, I think there should be another config value - one for the advertisement location radius.  Right now, there is a config "Auto locate distance" in settings to be changed, but that changes both the "Auto locate distance" and the "Auto locate ad distance". 
Let me try to explain the usage of it as easy as I can:
In general, customers of classifieds site would prefer to have a small radius for the ads filter (Wallapop has a 1 mile radius), but they wouldn’t prefer to have the same small radius for "Auto locate distance", because if the audience is a country, the visitor might want to search for ads in a location 40-50 miles away from his geo location.
It would be really nice if you could actually manually change the home location to any location and don't only have auto_locats as options.

Does that kind of make sense?

**Comment by neo22s** [comment]
we will review thanks

**Comment by neo22s** [comment]
Hello!

reviewing this.

1. "User Location widget to be in the sidebar, the widget does not show up in the sidebar." --> should appear if theres locations let us check

2. I also would think it would be a really good idea to use the google maps typeahead suggestions! -- > do you know where is the API and if its free? looks good idea!

3. "Auto locate distance" and the "Auto locate ad distance".  I do not understand this xD maybe @oliverds  understand it?

**Comment by Chinese1904** [comment]
2. https://developers.google.com/maps/documentation/javascript/places-autocomplete that's what I was talking about.

3. I meant that the same radius is used for results on maps than there is for the "Auto locate distance" radius. On maps you should rather have a radius that changes as you move the map which is generally a small few miles radius.

**Comment by oliverds** [comment]
1. User location widget appears if the user chooses the closest location from the homepage.

2. Typeahead on setting user address. Will take a look.

3. On 2.7.0, users can filter ads also by setting an address and within a specified radius.
![9603513](https://cloud.githubusercontent.com/assets/7003648/13849303/35b160f6-ec1b-11e5-9da0-08211ff26588.png)
![9603515](https://cloud.githubusercontent.com/assets/7003648/13849310/3a755c00-ec1b-11e5-8637-3fde960c66fd.png)
