### ISSUE TITLE
Undefined index: validate_banned_words

### ISSUE THREAD

**Issue by kotsios5** [open-classifieds/openclassifieds2#1677]
Clean installation of 2.6.1 without any premium theme, on http://reoc.lo/oc-panel/settings/form I am getting this error:

![advertisement](https://cloud.githubusercontent.com/assets/11571490/12010288/dfd3bed0-ac97-11e5-8bfa-fb0f58e2330b.png)

**Comment by kotsios5** [comment]
The error solved when I run oc-panel/update/261

**Comment by neo22s** [comment]
@oliverds we do not have this at yclas, no? I can not find it

**Comment by oliverds** [comment]
Sorry about that.

> @oliverds we do not have this at yclas, no? I can not find it

Issue opened at yclas. https://github.com/open-classifieds/openclassifieds2/issues/1400 is missing.
