### ISSUE TITLE
Private site option

### ISSUE THREAD

**Issue by neo22s** [open-classifieds/openclassifieds2#1683]
Similar to maintenance mode.

Only admin can register users.

On the site if this option is enabled only login and forgot password works, in the same view/controller.

**Comment by neo22s** [comment]
@kotsios5 

Let's hope I can explain this a bit better ;)

The idea is to get a site where only registered users can see the information/content of the site.

For that we can display a landing page like the one we use on maintenance (but  able to change the content maybe with a page?).

Site will not allow registering, only login and forgot password. Admin will need to create the accounts.

Maybe add a form that says request access. That will be a contact form with the subject already written like aa@aa.com is requesting access.

Any doubt? let me know if I can help ;)

**Comment by kotsios5** [comment]
I work on this the next days, but thanks for the explanation! I think I understand what needs to be done, I will let you know if I need anything.

**Comment by neo22s** [comment]
@kotsios5 take a look you will like it ;)

**Comment by kotsios5** [comment]
@neo22s sure! Thanks for your help! I will add the option to create a page and then move it to yclas!

**Comment by neo22s** [comment]
ok, maybe put the option and the page selection one next to the other. so its easier to find the settings ;)

The rest works good!
