### ISSUE TITLE
Cursor on description field

### ISSUE THREAD

**Issue by kotsios5** [open-classifieds/openclassifieds2#1685]
"In iPhone I click Publish New, when I click on the Description Box, the cursor is not displayed inside the box.  BBCODE editor is on.  If BBCODE editor is off, then the issue goes away"

I reproduced that issue on iPhone 6 as he said on the ticket. The cursor is not displayed on description field but it's possible to type letters. After typing a letter and delete it, the cursor appears.

https://market.open-classifieds.com/oc-panel/support/ticket/22882

**Comment by neo22s** [comment]
Ufff really complex :S lets see if oliver can fix it. Maybe the BBCODE should not load on mobile devices?

Or he should use the mobile theme or mobile APP....

**Comment by oliverds** [comment]
Not sure why this issue is not present on default, jobdrop, kamaleon, modern deluxe, ocean and responsive themes.
