### ISSUE TITLE
Publish new ad

### ISSUE THREAD

**Issue by kotsios5** [open-classifieds/openclassifieds2#1686]
If the listing doesn't have image, everything works ok.  If there is only one image, I see the warning message on the top "A problem occurred with this webpage so it was reloaded", but the listing is published fine together with the single image. 
But if I try to upload more than one image, then besides the warning message, I also see the pop-up windows saying "Are you sure you want to submit this form again.  Cancel/Submit".  If I click the Submit, the pop-up shows up again.  when I click Cancel button, listing was published except not all the images are uploaded.  One time I try to upload four images, only two were uploaded.  The sizes of the images are only about 100k each.

https://market.open-classifieds.com/oc-panel/support/ticket/22915

I can reproduce this issue on an iPhone5

**Comment by neo22s** [comment]
Which theme? which version of the browser?

**Comment by kotsios5** [comment]
iOS version: 9.2 (13C75)
Theme: reclassifieds3

**Comment by neo22s** [comment]
thanks! ;)

**Comment by hemant-chakka** [comment]
I am facing the same issue - "a problem occured with this web page, so it was reloaded" whenever I try to upload image on iphone, if I don't upload any image, everything is fine I don't get the error.How do I fix this ?

Thanks

**Comment by neo22s** [comment]
please use our forum https://forums.open-classifieds.com/publish-new.html
