### ISSUE TITLE
Keyboard input for dropdown menus on mobile

### ISSUE THREAD

**Issue by kotsios5** [open-classifieds/openclassifieds2#1689]
Maybe it would be easier for users to find their their location or category, for example if there are many locations or categories. On the other hand, if there is the keyboard input AND the dropdown menu displayed on the mobile screen, it would be more difficult or confusing for users.

Example: 
http://dc604.4shared.com/download/TSRQRxJHba/Mobile_view__2_.png?sbsr=ece3daa9145476db337a37496aaf990a95f&lgfp=3000

Ticket: https://market.open-classifieds.com/oc-panel/support/ticket/22732

**Comment by neo22s** [comment]
Doesnt seem that simple since that modal is how Android opens the selects by default....

If he wants something perfect for mobile he should check the natives apps...I will keep it on ideas, bu as said I do not see it at all.

**Comment by kotsios5** [comment]
I found this on easyjet app, maybe it's helpful.

![screenshot_2016-01-08-18-15-41](https://cloud.githubusercontent.com/assets/11571490/12322969/11fb09b2-bab8-11e5-9434-d4c502f900ce.png)

**Comment by neo22s** [comment]
thats not the native SELECT html input but looks great :dancers:

**Comment by oliverds** [comment]
Perhaps by changing "Chosen" select boxes to [Select2](https://select2.github.io/examples.html), it has mobile browser support.
