### ISSUE TITLE
Unconfirmed ad text translation

### ISSUE THREAD

**Issue by kotsios5** [open-classifieds/openclassifieds2#1690]
If an ad is not confirmed, I am getting a message "Page not found" etc.. If the website is not in English, the title of the page is still in English even if it's translated on the panel.

The text that is not displayed translated is:
"This advertisement doesn't exist, or is not yet published!"

Translation of this text is on page 70
http://reoc.lo/oc-panel/translations/edit/es_es?page=70

**Comment by neo22s** [comment]
weird I will review
