### ISSUE TITLE
Responsive / resize Images

### ISSUE THREAD

**Issue by neo22s** [open-classifieds/openclassifieds2#1694]
Free course from google
https://www.udacity.com/course/responsive-images--ud882?linkId=20115720

https://github.com/MattWilcox/Adaptive-Images
https://github.com/thephpleague/glide
http://code.svn.wordpress.org/photon/
https://github.com/Bodom78/kohana-imagefly

- [x] resize image depending on device @oliverds 
- [x] use correct image size, so the browser is not resizing @neo22s
- [x] implement in all themes, images for ads, categories, locations, users @kotsios5

**Comment by neo22s** [comment]
Hosted solutions SaaS seems lot more comfortable. not storing the data.

We can use
- https://developer.wordpress.com/docs/photon/ --> free for WP sites. we should warn customers
- http://images.weserv.nl/ --> free usage cloudflare CDN, nice!
- https://www.imgix.com/pricing --> paid expensive
- http://cloudinary.com/pricing --> 2gb free
- http://www.thumbr.io/plans_and_prices --> cheaper cool and from barcelona
- https://imageresizer.io/ --> no pricing cant find it
- https://www.resrc.it/ --> no pricing cant find it

**Comment by neo22s** [comment]
Speed:
https://i1.wp.com/demo2.open-classifieds.com/images/UGAWor3.jpg?resize=200,240 takes 34ms

https://images.weserv.nl/?url=demo2.open-classifieds.com/images/UGAWor3.jpg&w=200&h=240&t=square takes 130ms

I think this is the best option. I will create a function that receives the image URL the new size and options to output the image correctly.

If we use WP we need to use different domains using a md5 of the url? theres i(1,2,3).wp.com

**Comment by neo22s** [comment]
Ok, image resize should not be an issue plenty of solutions, about providing an smaller image in case the device is smaller, so making responsive images:

- https://make.wordpress.org/core/2015/11/10/responsive-images-in-wordpress-4-4/
- https://responsiveimages.org/
- https://www.smashingmagazine.com/2014/02/one-solution-to-responsive-images/
- https://css-tricks.com/which-responsive-images-solution-should-you-use/

**Comment by neo22s** [comment]
@oliverds Let's discuss this soon ;)

**Comment by oliverds** [comment]
Sure!

**picture** element described on https://responsiveimages.org/ seems easier to implement.

Using https://scotch.io/quick-tips/default-sizes-for-twitter-bootstraps-media-queries as base to find breaking points.

**Comment by neo22s** [comment]
@oliverds I can prepare som helper functions that given the path to an image returns all the possible sizes.

But theres few scenarios.
1- images that are thumbs, do we need different sizes?
2- images full size displayed in ads maybe here we do need that.

I think we need to do a skype chat since its 2 different topics, pics resized to the perfect match and responsive images.

**Comment by oliverds** [comment]
Sure we can discuss it over Skype.

**Comment by neo22s** [comment]
@oliverds maybe we can create a function like https://github.com/open-classifieds/openclassifieds2/blob/master/oc/kohana/system/classes/Kohana/HTML.php#L270

Called image_responsive ;) the class will need to be in common/html.php

**Comment by neo22s** [comment]
@oliverds @kotsios5 this is awesome: https://www.youtube.com/watch?v=8VzfRyDf8bo ---> https://www.youtube.com/watch?v=O091HfA9y_o

**Comment by neo22s** [comment]
common commit https://github.com/open-classifieds/common/commit/a92f51a657ec6a75905323f2004d4ea27f9acb2f

We have a new function 

`
Core::imagefly($image,$width=NULL,$height=NULL,$mode='crop');
`

Usage example
`
Core::imagefly($user->get_profile_image(),142,142)
`

This will generate an image of 142x142 and cache it in local, if they have CDN will use WP.

I have implemented it on theme default and ocean. see next commit

**Comment by oliverds** [comment]
These are the breaking points that have used for responsive images.

https://github.com/oliverds/yclas/blob/dfbd7b8aa0378ce27c63e31030a75577a42a926d/sites/classifieds/www/themes/default/views/pages/ad/single.php#L57

**min-width: 1200px**
Image container width on 1200px browser viewport.
Ex.
<img width="1456" alt="screen shot 2016-02-11 at 09 21 34" src="https://cloud.githubusercontent.com/assets/7003648/12980437/06b72c8e-d0a2-11e5-9c1e-4c58b19140a0.png">


**min-width: 992px**
Image container width on 992px browser viewport.

**min-width: 768px**
Image container width on 991px browser viewport.

**min-width: 480px**
Image container width on 979px browser viewport.

**min-width: 320px**
Image container width on 767px browser viewport.

**Comment by neo22s** [comment]
@oliverds 

What if as mentioned here https://github.com/open-classifieds/openclassifieds2/issues/1694#issuecomment-182277019 we have a function that generates the HTML?

So we pass an array of sizes or similar and then generates all this output?

Would be cleaner?

**Comment by oliverds** [comment]
@neo22s 

Oh I didn't saw your comment before. Yeah would be cleaner... I'm on it.

**Comment by neo22s** [comment]
@kotsios5 can start with this in all themes now ;)
