### ISSUE TITLE
Map on search page

### ISSUE THREAD

**Issue by kotsios5** [open-classifieds/openclassifieds2#1696]
When I am on map page, enter title, select category and location, click search and then click the map button (next to list, grid, sort), the map is displaying all the ads, not only the results of the search. 

The url is /map.html?category=&location=

**Comment by oliverds** [comment]
Maybe we should hide “Map” button on advanced search page since we don’t perform an 
*advanced search* on controller map https://github.com/open-classifieds/openclassifieds2/blob/master/oc/classes/controller/map.php#L28.

**Comment by neo22s** [comment]
thats right!

Or maybe theres some wayt that we display the map as an overlay with the result search? like 


![image](https://cloud.githubusercontent.com/assets/241725/12241711/f0c64114-b894-11e5-8e1a-a121faeca59f.png)


but better done, maybe hiding the lists?

**Comment by oliverds** [comment]
It seems possible. I will check it out ;)

**Comment by neo22s** [comment]
No hurry, if its easy to do it now move forward if not we schedule it. but seems quite cool, maybe a JS that reads the info from the current results in the HTML? we could have the lat and long as HTML data types? just brainstorming ;)

**Comment by kotsios5** [comment]
Map it's not displayed, instead of that the popup window is empty:
![search-map](https://cloud.githubusercontent.com/assets/11571490/13744381/4cced068-e9df-11e5-88e1-716c91fd097e.png)

**Comment by oliverds** [comment]
@kotsios5 It seems fine to me.

![all - openclassifieds2 2016-03-15 15-40-26](https://cloud.githubusercontent.com/assets/7003648/13794950/443faf22-eac4-11e5-9037-0699380267ed.png)

 Any js console error?

**Comment by kotsios5** [comment]
@oliverds On some themes (for example default theme) the pop up window does not appear when I click Map, nothing happens.
Yes, I can see an error on console:
ReferenceError: Maplace is not defined - sort.js:160:9

Same here:
https://forums.open-classifieds.com/support/map-on-search-page.html

**Comment by oliverds** [comment]
It seems there is, at least, one scenario where Maplace.js library is not being loaded. Will check it.

**Comment by oliverds** [comment]
Ok Maplace.js library was not loaded on advanced search. Fixed.
