### ISSUE TITLE
Improve performance SQL queries and PHP code

### ISSUE THREAD

**Issue by neo22s** [open-classifieds/openclassifieds2#1697]
This is a long task that can make the difference....

- review slow queries SQL ---> https://serverpilot.io/community/articles/how-to-read-the-mysql-slow-query-log.html
- PHP Slow requests --> https://serverpilot.io/community/articles/how-to-read-the-php-slow-request-log.html
- Optimize data types on Tables, include indexes where needed
- Optimize PHP code, check profiling tools, remove bottlenecks.

Profiling PHP:
- http://techportal.inviqa.com/2009/12/01/profiling-with-xhprof/
- https://blog.engineyard.com/2014/profiling-with-xhprof-xhgui-part-1
- http://www.xdebug.org/ with http://kcachegrind.sourceforge.net/html/Home.html or https://github.com/jokkedk/webgrind
- Paid: https://blackfire.io/
- Paid: http://newrelic.com/

**Comment by neo22s** [comment]
First part:

Remove the SHOW COLUMNS. this can be done by adding the protected $_table_columns =   in the ORM, can not be done in Ads nor Users since columns are dynamic.

To get the column:
```
$model = ORM::factory('review');
dr(var_export($model->table_columns()));
```

**Comment by neo22s** [comment]
I am using http://www.sitepoint.com/debugging-and-profiling-php-with-xdebug/ complex stuff

**Comment by neo22s** [comment]
After review of slow queries:

In table messages with 1400 messages takes 0'13 secs to get this:

```SELECT `oc2_m1`.`id_message` FROM `oc2_messages` AS `oc2_m1` LEFT JOIN `oc2_messages` AS `oc2_m2` ON (`oc2_m1`.`id_message` < `oc2_m2`.`id_message` AND `oc2_m1`.`id_message_parent` = `oc2_m2`.`id_message_parent`) WHERE `oc2_m2`.`id_message` IS NULL AND ((`oc2_m1`.`id_user_to` = '60' AND `oc2_m1`.`status_to` IN (0, 1)) OR (`oc2_m1`.`id_user_from` = '60' AND `oc2_m1`.`status_from` IN (0, 1)));```

**Comment by neo22s** [comment]
Working all day on Model_Category::get_category_count() and Model_Location::get_location_count() we should destroy this methods....  but I think @oliverds is working on this? https://github.com/open-classifieds/openclassifieds2/issues/1606

Another slow method is when we use ```DB::expr('RAND()')``` we need to see how could we replace this.... since its extremely slow if DB is big :(

**Comment by oliverds** [comment]
> Working all day on Model_Category::get_category_count() and Model_Location::get_location_count() we should destroy this methods.... but I think @oliverds is working on this? #1606

Yep but is not that easy, still not sure how to replace those methods with ajax calls on front-end yet.

Maybe we should limit get_category_count() up to the first child category/location.

#1606 is also a complex task.

**Comment by neo22s** [comment]
ok, let me review everywhere we use it, because if we only use it to load the menus thats going to be the solution.... xD

**Comment by neo22s** [comment]
nothing in php slow log :S

**Comment by neo22s** [comment]
for the RAND() issue theres not any faster solution since our results are non sequential....

More info http://jan.kneschke.de/projects/mysql/order-by-rand/

I will review the code add cache and be sure we are limiting and sorting correctly.
