### ISSUE TITLE
AdSense banner activation

### ISSUE THREAD

**Issue by 3-TEK** [open-classifieds/openclassifieds2#1701]
I'm running a premium theme "moderndeluxe3".
Been testing with ads after the 2.6.1 update to see if everything is working ok when i forgot about 1 "Test ad" i placed in "Spam" category.
Meanwhile i was setting up ad units on AdSense placing them between listings and was waiting for approval from Google (usually takes about 24 to 48 hours these days, don't know why). They rejected my units because they could not reach the "Test Ad" I had in "Spam" category marking it as "Page not found". I removed the ad and re-applied at google, now waiting for approval.

Any ideas?

**Comment by neo22s** [comment]
Please use our forum. This os for developers. Regards
