### ISSUE TITLE
Activating S3 - existing images

### ISSUE THREAD

**Issue by kotsios5** [open-classifieds/openclassifieds2#1713]
When Amazon S3 is activated, images of old ads that are saved on user server are not displayed.
Maybe it should be better to check somehow if images are on server and then use S3_domain to get them.

**Comment by neo22s** [comment]
Thats a limitation we have, we can not know whats uploaded and what not. So they need to enable that feature from beginning or they can upload all files manually.

**Comment by emanwebdev** [comment]
cannot check if previous / old images are on local server disk 
with a simple `if (file_exists($image_filename_we_try_to_retrieve))` ?

**Comment by neo22s** [comment]
see https://github.com/open-classifieds/openclassifieds2/issues/2096
