### ISSUE TITLE
Allow upload of .svg category-images

### ISSUE THREAD

**Issue by Pfilop** [open-classifieds/openclassifieds2#1714]
Category and user-Images get renamed to "ID.png" - no matter what filetype you actually uploaded...

Unfortunately no browser will display a SVG.png although most of them would allow ugly things like JPG.png

Could you please fix this behaviour?

**Comment by neo22s** [comment]
Could you please use our forums? https://forums.open-classifieds.com/ you can add a topic as suggestions and if more people wants this we will check it.

regards
