### ISSUE TITLE
Edit ad - images

### ISSUE THREAD

**Issue by kotsios5** [open-classifieds/openclassifieds2#1715]
When editing an ad, it doesn't allow to upload more than one image and it doesn't display the image before updating the ad:

![edit-ad](https://cloud.githubusercontent.com/assets/11571490/12484312/a30b2fa6-c051-11e5-931d-80ab83b6f768.png)

**Comment by neo22s** [comment]
That the image is not displayed its  a bug.

but the other we do it on purpose only q image at a time when updating ;)
