### ISSUE TITLE
Chat with seller custom fields

### ISSUE THREAD

**Issue by neo22s** [open-classifieds/openclassifieds2#1717]
We can create some special user CF that when filled will render a button to chat directly using a 3rd party app with the user.

- Whatsapp, like a checkbox, if selected will appear the button
- Telegram, link to open telegram app to chat directly with user
- Skype, link to open skype app to chat directly with user

Similar to: https://keyreply.com/chat/

**Comment by kotsios5** [comment]
Still working on this. Until now only skype works fine. 

Telegram: I have contacted their support for more information about the URL scheme.
Whatsapp: Still not sure if supports sending messages to users that are not in address book.
example: whatsapp://send?abid=Alex or whatsapp://send?abid=Alex , where abid: address book id

![ucf-panel](https://cloud.githubusercontent.com/assets/11571490/12961029/4397eb3c-d036-11e5-8638-78e4dbd1a834.png)

![ucf](https://cloud.githubusercontent.com/assets/11571490/12961068/7e13837a-d036-11e5-8a1b-8d40d0fdc456.png)

**Comment by neo22s** [comment]
oh, but I font think you need to create types.

Just if the CF is called skype then we render the link xD

For telegram 
`
tg://resolve?domain=USERNAME
`

for whatsapp if type is whatsapp just display the phone and the symbol next to it ;)

**Comment by kotsios5** [comment]
thanks!  it will be done tomorrow ;)

**Comment by neo22s** [comment]
This doesnt work. 

If the CF doesnt exists crashes ;)

Kohana_Exception [ 0 ]: The cf_skype property does not exist in the Model_User class 

DOCROOT/themes/default/views/pages/user/profile.php [ 39 ]

**Comment by neo22s** [comment]
This still does not work. If the fields to not exists crashes.

You can not do this: https://github.com/kotsios5/openclassifieds2/blob/479e8ffe5f73592eddf52a8161878e44a5447952/themes/default/views/pages/user/profile.php#L39 without and isset first.

Neither this 
https://github.com/kotsios5/openclassifieds2/blob/479e8ffe5f73592eddf52a8161878e44a5447952/themes/default/views/pages/user/profile.php#L52

**Comment by neo22s** [comment]
remove all your user CF and you will see.

Please do not commit without proper test.

**Comment by neo22s** [comment]
Still small issue, the fields are displayed 2 times:

![image](https://cloud.githubusercontent.com/assets/241725/13027244/05415a40-d247-11e5-9dee-ac6770914adf.png)

see https://testing.yclas.tk/user/admin

**Comment by kotsios5** [comment]
That's because you have checked show_profile. If you don't check it only the special user fields will appear.

**Comment by neo22s** [comment]
cool! working ;)

**Comment by horus911** [comment]
no attachment files why???

**Comment by horus911** [comment]
why we can not send files to seller or user in contact pop up form  box???
