### ISSUE TITLE
Ads with price = 0

### ISSUE THREAD

**Issue by kotsios5** [open-classifieds/openclassifieds2#1718]
Display 'Price: Free' when user type 0 in price field when publishing the ad. Currently when users type '0' the ad has no price.

**Comment by neo22s** [comment]
mmmm yeah can be done

**Comment by neo22s** [comment]
remember needs to be done in all the themes ;)

**Comment by kotsios5** [comment]
sure!

**Comment by kotsios5** [comment]
In both cases when:
a) the publisher leaves the price field empty (for categories like friendship) or
b) enter 0
the price in the database is 0.
In this way 'Price: Free' displayed even on ads that there's no reason to have price

**Comment by neo22s** [comment]
aha! thats why was not done before xD

Theres not a solution for everyone then.... this really depends on the customer how he wants to display it.

What do you think? maybe a configuration? if the setting is set then we will display the free text?

**Comment by kotsios5** [comment]
Yes, it would be the better option!

**Comment by neo22s** [comment]
ok, create a config, in advertisement settings, called free_tag or similar ;)

**Comment by neo22s** [comment]
@kotsios5 in the commit description you can close the issue directly by doing closes #1718 for example ;)

Related commit and closing https://github.com/open-classifieds/openclassifieds2/commit/007b7233aa8b48bc02ed25d3d9adf39bb0c08350

**Comment by kotsios5** [comment]
ok!
