### ISSUE TITLE
Post title includes "/"

### ISSUE THREAD

**Issue by kotsios5** [open-classifieds/openclassifieds2#1723]
When post title includes "/" then the SEO name of the ad includes "/" too and causes the error "Unable to find a route to match the URI"

Example: http://kijibuy.com/%E5%AF%B5%E7%89%A9%E5%8B%95%E7%89%A9%E9%86%AB%E9%99%A2%E7%BE%8E%E5%AE%B9%E6%97%85%E9%A4%A8/%E5%AF%B5%E7%89%A9%E6%9C%8D%E5%8B%99%20%E4%BB%A3%E6%BA%9C%E7%8B%97/%E5%B1%85%E5%AE%B6%E9%A4%B5%E9%A3%9F/%E6%B8%85%E7%90%86.html

https://forums.open-classifieds.com/support/bug-in-post-title-cause-an-error-unable-to-find-a-route-to-match-the-uri-in-chinese-version.html

**Comment by neo22s** [comment]
The issue is with CJK chars.... or seems https://github.com/open-classifieds/common/blob/master/classes/url.php#L30

I need to test in local.
