### ISSUE TITLE
Upload file to the ad

### ISSUE THREAD

**Issue by kotsios5** [open-classifieds/openclassifieds2#1724]
Option for publisher to upload a file (not only image), for example pdf or doc.

**Comment by neo22s** [comment]
quite complex, how do you assure theres no virus? to protect the file? complex....

**Comment by neo22s** [comment]
This was suggested by whom? to see the requirements. Maybe a CF that they can put a link? or probably with https://github.com/open-classifieds/openclassifieds2/issues/1741 its done ;)

Maybe we can put it in the docs, that they can use it to upload files and put the link there only for those who buy.

**Comment by kotsios5** [comment]
https://forums.open-classifieds.com/support/upload-file.html

He meant to allow publishers to upload a file like a pdf or doc, not just an image.

**Comment by neo22s** [comment]
They can put a link to dropbox file or similar, no?

**Comment by kotsios5** [comment]
Yes! They can create a custom field to share the link

**Comment by neo22s** [comment]
I mean using https://github.com/open-classifieds/openclassifieds2/issues/1741 and its send to the buyer to his email.

**Comment by kotsios5** [comment]
Yes, if they want to send it only to the buyer. In case they want to publish an ad and include the file in the ad (for example for more details), they can just share the link.
