### ISSUE TITLE
API image upload is not working

### ISSUE THREAD

**Issue by polatolu** [open-classifieds/openclassifieds2#1728]
image uploading for advertisements via API is not working, it returns the error below:

`Undefined index: image`

To add an image into an advertisement, I'm using `POST /api/v1/ads/image/ID_AD` and adding the image to the body section of this post as a file. 

Currently using 2.5.0 and this issue still exists on 2.6.1 regarding to my tests.

**Comment by neo22s** [comment]
Hello,

whats your website URL?

**Comment by polatolu** [comment]
I'm using locally, don't have a public installation yet.

**Comment by neo22s** [comment]
Why you dont you use our forum? https://forums.open-classifieds.com/support/on-oc-api-how-does-adding-image-to-an-ad-is-working.html you didnt answer there.

API doesnt work without a license, whats your purchase ID? so I can take a look.

Also please keep in mind this: https://github.com/open-classifieds/openclassifieds2/blob/master/CONTRIBUTING.md#reporting-issues

**Comment by rikeshrajbangshi** [comment]
Hello neo22s,

I need Help, I can't upload image through API. We have a license also. 

Purchase order ID : 3578

let adpublishphotosUrl = NSURL(string: API_URL + "ads/image/1")                          let request = NSMutableURLRequest(URL: adpublishphotosUrl!);             request.HTTPMethod = "POST"             let postString = "apikey=\(API_KEY)&user_token=\(UserToken)&image=\(img123.image)"             request.HTTPBody = postString.dataUsingEncoding(NSUTF8StringEncoding)

**Comment by neo22s** [comment]
@rikeshrajbangshi this is not a support page please contact us or open a support ticket.
