### ISSUE TITLE
Paypal Adaptive Payments

### ISSUE THREAD

**Issue by neo22s** [open-classifieds/openclassifieds2#1733]
SAme we do with stripe connect can be done with adaptive payments:

https://developer.paypal.com/docs/classic/products/adaptive-payments/
https://devtools-paypal.com/guide/ap_implicit_payment/php?interactive=ON&env=sandbox
https://github.com/paypal/adaptivepayments-sdk-php
Generate api access
https://www.paypal.com/es/cgi-bin/?cmd=_profile-api-access
https://developer.paypal.com/docs/classic/lifecycle/goingLive/
https://developer.paypal.com/developer/applications

Alternative library:
https://github.com/angelleye/paypal-php-library

**Comment by neo22s** [comment]
PAypal confirms what I knew, they have a horrible API, the SDK doesnt work documentation is old links that dont work either etc...worst ever...

Check:
http://stackoverflow.com/questions/19367125/how-to-transfer-money-from-paypal-account-to-another-paypal-account-via-api
http://stackoverflow.com/questions/4191887/how-to-send-money-to-paypal-using-php
http://ideone.com/12qU9A

**Comment by neo22s** [comment]
I have managed to use the sample from paypal https://devtools-paypal.com/guide/ap_implicit_payment/php?interactive=ON&env=sandbox

`use PayPal\Service\AdaptivePaymentsService;
use PayPal\Types\AP\FundingConstraint;
use PayPal\Types\AP\FundingTypeInfo;
use PayPal\Types\AP\FundingTypeList;
use PayPal\Types\AP\PayRequest;
use PayPal\Types\AP\Receiver;
use PayPal\Types\AP\ReceiverList;
use PayPal\Types\AP\SenderIdentifier;
use PayPal\Types\Common\PhoneNumberType;
use PayPal\Types\Common\RequestEnvelope;

require 'PPAutoloader.php';
PPAutoloader::register();`

**Comment by neo22s** [comment]
This is nuts I will work on something else the next days and leave this for future me, tired of it.

**Comment by neo22s** [comment]
The issue with this is that to get a paypal adaptive account is quite of difficult.

I have the code developed but I will not integrate this just yet. I am waiting to see if more clients are opening a marketplace and if they want to do it with paypal.

**Comment by emanwebdev** [comment]
New Notice from PayPal:
**Important**: Adaptive Payments is now a limited release product. It is restricted to select partners for approved use cases and should not be used for new integrations without guidance from PayPal.

from https://developer.paypal.com/docs/classic/products/adaptive-payments/

**Comment by neo22s** [comment]
@emanwebdev thanks... closing this madness!
