### ISSUE TITLE
Not possible to see or edit email templates

### ISSUE THREAD

**Issue by kotsios5** [open-classifieds/openclassifieds2#1739]
Email templates are not there, so i click 'create missing email from original'. Instead of create/display the email templates it displays the warning "We can not copy the email since the locale en_US already has existing email". I tried for other locales and it was the same.
Users will not be able to edit the templates.

![conte-emails](https://cloud.githubusercontent.com/assets/11571490/12853487/f2e3abc4-cc3c-11e5-84b1-053a2f073fc9.png)

**Comment by neo22s** [comment]
currently happening on OC 2.7?

**Comment by kotsios5** [comment]
yes! i also tried to clone and install again

**Comment by neo22s** [comment]
this was in a clean install? I can not reproduce it. can you please check?

thanks

**Comment by kotsios5** [comment]
I have checked now. 
I cloned from github and installed, it didn't work.
Then I installed 2.6.1 and it worked.

**Comment by neo22s** [comment]
mmmm

all of this with clean install? I mean new DB?

**Comment by kotsios5** [comment]
yeah, new db on every installation

**Comment by neo22s** [comment]
ok, I will do that then ;)
