### ISSUE TITLE
Captcha on register form

### ISSUE THREAD

**Issue by kotsios5** [open-classifieds/openclassifieds2#1754]
Option to enable/disable captcha on the register form.

**Comment by kotsios5** [comment]
reCaptcha does not appear on the form on http://reoc.lo/oc-panel/auth/register but it appears on the modal. Actually we have two forms on that page, the first one on the modal and the second one on the page, so reCaptcha appears only in the first form.

**Comment by neo22s** [comment]
yeah thats the problem, not sure if you will be able to solve it.... maybe adding a rule that if you are in http://reoc.lo/oc-panel/auth/register not render the other form (the one in the header)...I dont see other way.

**Comment by oliverds** [comment]
We had similar issue with contact form #1631.

Was fixed with commits https://github.com/open-classifieds/openclassifieds2/commit/bf70fa3efcb0a41b638f916d804e75900375966b and https://github.com/open-classifieds/common/commit/d3db62b955849caa709132bc83caa881f229563d#diff-4e4babb40d55dff6122fa0f3d9a6c494

**Comment by neo22s** [comment]
@oliverds awesome!! hahaha theres a fix for everything!

**Comment by kotsios5** [comment]
@oliverds Got it! Thanks!

**Comment by kotsios5** [comment]
I spend many hours trying to find a solution but still nothing.
@oliverds It looks like the same issue with contact widget, but actually it's not. Here we have the same code twice on the same page and I can't distinguish when it's on modal or in the page.

**Comment by oliverds** [comment]
I think we need to create more reCaptcha placeholders…

I would replace line https://github.com/open-classifieds/common/blob/d3db62b955849caa709132bc83caa881f229563d/classes/oc/captcha.php#L163-L171 with 

<pre>
            $html .= 'var recaptcha1; var recaptcha2; var recaptcha3; var recaptcha4;
                      var recaptchaCallBack = function() {
                          if (document.getElementById("recaptcha1") !== null) {
                              recaptcha1 = grecaptcha.render("recaptcha1", {"sitekey" : "'.Core::config('general.recaptcha_sitekey').'"});
                          }
                          if (document.getElementById("recaptcha2") !== null) {
                              recaptcha2 = grecaptcha.render("recaptcha2", {"sitekey" : "'.Core::config('general.recaptcha_sitekey').'", "size" : "compact"});
                          }
                          if (document.getElementById("recaptcha3") !== null) {
                              recaptcha3 = grecaptcha.render("recaptcha3", {"sitekey" : "'.Core::config('general.recaptcha_sitekey').'"});
                          }
                          if (document.getElementById("recaptcha4") !== null) {
                              recaptcha4 = grecaptcha.render("recaptcha4", {"sitekey" : "'.Core::config('general.recaptcha_sitekey').'"});
                          }
                      };'."\n";
</pre>

On line https://github.com/open-classifieds/openclassifieds2/blob/master/themes/default/views/header.php#L131 something like

`<?=View::factory('pages/auth/register-form', ['recaptcha_placeholder' => 'recaptcha4'])?>`

And on line https://github.com/open-classifieds/common/blob/master/views/pages/auth/register-form.php#L48 something like 

`
          <?=Captcha::recaptcha_display()?>
          <div id="<?=isset($recaptcha_placeholder) ? $recaptcha_placeholder : 'recaptcha3'?>"></div>
`

All that sould work.

**Comment by kotsios5** [comment]
Thanks @oliverds, I really appreciate your help!
