### ISSUE TITLE
geonames with HTTPS

### ISSUE THREAD

**Issue by neo22s** [open-classifieds/openclassifieds2#1755]
locations.js:122 Mixed Content: The page at 'https://testing.yclas.tk/oc-panel/location?id_location=1' was loaded over HTTPS, but requested an insecure script 'http://www.geonames.org/childrenJSON?geonameId=6295630&callback=listPlaces&style=long&lang=en&noCacheIE=1455362833277'. This request has been blocked; the content must be served over HTTPS.JSONscriptRequest.addScriptTag @ locations.js:122

Ups we got a problem here since there's no HTTPS :S

what do we do?

**Comment by oliverds** [comment]
Damn GeoNames HTTPS support is only available as a paid service and seems expensive http://www.geonames.org/commercial-webservices.html.

Maybe we could do the geonames request through PHP but I remember they have API rate limits.

**Comment by neo22s** [comment]
uffff

We need to find an alternative. Maybe using some sort of proxy that has HTPS?

**Comment by neo22s** [comment]
ok, all good!
