### ISSUE TITLE
Mark as sold

### ISSUE THREAD

**Issue by neo22s** [open-classifieds/openclassifieds2#1759]
User can mark his ads as Sold

**Comment by neo22s** [comment]
add a button next to the edit ad.

Maybe we need a new status...or we can just mark it as unavailable and thats all... the button should also set the stock = 0. since its sold....

**Comment by kotsios5** [comment]
I think this is the same as the 'deactivate' button.. Which does not set the stock equal to zero.

**Comment by neo22s** [comment]
we can modify controller that changes status to inactive and marks the stock to 0.

;)
