### ISSUE TITLE
Expired ads on panel

### ISSUE THREAD

**Issue by kotsios5** [open-classifieds/openclassifieds2#1766]
Currently, when an ad is expired is displayed under All Ads tab on panel Classifieds -> Advertisements. Maybe it would be better to change this and remove expired ads from there, so users can distinguish between published and expired ads.

**Comment by neo22s** [comment]
Maybe a filter by status? and by default only active ones? We can put a bar with buttons to filter ;)

**Comment by kotsios5** [comment]
Yep! We can also filter by featured, it would be useful!

**Comment by neo22s** [comment]
oh! watch out this is for 2.8.0 xD

I am working on the release of 2.7.0, please @oliverds @kotsios5 dont add anything else ;)

**Comment by neo22s** [comment]
ok feedback:

We can have just 2 buttons, like we have unavailable, spam etc... 1 that says Expired ads, and another Not expired as.

Links do the same ;) you can put an icon of a clock or similar.

Then also needs to be at Yclas.com

But yes its working good.

**Comment by neo22s** [comment]
O also put it before the sorting feature please.

**Comment by kotsios5** [comment]
Thanks for you feedback! 
What about featured ads? Another button like spam, unavailable etc?

**Comment by neo22s** [comment]
that would be cool!

**Comment by neo22s** [comment]
Have you committed this? so I can close 2.7.0 ;)

**Comment by kotsios5** [comment]
No! I was thinking to remove it for 2.7.0 and commit later for 2.8.0 when it will be completely done!

**Comment by neo22s** [comment]
Well just put the buttons instead of a dropdown.

Then the featured ads create a new issue for 2.8.0, ok? ;)

**Comment by kotsios5** [comment]
Ok!
