### ISSUE TITLE
Problems with imagefly

### ISSUE THREAD

**Issue by ascepanovic** [open-classifieds/openclassifieds2#1768]
Hi there,

I'm playing with default theme, but on different pages I am getting errors related to imagefly.
Mostly: Call to undefined method Core::imagefly() when searching or listing ads...

Do you have any suggestions maybe what is wrong here and how can I correct it.
In modules folder I do not have nothing except blacksmith folder so I'm not really sure where imagefly should be located ?

Btw. I'm using version 2.6.1

<img width="795" alt="screenshot 2016-02-19 11 51 38" src="https://cloud.githubusercontent.com/assets/2404433/13173677/493d098a-d6ff-11e5-9034-a880720b186d.png">

**Comment by neo22s** [comment]
Hello,

You are not using 2.6.1 you are using the code from the master branch. There's a tag for 2.6.1 ;)

Please anything else use our forum is the correct place.

regards

**Comment by neo22s** [comment]
https://github.com/open-classifieds/openclassifieds2/tree/2.6.1
