### ISSUE TITLE
Custom fields search a range of values

### ISSUE THREAD

**Issue by kotsios5** [open-classifieds/openclassifieds2#1769]
Option for numeric custom fields to search a range of values, like the Price field.

https://market.open-classifieds.com/oc-panel/support/ticket/23657

**Comment by neo22s** [comment]
we are creating a filter widget which does that. Correct @oliverds ? i remember talking about it

**Comment by oliverds** [comment]
Yeah remember talk about it too but I can't find which issue was related.

**Comment by neo22s** [comment]
me neither hahahaha was a customization for a client no?

**Comment by oliverds** [comment]
Maybe 30a_dev but it was a subscriptions customization to filter model, year, etc.
