### ISSUE TITLE
Membership plans to post - publish new

### ISSUE THREAD

**Issue by kotsios5** [open-classifieds/openclassifieds2#1772]
When I signed up for a plan and try to publish a new ad, the Publish New button does nothing. No error on Tools -> Logs. It only happens on premium themes.

**Comment by neo22s** [comment]
what you mean nothing happens? nothing loads?

**Comment by kotsios5** [comment]
Yes, nothing.

**Comment by neo22s** [comment]
the plans have all the info, theres not any error on your apache logs? jsut blank page?

**Comment by kotsios5** [comment]
No, nothing relevant.

**Comment by oliverds** [comment]
I'm unable to reproduce this issue.

Steps followed...

1. Enabled "suscription plugin"
2. Configured a new plan
3. Register new user and log in
4. Publish new ad but redirected to pricing page
5. Choose plan and pay
6. Publish new ad

**Comment by oliverds** [comment]
I think a have found the issue.

@kotsios5 do you have captcha enabled and reCaptcha disabled?

**Comment by kotsios5** [comment]
@oliverds Yes! As it was by default!

**Comment by oliverds** [comment]
Thanks @kotsios5. Fixed!
