### ISSUE TITLE
Membership plans to post - Info

### ISSUE THREAD

**Issue by kotsios5** [open-classifieds/openclassifieds2#1773]
"INFO: Please, choose a plan first" appears on checkout page (after I choose a plan)

![plans](https://cloud.githubusercontent.com/assets/11571490/13318243/a897cdfa-dbb1-11e5-9c20-d2aa089393f4.png)

**Comment by neo22s** [comment]
What flow this you follow?

1- go to publish
2- choose a plan? there should be the message not in any other page.

**Comment by kotsios5** [comment]
This is what I did. Go to publish, choose a plan by clicking the sign up button and then on the checkout page the INFO appears.

**Comment by neo22s** [comment]
ok, I will take a look, weird ;)

**Comment by oliverds** [comment]
Ok. Found this issue on Splash and Jobdrop theme. https://github.com/oliverds/yclas/commit/95f108b9df491767519b04d20ebb1cd3109991eb fixes it.

**Comment by neo22s** [comment]
so I can close this, correct?

**Comment by oliverds** [comment]
Yep, have done a pull-request.
