### ISSUE TITLE
Rich snippets for products

### ISSUE THREAD

**Issue by neo22s** [open-classifieds/openclassifieds2#1778]
Looks interesting we have it for OE 

https://developers.google.com/structured-data/rich-snippets/products

**Comment by oliverds** [comment]
Perhaps print **Structured Data** as an option in case website is not a marketplace.

**Comment by oliverds** [comment]
Damn! You were right @neo22s, there is an easier and cleaner way for this using [JSON-LD](http://json-ld.org/) :grin:. Reverted some changes.
