### ISSUE TITLE
Update jQuery

### ISSUE THREAD

**Issue by oliverds** [open-classifieds/openclassifieds2#1783]
http://blog.jquery.com/2016/02/22/jquery-1-12-1-and-2-2-1-released/

They reverted commit https://github.com/jquery/jquery/commit/49833f7795d665ff1d543c4f71f29fca95b567e9 causing issue https://github.com/openclassifieds/yclas/issues/139

**Comment by neo22s** [comment]
hohoho cool!

**Comment by oliverds** [comment]
Updating jQuery also fixes https://github.com/openclassifieds/yclas/issues/285 since they removed https://github.com/jquery/jquery/blob/1.11.3/dist/jquery.min.js#L6 line on distribution files.

**Comment by neo22s** [comment]
nice!
