### ISSUE TITLE
Category/Location widget issues (zh_CN)

### ISSUE THREAD

**Issue by kotsios5** [open-classifieds/openclassifieds2#1787]
Example on this site http://kijibuy.com as I cannot reproduce it on local.

test account:
email: myweb2pr@gmail.com
password: kijibuy

When I am logged out I can see that categories and locations widget are wrong. This is not happening when I am logged in.

Logged In - Homepage
![kiwilogin](https://cloud.githubusercontent.com/assets/11571490/13670017/3c47d4f6-e6bf-11e5-9905-3db13d07e184.png)

Logged Out - Homepage
![kiwi](https://cloud.githubusercontent.com/assets/11571490/13670019/3e47146a-e6bf-11e5-95e9-a163abf50ceb.png)
 
From forum:
https://forums.open-classifieds.com/support/full-category-list-disappear-in-sidebar-without-login.html
https://forums.open-classifieds.com/support/can-t-browse-specific-category-in-specific-location-when-logged-out.html

**Comment by neo22s** [comment]
on 2.6.1 or 2.7.0?

Saludos / Regards, Chema
GarridoDiaz.com <http://garridodiaz.com/>

**Comment by kotsios5** [comment]
On 2.6.1

**Comment by neo22s** [comment]
so in 2.7.0 happens?

Saludos / Regards, Chema
GarridoDiaz.com <http://garridodiaz.com>

**Comment by kotsios5** [comment]
No, I have just tested again.

I see, it will be solved once he update to 2.7.0.

**Comment by neo22s** [comment]
cooooool! can be closed then ;)

Saludos / Regards, Chema
GarridoDiaz.com <http://garridodiaz.com>
