### ISSUE TITLE
Translations editor LIVE!

### ISSUE THREAD

**Issue by neo22s** [open-classifieds/openclassifieds2#1807]
- [x] If you are translator or admin or moderator:
- [x] Display a edit button in all pages
- [x] Once pressed user can edit any text. 
- [x] we can override the __() function to return the JS or redirect the user to same page but with a parameter like ?edit_translation=1
- [ ] for pages just display a button to edit the content
- [x] once he does the translations he can press save.

**Comment by oliverds** [comment]
Ok. Having problems implementing this "LIVE" editor.

I'm trying to use [X-editable](https://vitalets.github.io/x-editable/) (Which looks pretty good) to make the texts editable but have to inject a few HTML attributes to identify the texts like `data-trans-id` and use a javascript selector.

I have no problem overriding the __() function to print those attributes but we also use `__('text')` inside an HTML attribute like `<a title="<?=__('text')?>"` (We even use it to translate URL texts) so we will be returning something like `<a title="<span data-trans-id="1">text</span>"` which breaks the HTML markup and also makes it impossible to later use a javascript selector for that text.

So now I'm stuck on this.

**Comment by neo22s** [comment]
What if we search for `title="<?=__('` and we replace it with another function like `title="<?=_e('`

Also will happen in placeholders :S I didnt think about this before. :(

**Comment by oliverds** [comment]
Other places where HTML causes problems

* https://github.com/open-classifieds/common/blob/master/classes/controller/jslocalization.php#L17
* https://github.com/open-classifieds/openclassifieds2/blob/master/themes/default/views/pages/ad/listing.php#L202 (somehow `sprintf()` missing arguments error)
* https://github.com/open-classifieds/openclassifieds2/blob/master/oc/config/routes.php#L19 (easy to solve)

So use `__()` to print HTML is not the way. But I can't figure out a solution.

**Comment by neo22s** [comment]
yeah we can create a function _e(

This function will just translate.

then __() will add JS or call directly _e(

You know what I mean? ;)

**Comment by oliverds** [comment]
Yes, I see what you mean but loooots of find and replace hehe.

**Comment by neo22s** [comment]
yep....pretty much it sucks :s

What other option do we have?

**Comment by oliverds** [comment]
> What other option do we have?

I don't see a better solution yet.

**Comment by neo22s** [comment]
should we postpone this for 2.9.0? since can delay the release a lot right?

**Comment by oliverds** [comment]
Could be. We have to test it too.

**Comment by neo22s** [comment]
ok, lets leave it for 2.9.0

**Comment by oliverds** [comment]
Only default theme so far.

![11](https://cloud.githubusercontent.com/assets/7003648/16676480/0c0d1272-4490-11e6-8adb-01adef17c505.gif)

Live translatable strings in _e() function.

**Comment by neo22s** [comment]
this looks awesome!! lets test :D

**Comment by neo22s** [comment]
The pop up when you want to translate a string from the top/heade its not visible.
