### ISSUE TITLE
Interactive Map

### ISSUE THREAD

**Issue by kotsios5** [open-classifieds/openclassifieds2#1825]
Interactive map configurations are not saved when Uses CDN for CSS/JS = Yes. I cannot reproduce it on local or yclas, it happens here: http://profi-immobilie.com/

Erros on panel:
POST http://profi-immobilie.com/oc-panel/map [HTTP/1.1 403 Forbidden 1064ms]
TypeError: _.Zf is undefined
TypeError: _.l is not a function
TypeError: _.li.j is undefined

**Comment by oliverds** [comment]
Couldn't reproduce it.

It seems some kind of server configuration forbidding http://profi-immobilie.com/oc-panel/map post action.

**Comment by neo22s** [comment]
mod_security probably from apache...

**Comment by oliverds** [comment]
So there is no way to fix it from our side right?

**Comment by neo22s** [comment]
nop I will close if we can not reproduce it in local @kotsios5 comment to the client we can not reproduce it and seems a security issue on his hosting side.
