### ISSUE TITLE
Implementing the search bar

### ISSUE THREAD

**Issue by ThomWensink** [open-classifieds/openclassifieds2#1834]
So for now we decided not to implement the search bar in the upper left bar on the main menu. I'd like to open this discussion. 

I think this is a rather important feature that we should not overlook. The search bar should give users the option to search for excisting pages or search (perhaps in the forums) for frequent problems.

Its just a simple matter of an investment of time. If we spend a few hours now on implementing this I think it will decrease the amount of support tickets that will be opened. Users will search for answers themselves before opening a ticket and in the long run I think it will save Constantinos work. 

_Just my cup of tea :)_

**Comment by neo22s** [comment]
We could implement just a normal search in the menu? like to search menu items?

Also not too difficult would be to implement a search on the docs...

**Comment by oliverds** [comment]
Search sidebar menu items should not be difficult. Perhaps the tricky part would be metisMenu.

Search all oc-panel pages, that's a difficult one.

So the sidebar search bar should search on the documentation or sidebar menu items... no?

**Comment by neo22s** [comment]
I think that can be good, display in the top the items in the menu and below results from the docs?

**Comment by oliverds** [comment]
Ok. Will be done like that ;)

**Comment by oliverds** [comment]
Having troubles implementing it with metisMenu. Will review it again later.
