### ISSUE TITLE
Arabic seo names

### ISSUE THREAD

**Issue by kotsios5** [open-classifieds/openclassifieds2#1837]
Arabic seo name for category or ad is changed to latin characters when submitted. On OC and Yclas, examples:

Category: http://constantinos.yclas.com/sy-r-t-o-mrkb-t-llbyaa-o-ll-yg-r-fy-lgz-r
Ad: http://constantinos.yclas.com/asdasd/sy-r-t-o-mrkb-t-llbyaa-o-ll-yg-r-fy-lgz-r.html

**Comment by neo22s** [comment]
its on purpose.... and its correct ;)

**Comment by kotsios5** [comment]
Great!
