### ISSUE TITLE
Toastr notifications

### ISSUE THREAD

**Issue by ThomWensink** [open-classifieds/openclassifieds2#1839]
Boys,

So this is something I wanted to implement from the beginning but didnt have the chance to introduce yet. 

Question: do we need a page refresh on form submit? I guess we do because its a form right? If we could get it to work somehow without form submit we could implement Toastr notifications. 

Demo: http://codeseven.github.io/toastr/demo.html
Open source code: https://github.com/CodeSeven/toastr

This is just an visual improvement. The current notifications are good aswell, just if we are improving things now might be the best time to implement it haha. 

Lemme know what the posibilities are regarding a page refresh on form submit.

**Comment by neo22s** [comment]
possible it is...xD

but lets wait a bit toooo mant changes, I put it on ideas, ok?

**Comment by oliverds** [comment]
PNotify looks good too: https://sciactive.com/pnotify/

But agree let's put it on the todo list.

**Comment by ThomWensink** [comment]
That one looks good too. Either of them would be cool to implement. But chema is right, perhaps its a bit much now. Lets do this when there is time left :)

**Comment by oliverds** [comment]
Ok. Growl style notifications on save settings where page refresh is not necessary required.

**Comment by neo22s** [comment]
looks good!!
