### ISSUE TITLE
Create uniformity in tables

### ISSUE THREAD

**Issue by ThomWensink** [open-classifieds/openclassifieds2#1843]
Ok, so this is one of the biggest improvements we can do I think. I mentioned this before on Trello but perhaps it wasnt clear. 

Fact is that we are using a lot of different styles in our tables. So far i've seen the following tables: 
_Table style 1_
![screenshot_1](https://cloud.githubusercontent.com/assets/11768128/14633915/f15c7e88-0649-11e6-96d7-21f54bd3f98c.png)

_Table style 2_
![screenshot_3](https://cloud.githubusercontent.com/assets/11768128/14633913/f11bdcc0-0649-11e6-9572-4ec4d5ddfcf2.png)

_Table style 3_
![screenshot_4](https://cloud.githubusercontent.com/assets/11768128/14633914/f1523d56-0649-11e6-8678-fbe54fef2782.png)

I know some of these tables are automaticly generated via JS but there has to be some way to control these too? 

Personally I like table style 1 the most. If we could use that style (buttons, colors, dropdowns) in all tables it would make way more sense.

**Comment by neo22s** [comment]
agree! we can do this!

**Comment by oliverds** [comment]
Good suggestion! I think now will have uniformity in all tables.
