### ISSUE TITLE
Checkbox custom fields

### ISSUE THREAD

**Issue by kotsios5** [open-classifieds/openclassifieds2#1850]
Once checkbox custom field is checked, it's not possible to uncheck it. 

https://forums.open-classifieds.com/support/custom-field-checkbox-for-adverts-wont-uncheck.html#comment-2633868959

Issue reproduced on local and http://constantinos.yclas.com.

**Comment by kotsios5** [comment]
I can't see how to fix this bug. 
1. I post the ad without checking the field, the value of the field in the db is "null". 
2. I edit the ad and check the field, the value is "1". 
3. Then I edit the ad again and uncheck the field, the value is still "1". 

It seems the only way to uncheck the field it is by change the value in the database to "null".

**Comment by oliverds** [comment]
That's strange. Something with js maybe. Let me take a look.

**Comment by oliverds** [comment]
Right! We needed a default value in case the checkbox is not checked.
