### ISSUE TITLE
Deleting / Uploading images at the same time

### ISSUE THREAD

**Issue by aescarcha** [open-classifieds/openclassifieds2#1852]
The way image upload / delete works does a save with the current model value -1 or +1, if you do several requests at the same time it creates inconsistencies, and some deleted images would display on show ad.

This could be fixed if instead of doing

`$this->has_images = ($this->has_images > 0) ? $this->has_images-1 : 0;
`

the increment / decrement was done in database, something like

`DB::update('tablname')->set(array('column_name' => DB::expr('column_name + 1'))->where('id', '=', 'primary_key')->execute();`

**Comment by neo22s** [comment]
want to do a PR with the improvement? ;)

**Comment by aescarcha** [comment]
Y sure, but I'll need a couple of days :)
