### ISSUE TITLE
AMP Errors

### ISSUE THREAD

**Issue by neo22s** [open-classifieds/openclassifieds2#1855]
I got an email from google saying that they could not add the AMP pages since theres tags missing

https://developers.google.com/structured-data/testing-tool/?url=https%3A%2F%2Faderous.com%2Fspammers%2F996-434-2177-sweet-and-spicy-call-girls-in-kormangala-4k-2hrs-6k-night.html%3Famp%3D1

![image](https://cloud.githubusercontent.com/assets/241725/14810252/40669980-0b92-11e6-9c17-3d3fbe0ddcb5.png)

https://aderous.com/spammers/996-434-2177-sweet-and-spicy-call-girls-in-kormangala-4k-2hrs-6k-night.html?amp=1
https://aderous.com/others/melwin-one-man-band-making-waves-ingoa-9822133510-1.html?amp=1
https://aderous.com/housing/bangal-ka-kala-jaduvashikaran-specialist-baba-91-9636481131.html?amp=1
https://aderous.com/services/alam-survey-jual-theodolite-topcon-es-102-103-105.html?amp=1
https://aderous.com/spammers/financial-problem-solution91-9887113626.html?amp=1
https://aderous.com/shared-apartments-rooms/asdasd.html?amp=1
https://aderous.com/others/sell-2c-e-sales8kaseeypharmcom.html?amp=1
https://aderous.com/other-market/jual-waterpass-automatic-leve-sokkia-b40-082112325856.html?amp=1

**Comment by oliverds** [comment]
Structured data was missing on AMP pages.
