### ISSUE TITLE
Image or video in forum description

### ISSUE THREAD

**Issue by kotsios5** [open-classifieds/openclassifieds2#1857]
When including image or youtube video in the description of the forum (Content -> Forums -> New), it displays the BBCode instead of the image or video:

![forum-media](https://cloud.githubusercontent.com/assets/11571490/14851766/fbf9e7f0-0c79-11e6-857a-adfe17ca895b.png)

Same on Yclas.

**Comment by neo22s** [comment]
any theme?

**Comment by neo22s** [comment]
i guess is missing the text to bbcode.

or bold for example is working?

**Comment by kotsios5** [comment]
It happens in all the themes. Neither bold or italics is working.

**Comment by neo22s** [comment]
:O thats strange!

https://github.com/open-classifieds/common/blob/3d0d9a9e48c321b3ba13c142fa4747f3371d4c7b/views/pages/forum/topic.php#L41

We use the Text::bb2html( weird

**Comment by neo22s** [comment]
I will take a look to this.

**Comment by kotsios5** [comment]
I found what's wrong, bb2html is missing in list.php

Assign the issue to me please, it needs to be done for some themes too.

**Comment by neo22s** [comment]
aaaaaaaaa description of the forum

sorry i didnt understand the issue before
