### ISSUE TITLE
Unlimited option for Membership Plan

### ISSUE THREAD

**Issue by nickjacobs** [open-classifieds/openclassifieds2#1862]
It would be great to have an 'Unlimited' option for membership plans, so that instead of having to put a large number like 999999, you can have unlimited amount of ads to post, and the view shows 'You have unlimited ads left'.  Either using Unlimited #checkbox - or 0=unlimited

**Comment by neo22s** [comment]
Hello Nick,

Please for suggestions the right place is to use the forum here:
https://forums.open-classifieds.com/publish-new.html?category=suggestions

Then other people can vote and if more people asks for it we will add it here on github.

This is only for developers.

thanks.
