### ISSUE TITLE
Membership plan - unlimited ads

### ISSUE THREAD

**Issue by neo22s** [open-classifieds/openclassifieds2#1863]
The membership plans are great, but I think there would be a useful mod - to allow unlimited ads.

At the moment to setup a plan like 'Annual plan - Unlimited Ads - x$' I have to set a large number for Amount of Ads (like 999999).

It would be great to be able to have either a checkbox 'Unlimited', or have 0 amount of ads=unlimited. Also, in the view, instead of showing 'You have 999998 ads left', it would show 'You have unlimited ads'. - See more at: https://forums.open-classifieds.com/suggestions/membership-plan-unlimited-ads.html#sthash.77Ht1JDZ.dpuf

**Comment by oliverds** [comment]
Ok. `$plan->amount_ads == -1` means unlimited ads

**Comment by neo22s** [comment]
In moderation and when you activate via confirm email we do a verification too, its new thats why you missed it ;)

https://github.com/open-classifieds/openclassifieds2/commit/dd26aecc8e091f34b891b191065e05b2c49a322d#diff-12ce1adac70d2c5628eecd146d49433dR351

https://github.com/open-classifieds/openclassifieds2/commit/dd26aecc8e091f34b891b191065e05b2c49a322d#diff-7f60901fa6394ce0018ad2a74b733f51R409


You simply need to put an OR that if its -1 goes through doesnt check anything else ;)

**Comment by oliverds** [comment]
My bad did't had updated my repo. Thanks!

**Comment by neo22s** [comment]
missing for yclas ,no?

**Comment by oliverds** [comment]
> missing for yclas ,no?

Yep. Was committing it ;)

**Comment by neo22s** [comment]
hahah sorry! xD
