### ISSUE TITLE
Latest ads widget displays expired ads

### ISSUE THREAD

**Issue by kotsios5** [open-classifieds/openclassifieds2#1867]
Latest ads widget displays expired ads. This happens if crontab was not set up and expired ads status is still published.

**Comment by neo22s** [comment]
Yeah...not much we can do I think....they need to enable the cron...

**Comment by kotsios5** [comment]
Cron is enabled now but it was not on the expiration date so the status didn't change.

**Comment by neo22s** [comment]
ok, review it, not fully sure I understand it.
