### ISSUE TITLE
Membership plan can be bought again before it expires 

### ISSUE THREAD

**Issue by kotsios5** [open-classifieds/openclassifieds2#1868]
Membership plan can be bought again before it expires. For example, a free plan of one ad for one day can be purchased by the same user many times in the same day.

**Comment by neo22s** [comment]
so its correct behaviour that someone can rebuy a plan. The issue is that if you are using a Free plan you should not be able to rebuy before expires ;)

**Comment by neo22s** [comment]
also found an issue while moderation the amount of ads left can go below 0...
