### ISSUE TITLE
image_path function fix

### ISSUE THREAD

**Issue by HurukHai** [open-classifieds/openclassifieds2#1874]
Hi,

Maybe you're intesrested in a posibly bug that, strangely can appear on `oc/classes/model/ad.php` and maybe in other places where `$this->image_path()` is used.

`$img_path = DOCROOT.$this->image_path();`
and later on: 
`File::delete($img_path);`

Actually I'm using rsync to synchro local and live files, and obviously, I forgot to change permissions to images directory. Apache didnt have write permisions... 
Because of that $this->image_path() returned false and File:delete tried to erase the DOCROOT folder.

Maybe this is not an issue at all becasue using the installer, permisions are correctly setted.

**Comment by neo22s** [comment]
Whats your domain name?

Have you followed the instructions to contribute? this is meant for developers thanks.

**Comment by HurukHai** [comment]
Ops sorry, close.

**Comment by neo22s** [comment]
No problem! you can use always our forum we will help you there, explain as in details as possible.
