### ISSUE TITLE
Auto-renew expired ads

### ISSUE THREAD

**Issue by kotsios5** [open-classifieds/openclassifieds2#1878]
Auto-renew expired ads until the user cancel it.

https://yclas.com/forum/support/auto-renew-ad.html

**Comment by neo22s** [comment]
@kotsios5 This is related to https://github.com/open-classifieds/openclassifieds2/issues/1920 since they are talking about memberships?

**Comment by kotsios5** [comment]
@neo22s Yes, seems the same!
