### ISSUE TITLE
logo and favicon issues when change http to https

### ISSUE THREAD

**Issue by congaframe** [open-classifieds/openclassifieds2#1879]
when site changes from http to https, the base_url config doesn't update site's logo and favicon
It turns out that those URLs are hard-coded inside DB: 
"logo_url":"http:\\/\\/domain.uk\\/images\\/vLink-Logo_hoz.png","favicon_url":"http:\\/\\/domain.uk\\/images\\/favicon.ico"

Theme code: 
```
./themes/default/views/header_metas.php:<link rel="shortcut icon" href="<?=(Theme::get('favicon_url')!='') ? Theme::get('favicon_url') : core::config('general.base_url').'images/favicon.ico'?>">
```
So if someone needs to change http to https, they will need to edit the theme, remove logo/favicon and reupload in order to insert new sql value.

**Comment by neo22s** [comment]
Good point we should update all the configs and search for `http:\/\/domain.com` and replace it for `https:\/\/doman.com`

**Comment by oliverds** [comment]
...Or we could save logo/favicon with protocol-relative URL.
