### ISSUE TITLE
installation script detects invalid protocol when using https

### ISSUE THREAD

**Issue by congaframe** [open-classifieds/openclassifieds2#1885]
Hi,
I found the following bug when install the code using https. The base_url has value of "http", instead of "https". 
I believe this is the code that get wrong protocol
https://github.com/open-classifieds/openclassifieds2/blob/a362dcda7109f36ad5b9edab7db309fd150ad332/install/class.install.php#L76-L79
```
        // Try to guess installation URL
        self::$url = 'http://'.$_SERVER['SERVER_NAME'];
        if ($_SERVER['SERVER_PORT'] != '80') 
            self::$url = self::$url.':'.$_SERVER['SERVER_PORT'];
```
I'm not a coder, please correct my below fix: 
```
        // checking $protocol in HTTP or HTTPS
        if (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] != 'off') {
            // this is HTTPS
            $protocol  = "https://";
        } else {
            // this is HTTP
            $protocol  = "http://";
        }
        // Try to guess installation URL
        self::$url = $protocol.$_SERVER['SERVER_NAME'];
        if ($_SERVER['SERVER_PORT'] != '80') 
            self::$url = self::$url.':'.$_SERVER['SERVER_PORT'];
```

**Comment by neo22s** [comment]
We will review, please for next time read our contributing guide https://github.com/open-classifieds/openclassifieds2/blob/master/CONTRIBUTING.md#reporting-issues

Always use our forums better ;)
