### ISSUE TITLE
Error with two subscribe widgets enabled

### ISSUE THREAD

**Issue by oliverds** [open-classifieds/openclassifieds2#1889]
> ErrorException [ Fatal Error ]: Cannot redeclare lili_subscribe() (previously declared in ~/Code/open-classifieds/openclassifieds2/themes/default/views/widget/widget_subscribers.php:18)

<img width="253" alt="screen shot 2016-05-27 at 9 35 09 am" src="https://cloud.githubusercontent.com/assets/7003648/15601099/2cf8dda8-23ee-11e6-89e0-803130b00681.png">

**Comment by neo22s** [comment]
ups I closed it but commit missing no?

**Comment by oliverds** [comment]
Pull-request missing yet.
