### ISSUE TITLE
[i18n] TRANSLATIONS: Missing 'msgid' in localized versions of files messages.po

### ISSUE THREAD

**Issue by emanwebdev** [open-classifieds/openclassifieds2#1906]
For example, 
https://github.com/open-classifieds/openclassifieds2/blob/master/languages/messages.po#L11045 

does NOT exist in 'fr_FR/messages.po'

hence how can we synchronize reference file messages.po with translated .po files?

**Comment by neo22s** [comment]
in the panel, translations. Needs to be done form there uses as reference the english version.

**Comment by emanwebdev** [comment]
well, but is there a tool somewhere in the panel to find missing i,e, not yet translated strings?

and how to search for a specific string ? for instance, there are dozens of machine translated string , from funny ones to misunderstanding ones. OMG! there are 89 pages to scout to find that string

**Comment by emanwebdev** [comment]
Is there a way to use PoEdit or similar tool without having the generated .po and .mo overwritten when using the panel please

**Comment by neo22s** [comment]
Hello,

Yes theres a button to filter missing translations and another one to make
a search ;)

Saludos / Regards, Chema
GarridoDiaz.com <http://garridodiaz.com>
