### ISSUE TITLE
Add Admin Keyboard Shortcuts

### ISSUE THREAD

**Issue by oliverds** [open-classifieds/openclassifieds2#1909]
**JS Libraries**

* https://craig.is/killing/mice
* https://github.com/madrobby/keymaster
* https://github.com/ccampbell/mousetrap

**Comment by oliverds** [comment]
**Shortcuts**

*Focus search input*
`Ctrl+Shift+s`

*Go to Home*
`g h`

*Go to Stats*
`g s`

*Go to Advertisements*
`g a`

*Go to Moderation*
`g m`

*Go to Orders*
`g o`

*Go to Plans*
`g p`

*Go to Subscriptions*
`g s`

*Go to Coupons*
`g c`

*Go to Users*
`g u`

*Go to User black list*
`g b l`

*Go to Delete All Cache*
`g c`

**How To Create Shortcuts**

Shortcut binding with 'data-keybinding' attribute. Ex. `<a data-keybinding='ctrl+shift+f'>Link</a>`

**Comment by neo22s** [comment]
Works great!!!! had only small issue with the first shortcut since was in use with another extension.

**Comment by neo22s** [comment]
@kotsios5 prepare a short docs for this ;) people will appreciate it ;)

**Comment by oliverds** [comment]
> Works great!!!! had the only small issue with the first shortcut since was in use with another extension.

Awesome screenshot extension no? Now I'm thinking about changing the shortcut to `f s` (focus search).

**Comment by neo22s** [comment]
Exactly!!! awesome screenshot! hahahah

mmmm not sure , just leave it ;)
