### ISSUE TITLE
Publisher to enable/disable comments

### ISSUE THREAD

**Issue by kotsios5** [open-classifieds/openclassifieds2#1912]
If comments are enabled by admin, allow the publisher to specify if they want to allow comments on their ad or not. 

https://yclas.com/forum/suggestions/upsell-options.html

**Comment by oliverds** [comment]
Thinking on use a custom field "cf_comments" to disable/enable the ad comments

**Comment by neo22s** [comment]
yes!

**Comment by oliverds** [comment]
Ok. This feature only available on premium themes because custom fields are for premium themes.

Method `$ad->comments()` checks also if custom field `commentsdisabled` is TRUE (https://github.com/oliverds/yclas/commit/8d3fe3e59fbda9890f8564e46dea93406d66b0c8).

**Comment by neo22s** [comment]
awesome!
