### ISSUE TITLE
Panel in mobile devices

### ISSUE THREAD

**Issue by neo22s** [open-classifieds/openclassifieds2#1917]
See https://yclas.com/forum/news/new-panel-new-theme-and-more.html

**Comment by oliverds** [comment]
This issue is still happening :(

**Comment by oliverds** [comment]
Hey, @ThomWensink. Could you please take a look at this? I have spent quite some time on this but still not able to fix it. Thanks!

**Comment by ThomWensink** [comment]
@oliverds I'll take a look! Will let you know what I find or if I solve it.

**Comment by neo22s** [comment]
Thanks thom

**Comment by neo22s** [comment]
Its already working?

**Comment by oliverds** [comment]
Thx Thom!

Well, it's a partial fix but works.

A kind of "dropup" or scrollable div would be better I think but couldn't do that.
