### ISSUE TITLE
Auto-renew membership plan

### ISSUE THREAD

**Issue by kotsios5** [open-classifieds/openclassifieds2#1920]
Give users the option to auto-renew their membership plan. The plan will be auto-renewed until they cancel it.

https://yclas.com/panel/support/ticket/8475

**Comment by neo22s** [comment]
we discussed this in the past, cant remember if theres an issue.

But this we could make it work right now only with stripe...and lot of trouble :S

**Comment by neo22s** [comment]
lets implement it only with stripe. We need to add a button to cancel subscription, create a cron to auto charge. I think thats actually all... ;)
