### ISSUE TITLE
Issues on maps

### ISSUE THREAD

**Issue by mydiyhobby** [open-classifieds/openclassifieds2#1933]
Hi Guys...Have some issue with my site...

Check please: linkinads.com

this error keep on popups...

This page was unable to display a Google Maps element. Please contact the site administrator.
 If you are the administrator of this site, please check the 
JavaScript console or check the following page for troubleshooting: http://g.co/mapsJSApiErrors

**Comment by neo22s** [comment]
Please this is not a forum.

Read the rules: https://github.com/open-classifieds/openclassifieds2/blob/master/CONTRIBUTING.md#reporting-issues

and use our forum thanks.
