### ISSUE TITLE
Yahoo login - Undefined index: key

### ISSUE THREAD

**Issue by kotsios5** [open-classifieds/openclassifieds2#1934]
Not able to login using Yahoo auth. I choose yahoo to login and get this error:
 Error: please try again! Undefined index: key

Reproduced on OC and Yclas.

**Comment by neo22s** [comment]
mmm weird.

Will review later.

**Comment by neo22s** [comment]
strange in local not happening :S @oliverds can you reproduce it?

**Comment by neo22s** [comment]
found it...strange :(

Not sure how to update now all the configs of existing sites. see commit https://github.com/open-classifieds/openclassifieds2/commit/8c615480a2e67a50d2a455a9a8a54d0533c93733

Instead of ID we need to use KEY. :S
