### ISSUE TITLE
Method View::__toString() must not throw an exception, caught Error: Call to undefined function is_admin()

### ISSUE THREAD

**Issue by kotsios5** [open-classifieds/openclassifieds2#1935]
Choose to edit an ad from Classifieds -> Advertisement or MyAds, getting this error:

![edit-ad](https://cloud.githubusercontent.com/assets/11571490/16390188/79c5c146-3c99-11e6-8c28-587d07fe7aad.png)

**Comment by neo22s** [comment]
2.8.0?

**Comment by kotsios5** [comment]
yes! I can reproduce it only on Splash, let me review the issue..

**Comment by oliverds** [comment]
I guess it's because of line https://github.com/openclassifieds/yclas/blob/master/sites/classifieds/www/themes/splash/views/oc-panel/profile/ads.php#L102 but I can't reproduce the error. Also on PRE looks fine.

@kotsios5 is your common repo updated?

**Comment by kotsios5** [comment]
@oliverds Yes, "Already up-to-date." It happens only on Splash, which is updated too. :S

**Comment by oliverds** [comment]
Double checked Splash theme and seems fine.

@neo22s Do you have the same error?

**Comment by neo22s** [comment]
Splash in reoc.lo no, in yclas.tk neither. http://testnew.yclas.tk/
