### ISSUE TITLE
Yahoo login - user email

### ISSUE THREAD

**Issue by kotsios5** [open-classifieds/openclassifieds2#1938]
Logging in using Yahoo auth redirects to a page that asks for user email address create user account. Instead, it should be use the email that uses to login to yahoo.

![yahoo-login](https://cloud.githubusercontent.com/assets/11571490/16410355/159802d4-3d1a-11e6-83dd-1178d04e41d7.png)

**Comment by neo22s** [comment]
Yahoo does not provide the email, or seems so...
