### ISSUE TITLE
Google Maps API error: MissingKeyMapError

### ISSUE THREAD

**Issue by kotsios5** [open-classifieds/openclassifieds2#1939]
Review the way google maps works.

Reproduced here: http://placestoshine.com/map.html

**Comment by neo22s** [comment]
We use http://maplacejs.com/ and seems theres an api key needed, I dont think we are using that :s

We can create a setting to put that info. We should do it fast before 2.8.0 release.

What you think @oliverds ?

**Comment by neo22s** [comment]
> About the API_KEY for Google Maps API
> All JavaScript API applications require authentication using an API key (or a client ID for Google Maps API for Work customers). Including a key when loading the API allows you to monitor your application's API usage in the Google Developers Console, enables per-key instead of per-IP-address quota limits, and ensures that Google can contact you about your application if necessary.
> 
> For more info please go to Google Maps JavaScript API developers website
https://developers.google.com/maps/documentation/javascript/get-api-key

**Comment by oliverds** [comment]
An api key was not required before by Google.

Yes, we need a new config for the api key.

@kotsios5 Are you already working on this?

**Comment by neo22s** [comment]
I think @kotsios5  is working on this. Yes just create a new config that gets inserted here
http://www.vultr.com/?ref=6814237

Then a setting where the other configs of the map with a link to create the api key.

And update the docs with this new ;)

**Comment by oliverds** [comment]
@kotsios5 has solved it and seems good.

I think this can be closed.
