### ISSUE TITLE
Updating to 2.8.0 panel issues

### ISSUE THREAD

**Issue by kotsios5** [open-classifieds/openclassifieds2#1951]
If users had selected an admin theme different than bootstrap before the update, a wrong css file is selected and there are major design issues in their new panel.

https://forums.open-classifieds.com/support/my-theme-s-panel-is-messed-up-after-update-to-2-8-0.html#comment-2758232322

**Comment by neo22s** [comment]
@oliverds we did a fix for yclas for this no? maybe for 2.8.1?

**Comment by oliverds** [comment]
Yes, It was a quick fix and I forgot to do the same for OC
