### ISSUE TITLE
Remove featured plan

### ISSUE THREAD

**Issue by kotsios5** [open-classifieds/openclassifieds2#1955]
When I click to delete a featured plan, the plan is still displayed there but if I refresh the page it's removed.

Same on yclas.

**Comment by neo22s** [comment]
Not sure I understand what url? you mean an ad that this featured? or one of the plans to feature an ad? xD

**Comment by kotsios5** [comment]
On this page: http://reoc.lo/oc-panel/settings/payment

Pressing this button:
![remove-featured-plan](https://cloud.githubusercontent.com/assets/11571490/16554797/edf6ab00-41c8-11e6-952b-ca45724e93fa.png)

**Comment by neo22s** [comment]
I see now! ok seems a JS issue.
