### ISSUE TITLE
Email confirmation On

### ISSUE THREAD

**Issue by kotsios5** [open-classifieds/openclassifieds2#1959]
Here's a scenario where publisher can activate his ad without using the link of the confirmation email.

1. Moderation = Email confirmation On
2. User registers with a fake email address.
3. Posts an ad and get the message _Advertisement is posted but first you need to activate. Please check your email!_ 
4. Go to oc-panel/myads and choose to deactivate the ad.
5. Click to activate the ad.
6. _Advertisement is active and published_ .

**Comment by neo22s** [comment]
aha!

ok we need to review this ;) should not be able to deactivate it since is not active thats all :P
