### ISSUE TITLE
ERROR: ErrorException [ 2 ]: file_get_contents

### ISSUE THREAD

**Issue by kotsios5** [open-classifieds/openclassifieds2#1965]
ERROR: ErrorException [ 2 ]: file_get_contents(https://rawgit.com/ivolo/disposable-email-domains/master/index.json): failed to open stream: HTTP request failed! HTTP/1.1 403 Forbidden

I was able to reproduce it on local then I replaced banned_domains.json with a new one (the same) and I couldn't reproduce the issue anymore. The issue seems to be on this line: 
https://github.com/open-classifieds/common/blob/master/classes/valid.php#L78

**Comment by neo22s** [comment]
Weird....the file is valid. But we can use CURL better. I will work on this tomorrow ;)
