### ISSUE TITLE
Blog post bb2html

### ISSUE THREAD

**Issue by kotsios5** [open-classifieds/openclassifieds2#1970]
If we use bb2html to display post description, medias are displayed but the text is displayed as HTML code:

![blog-post](https://cloud.githubusercontent.com/assets/11571490/16806511/a4c37b70-490c-11e6-9e28-4e81a0c430b0.png)

If we don't use bb2html, medias are displayed as bbcode code and the text is fine.

**Comment by oliverds** [comment]
Actually blog posts allow HTML so we don't have to use `bb2html()`.

Strange but on the panel we are displaying the wrong editor, sceditor instead of summernote.

**Comment by oliverds** [comment]
Commit https://github.com/oliverds/openclassifieds2/commit/7b4989dac6a84bf78763af88b89d436a64624f78 fixes the HTML editor on blog posts. Was an issue with the new panel.

@kotsios5 Could you please revert https://github.com/open-classifieds/openclassifieds2/commit/5898a66b2b102906b37bc23b6b13695b0e2480b7 related commits? Sorry, I should have noted the HTML editor issue before.

**Comment by kotsios5** [comment]
@oliverds Yes, sure!

**Comment by oliverds** [comment]
Thanks @kotsios5. I think we can close this, no?
