### ISSUE TITLE
Static map on ad page

### ISSUE THREAD

**Issue by kotsios5** [open-classifieds/openclassifieds2#1978]
Static map image is not displayed on single ad page.
GET http://maps.googleapis.com/maps/api/staticmap [HTTP/1.1 403 Forbidden 176ms]

Example: http://bengalurufocus.com/bangalore-north/pg.html  (on yclas)

**Comment by neo22s** [comment]
mmm this must be something new of the API.

**Comment by neo22s** [comment]
http://maps.googleapis.com/maps/api/staticmap?zoom=25&scale=false&size=600x300&maptype=roadmap&format=png&visual_refresh=true&markers=size:large%7Ccolor:red%7Clabel:%C2%B7%7C13.000596,77.571304

"The Google Maps API server rejected your request. This service requires an API key."

Ok, seems now we need to add the key too in the URL.

**Comment by oliverds** [comment]
Yes, API key is now mandatory.

**Comment by neo22s** [comment]
damn.... but its weird because is not happening to all the customers...must be something related to amount of hits?

Example https://americainmuebles.com/casas-en-alquiler-en-rio-cuarto/alquiler-casa-banda-norte.html
https://maps.googleapis.com/maps/api/staticmap?zoom=14&scale=false&size=600x300&maptype=roadmap&format=png&visual_refresh=true&markers=size:large%7Ccolor:red%7Clabel:%C2%B7%7C-33.110195,-64.337303

**Comment by oliverds** [comment]
Not sure why is a bit random. On bengalurufocus.com, sometimes shows me the map without problem.

Anyway, according with [Static Maps Docs](https://developers.google.com/maps/documentation/static-maps/intro) we need to add the KEY to the URL.

**Comment by kotsios5** [comment]
The issue is not fixed.
http://kotsios.yclas.com/new-categorynew-categorynew-category/test-ad.html
http://bengalurufocus.com/bangalore-north/pg.html 

Same error on console.

**Comment by neo22s** [comment]
The Google Maps API server rejected your request. This API project is not authorized to use this API. Please ensure that this API is activated in the APIs Console: https://console.developers.google.com/apis/library?project=_ Please ensure this API is activated in the Google Developers Console: https://console.developers.google.com/apis/api/static_maps_backend?project=_

**Comment by neo22s** [comment]
this is what says

**Comment by kotsios5** [comment]
I am not getting this error :S

I activated the API and it works!

**Comment by oliverds** [comment]
*bengalurufocus.com*, should be an API misconfiguration.

https://console.developers.google.com/apis/credentials

![screen shot 2016-07-20 at 9 41 27 am](https://cloud.githubusercontent.com/assets/7003648/16990706/9cfd88ac-4e5e-11e6-8092-9a4306b82a0f.png)

https://console.developers.google.com/apis/enabled

![screen shot 2016-07-20 at 9 42 43 am](https://cloud.githubusercontent.com/assets/7003648/16990712/a139f8d8-4e5e-11e6-91ca-0f4b7e5f08e6.png)

**Comment by kotsios5** [comment]
Yep, told him to enable Google Static Maps API. Thanks!

**Comment by neo22s** [comment]
cool! :D
