### ISSUE TITLE
Mark order as paid on panel

### ISSUE THREAD

**Issue by kotsios5** [open-classifieds/openclassifieds2#1979]
It happens only when the product is an ad, it works fine for Featured ads and Go to top.

1. Click Buy now on the single ad page.
2. Do not pay, go to the panel Classifieds -> Orders.
3. Click Mark as paid.
4. The order is paid, the ad is still published.

We need to deactivate the ad at the same time, which happens if the order is paid on Paypal.

Update: I think it happens only if the ad stock is NULL.

**Comment by neo22s** [comment]
damn! this was wrong for long time!!
