### ISSUE TITLE
Wrong api key

### ISSUE THREAD

**Issue by rviera** [open-classifieds/openclassifieds2#1985]
Hello, I'm getting the following: {"code":401,"error":"Wrong Api Key"} when trying to access http://livreiroonline.com.br/inicio/api/v1/listings?q=something&page=1&items_per_page=10 and other pages that need apikey. I'm using the APIkey from "settings>general>API Key"as suggested. Is there a way to generate another APIkey?

Thank you in advance.
Raphael

**Comment by kotsios5** [comment]
Hello Raphael, we will help you here: https://forums.open-classifieds.com/community/wrong-api.html

**Comment by neo22s** [comment]
Hello Raphael,

Please use our forums, this is for developer.

Thanks

**Comment by rviera** [comment]
Sorry, I followed the instruction from YClass Documentation: "Issues and bug reports . Please use GitHub to report any issue you may face."
Regards

**Comment by neo22s** [comment]
sorry thats only for devels, @kotsios5 will update that thanks for reporting!
