### ISSUE TITLE
Mercadopago

### ISSUE THREAD

**Issue by neo22s** [open-classifieds/openclassifieds2#1989]
https://www.mercadopago.com.ar/developers/es/

also connect? like with stripe take a look.

**Comment by oliverds** [comment]
Is sandbox mode missing?

https://www.mercadopago.com.mx/developers/es/related/basic-sandbox/

**Comment by neo22s** [comment]
I have used: https://www.mercadopago.com.ar/developers/es/solutions/payments/custom-checkout/test-cards/

+ testing users: https://www.mercadopago.com.ar/developers/es/solutions/payments/basic-checkout/test/test-users/
