### ISSUE TITLE
OC-panel: Select2 instead of Chosen

### ISSUE THREAD

**Issue by oliverds** [open-classifieds/openclassifieds2#2001]
On the front, we use Select2 for select form controls but on oc-panel we use Chosen. We should stick to only one ;)

**Comment by oliverds** [comment]
Oh! And we begin the 2000+ issues 😄

**Comment by neo22s** [comment]
hahahah ;)

**Comment by neo22s** [comment]
in yclas.tk is failing :S http://testnew.yclas.tk/oc-panel/theme/options

**Comment by oliverds** [comment]
Strange, it seems ok to me

![screen shot 2016-07-30 at 8 09 10 pm](https://cloud.githubusercontent.com/assets/7003648/17274017/859a2996-5691-11e6-9a1f-d290ea82acd8.png)

Any errors in the console?

**Comment by neo22s** [comment]
You are tight was something in my browser side :S some cache or whatever :S
