### ISSUE TITLE
Option to hide categories from homepage

### ISSUE THREAD

**Issue by kotsios5** [open-classifieds/openclassifieds2#2006]
An option for each category, to be displayed on homepage or not. Admins could be able to hide the categories they don't find necessary to show, without deleting them.

**Comment by neo22s** [comment]
sounds good idea!

@oliverds @kotsios5 a config and we save ids? or we add a new field in the table?

I tihnk a config is easier without modifying the table structure...

**Comment by kotsios5** [comment]
@neo22s Yes, it will easier. I think this way will be easier for admins too, since they won't need to browse the categories one by one to change that field.

**Comment by oliverds** [comment]
Cool! A config will be ;)
