### ISSUE TITLE
Website logo not displayed on email

### ISSUE THREAD

**Issue by kotsios5** [open-classifieds/openclassifieds2#2007]
I have checked other sites and yclas and it works fine. 
This website is using Zoho and the logo on email templates is not displayed. http://jualbelisemua.com/

![](http://jualbelisemua.com/screenshot/leerror.png)

**Comment by neo22s** [comment]
did he edit email.php? in views?

**Comment by neo22s** [comment]
and if hte email is sent with other provider the logo appears?

**Comment by kotsios5** [comment]
I don't think that he edited email.php, I will ask these questions!

**Comment by oliverds** [comment]
Just have this same issue with a customisation. Problem is that we are returning relative path image URL on emails. Fixing it.

**Comment by oliverds** [comment]
It's ok on yclas because we return CDN image URL.
