### ISSUE TITLE
Add image to an ad using API

### ISSUE THREAD

**Issue by kotsios5** [open-classifieds/openclassifieds2#2011]
Example:
http://reoc.lo/api/v1/ads/image/417?user_token=884ac030f2a9aeb8435ee03bc95e4f9b31bb2ccd&image=http://reoc.lo/images/2016/07/29/385/thumb_user-ad-on-moderndeluxe-1_1.jpg

{"code":404,"error":"Advertisement not found"}

Advertisement exists, but `$_FILES['image']` is not set, even if I include the image.

**Comment by neo22s** [comment]
This does not work like that at all ;)

Needs to send as multipart POST. Not specifying a URL.
