### ISSUE TITLE
Structured Data

### ISSUE THREAD

**Issue by kotsios5** [open-classifieds/openclassifieds2#2018]
Example: treguim.al
Rich Snippets is enabled, a locale with no currency is selected (locale created by user).

https://search.google.com/structured-data/testing-tool/u/0/#url=https%3A%2F%2Ftreguim.al%2Fmakina%2Fseat-ibiza.html

Since there's a warning about the priceCurrency, google sends a lot emails to the website owner.

**Comment by oliverds** [comment]
It seems we are unable to return a currency symbol with method [i18n::get_intl_currency_symbol()](https://github.com/open-classifieds/common/blob/6d0e90e45745f5e44f6eb723fb2f842e43251b84/classes/oc/i18n.php#L614).

I think would be helpful to know customer general.number_format config value.
