### ISSUE TITLE
Contact form Subject

### ISSUE THREAD

**Issue by kotsios5** [open-classifieds/openclassifieds2#2019]
The Subject of the contact.html page is not included into the email. We could add it in the first line of the email content.

**Comment by neo22s** [comment]
but is in the subject, no?

**Comment by kotsios5** [comment]
No, this is the subject: 
[EMAIL.SENDER] wants to contact you!

**Comment by neo22s** [comment]
ok, its easy to fix ;)

**Comment by kotsios5** [comment]
we could just edit the email template and use the subject:
https://github.com/open-classifieds/openclassifieds2/blob/master/oc/classes/controller/contact.php#L36

**Comment by neo22s** [comment]
exactly ;) that tag will work ;)

Saludos / Regards, Chema
GarridoDiaz.com <http://garridodiaz.com>
