### ISSUE TITLE
Email From easy to replace

### ISSUE THREAD

**Issue by neo22s** [open-classifieds/openclassifieds2#2024]
Lets add at oc-panel/content/email a form to replace the email from all the templates directly.

if not you need to go 1 by 1...

**Comment by oliverds** [comment]
You mean to replace this email no?

![screen shot 2016-08-10 at 10 08 18 am](https://cloud.githubusercontent.com/assets/7003648/17559083/78741980-5ee2-11e6-98ad-a66b4b7af29c.png)

Ok.

**Comment by neo22s** [comment]
yes....super annoying! hahahaha
