### ISSUE TITLE
Review Bitpay

### ISSUE THREAD

**Issue by kotsios5** [open-classifieds/openclassifieds2#2025]
Review if they changed their API.

https://market.open-classifieds.com/oc-panel/support/ticket/26595

**Comment by neo22s** [comment]
Seems they did modified the API
We used https://github.com/bitpay/php-client  that now redirects to https://github.com/bitpay/php-bitpay-client

Docs suck:
https://help.bitpay.com/8451-Implementation-/bitpay-php-library-usage-tutorial-from-start-creating-keys-to-finish-creating-an-invoice?from_search=13371696

**Comment by neo22s** [comment]
ok fixed it!! ufff such a mess!! was my fault!
