### ISSUE TITLE
XSS vulnerability

### ISSUE THREAD

**Issue by HurukHai** [open-classifieds/openclassifieds2#2032]
I'm running a previous version, 2.7.0 with some tricky improvements.

After the scan I found this: 

> The site is running TeeKai Tracking which is vulnerable to XSS
> Thos site is running Pinnacle ShowCenter Skin which is vulnerable to XSS

I've checked all the commits from 2.7.0 to 2.9.0 and no fix for XSS seen.
No comments about this found in opened issues neither.

**Comment by kotsios5** [comment]
Please use our forums, we will help you there: https://forums.open-classifieds.com
