### ISSUE TITLE
No option to post when Only admin to post is enabled

### ISSUE THREAD

**Issue by kotsios5** [open-classifieds/openclassifieds2#2036]
There's no option in the panel to post new ad, when Only admin to post is enabled.

**Comment by neo22s** [comment]
But the /publish-new.html works, no?

**Comment by kotsios5** [comment]
Yes, that works fine, only if you are logged in as admin. 
Where do you think the button should be placed?
1) as a button on the top menu?
2) another option in the dropdown menu?

![new-ad](https://cloud.githubusercontent.com/assets/11571490/18000775/9078baa8-6b77-11e6-8432-7a44264af978.png)

**Comment by neo22s** [comment]
Or maybe the button appears in the theme only if admin is logged in?
