### ISSUE TITLE
Custom fields on search widget

### ISSUE THREAD

**Issue by ptibor76** [open-classifieds/openclassifieds2#2038]
A checkbox type custom field which is appears on the search widget currently displays as a simple checkbox but it should be a 3 state field: yes, no, all - because it's a filter

If the custom field is a numeric field, a single numeric field is not enough for exact search. It should be a range with 'from' and 'to' values.

**Comment by neo22s** [comment]
Please for suggestions use our forums so other users can participate in the conversation:

https://forums.open-classifieds.com/publish-new.html?category=suggestions

thanks

**Comment by ptibor76** [comment]
Ok, thanks
