### ISSUE TITLE
Message system optional price field

### ISSUE THREAD

**Issue by neo22s** [open-classifieds/openclassifieds2#2041]
"
When a an advert is posted, and someone wishes to send a message through the website I have had created, there are 3 boxes to input contact name and a brief message, however the 3rd box says price. For the type of website I am, I don't need the price box. 
"

Create a setting to disable this field.

**Comment by oliverds** [comment]
So we should show price field on "send a message form" only if price field is enabled on "Advertisement Fields" https://reoc.lo/oc-panel/settings/form no?

**Comment by neo22s** [comment]
Oh! of course!! thats a good one.

But also, if you have the price field on, to be able to disable it in the form.

So:
1- If price is OFF never show it
2- if price is ON and new config is ON then display
3- if price is ON and new config is OFF do not display
