### ISSUE TITLE
Choose social media for the Share Widget

### ISSUE THREAD

**Issue by kotsios5** [open-classifieds/openclassifieds2#2047]
An option for admin to select which social media will be displayed in the Share Widget.

**Comment by neo22s** [comment]
easy to do? not really sure xD

**Comment by kotsios5** [comment]
I think it's easy. We need to create the option and display the selected social media.
https://github.com/open-classifieds/common/blob/dbbcef92a1bff8addb5719a9fbcc809c9c1a2845/views/share.php#L1-L10

**Comment by neo22s** [comment]
ok! all for you ;)

**Comment by kotsios5** [comment]
It should be closed with https://github.com/open-classifieds/openclassifieds2/pull/2050/commits/ee612092fe7060fd9c7e474628f5c664eb7ffb27
