### ISSUE TITLE
Elasticemail new pricing

### ISSUE THREAD

**Issue by kotsios5** [open-classifieds/openclassifieds2#2048]
https://elasticemail.com/pricing

**Comment by neo22s** [comment]
WOW now 150K free emails!??? :O

**Comment by kotsios5** [comment]
Yep! We need to change these texts, right?
![elasticemail-new-pricing](https://cloud.githubusercontent.com/assets/11571490/18243981/a0653668-7355-11e6-99f6-01cfd7357292.png)

**Comment by neo22s** [comment]
yes! ;)

**Comment by kotsios5** [comment]
Should be closed with https://github.com/open-classifieds/openclassifieds2/pull/2050/commits/cb3c98dd7f7f2417ce88c7cd3a0598187ac22b95
