### ISSUE TITLE
Share on facebook

### ISSUE THREAD

**Issue by kotsios5** [open-classifieds/openclassifieds2#2049]
We need to investigate if it's an issue from our side.

https://developers.facebook.com/tools/debug/sharing/?q=popoyolist.com

**Comment by neo22s** [comment]
as soon as he uses a logo that wont happen:
https://github.com/open-classifieds/openclassifieds2/blob/e3bcea757e0d91ecff6dfb2b68caecc69f8ece76/themes/default/views/header_metas.php#L28
