### ISSUE TITLE
nothing below /oc/common/ clones or downloads

### ISSUE THREAD

**Issue by uberdave** [open-classifieds/openclassifieds2#2068]
there are no files in the common directory after I cloned the project into my web directory.
So, I tried downloading the project and there are no files in the common directory.

I noticed on the github directory that the common filename was  'common @ e9144d1', instead of 'common', but in both of my directories, cloned and downloaded, the filename is simply 'common'
===============================================================================
Warning: include(/var/www/html/class/oc/common/vendor/php-gettext/gettext.inc): failed to open stream: No such file or directory in /var/www/html/class/install/class.install.php on line 286

Warning: include(): Failed opening '/var/www/html/class/oc/common/vendor/php-gettext/gettext.inc' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/html/class/install/class.install.php on line 286

Fatal error: Call to undefined function T_setlocale() in /var/www/html/class/install/class.install.php on line 288

**Comment by neo22s** [comment]
Hello Dave,

You need to download the latest stable release from here:
http://open-classifieds.com/download/

If you are a developer follow this steps to clone the github project:
https://github.com/open-classifieds/openclassifieds2/blob/master/CONTRIBUTING.md#cloning-repo

Anything else please use our forums:
https://forums.open-classifieds.com/

Thanks!

**Comment by uberdave** [comment]
I got through everything. The site came up... then

The requested URL /openclassifieds2/oc-panel/auth/login was not found on this server
when I tried to login.

**Comment by neo22s** [comment]
Please use our forum Dave, post a new topic there. Thanks
