### ISSUE TITLE
Private site - request access not working

### ISSUE THREAD

**Issue by kotsios5** [open-classifieds/openclassifieds2#2072]
Email is not sent to admin, no error message.

**Comment by neo22s** [comment]
this is closed, no? did you add the exception to the controller? https://github.com/open-classifieds/openclassifieds2/pull/2078

**Comment by kotsios5** [comment]
not fixed yet, they shouldn't see the menu etc
![request-access](https://cloud.githubusercontent.com/assets/11571490/19150420/ab97bbba-8bbe-11e6-9c5a-df9a316bd92d.png)
