### ISSUE TITLE
The requested URL /openclassifieds2/oc-panel/auth/login was not found on this server.

### ISSUE THREAD

**Issue by uberdave** [open-classifieds/openclassifieds2#2076]
I installed the oc directory as per instructions in my last closed issue.
I get the front page up afterwards.

then when I try to log in, i get this
The requested URL /openclassifieds2/oc-panel/auth/login was not found on this server.
there is no oc-panel directory in my distribution.

I went to the forum, but it will not post my question. 

 I have no idea what version I have, but i downloaded from the suggestion made to me in the ticket, you guys closed.

**Comment by neo22s** [comment]
You have the latest version as indicated in the file downloaded by you the version is 2.9.0.

Please use our forums, github is for development purposes. thanks.

**Comment by m-henderson** [comment]
same here

**Comment by neo22s** [comment]
its a htaccess issue, please be sure your hosting is compatible.

**Comment by m-henderson** [comment]
will do. mod_rewrite is enabled. idk what it could be. do you have a way I can fix it ? 

I am running ubuntu 16.04 on my server that has a LAMP stack.

**Comment by m-henderson** [comment]
found a fix 

By default the LAMP install will disable usage of the .htaccess file.

You need to edit the configuration file for your virtual host.

` $ nano /etc/apache2/sites-available/000-default.conf`
**Change the <VirtualHost> directive to look something like this. The important part is AllowOverride All, as this tells Apache that the directory can override default settings using a .htaccess file.**

```
<VirtualHost *>
    

     <Directory /var/www/html>
        Options FollowSymLinks
        AllowOverride all
        Require all granted
     </Directory>

     ErrorLog ${APACHE_LOG_DIR}/error.log
     CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>
```
Now make sure the website is enabled.

 ` $ a2ensite 000-default.conf`
Also make sure that the rewrite mod is enabled.

  `$ a2enmod rewrite`
Now restart Apache

`   $ service apache2 restart`

**Comment by neo22s** [comment]
thanks for sharing.

**Comment by m-henderson** [comment]
no problem, friend!
