### ISSUE TITLE
Innodb

### ISSUE THREAD

**Issue by neo22s** [open-classifieds/openclassifieds2#2115]
Migrate all tables to innodb.

So in the update 300 alter table to innodb and in install use innodb too. 

We need to see if this process may time out the sites easily...if thats the case only for new installs.

Review TEXT fields - seems we should move better to varchar. Study this option.

**Comment by neo22s** [comment]
http://stackoverflow.com/a/9492183/514629

ALTER TABLE `oc2_visits` ENGINE=InnoDB;
ALTER TABLE `oc2_users` ENGINE=InnoDB;
ALTER TABLE `oc2_subscriptions` ENGINE=InnoDB;
ALTER TABLE `oc2_subscribers` ENGINE=InnoDB;
ALTER TABLE `oc2_roles` ENGINE=InnoDB;
ALTER TABLE `oc2_reviews` ENGINE=InnoDB;
ALTER TABLE `oc2_posts` ENGINE=InnoDB;
ALTER TABLE `oc2_plans` ENGINE=InnoDB;
ALTER TABLE `oc2_orders` ENGINE=InnoDB;
ALTER TABLE `oc2_messages` ENGINE=InnoDB;
ALTER TABLE `oc2_locations` ENGINE=InnoDB;
ALTER TABLE `oc2_forums` ENGINE=InnoDB;
ALTER TABLE `oc2_favorites` ENGINE=InnoDB;
ALTER TABLE `oc2_crontab` ENGINE=InnoDB;
ALTER TABLE `oc2_coupons` ENGINE=InnoDB;
ALTER TABLE `oc2_content` ENGINE=InnoDB;
ALTER TABLE `oc2_config` ENGINE=InnoDB;
ALTER TABLE `oc2_categories` ENGINE=InnoDB;
ALTER TABLE `oc2_adsimport` ENGINE=InnoDB;
ALTER TABLE `oc2_ads` ENGINE=InnoDB;
ALTER TABLE `oc2_access` ENGINE=InnoDB;

**Comment by neo22s** [comment]
TEXT can be replaced by VARCHAR (65535 - the other varchars in the table)

From the docs:
http://dev.mysql.com/doc/refman/5.7/en/string-type-overview.html
VARCHAR is subject to the maximum row size (65,535 bytes, which is shared among all columns)

LONGTEXT is a problem :( could be changed to a MEDIUMTEXT that for sure. But can not get rid off TEXT issue....


     Type | Maximum length
-----------+-------------------------------------
  TINYTEXT |           255 (2 8−1) bytes
      TEXT |        65,535 (216−1) bytes = 64 KiB
MEDIUMTEXT |    16,777,215 (224−1) bytes = 16 MiB
  LONGTEXT | 4,294,967,295 (232−1) bytes =  4 GiB

**Comment by oliverds** [comment]
Sorry, but what's the reason to change TEXT data type to VARCHAR on InnoDB engine?

**Comment by neo22s** [comment]
- takes less space since is a variable space (we save a ton like this)
- replication on DB using a Master->Master or Master->Slave seems to be more reliable (no clue why)

**Comment by neo22s** [comment]
To get where we use longtext

```
select * from information_schema.columns
where table_schema = 'openclassifieds' AND data_type = 'longtext'
order by table_name,ordinal_position
```

**Comment by neo22s** [comment]
@kotsios5 

Can we create a new page in the docs, that says MyIsam to Innodb.

And then Explain; if you want to move from MyIsam to innodb please execute this SQLs

MyISAM will be deprecated in future versions of MySQL and you may need to do this if you are running a version of Yclas self-hosted below 3.0

> ALTER TABLE oc2_visits ENGINE=InnoDB;
> ALTER TABLE oc2_users ENGINE=InnoDB;
> ALTER TABLE oc2_subscriptions ENGINE=InnoDB;
> ALTER TABLE oc2_subscribers ENGINE=InnoDB;
> ALTER TABLE oc2_roles ENGINE=InnoDB;
> ALTER TABLE oc2_reviews ENGINE=InnoDB;
> ALTER TABLE oc2_posts ENGINE=InnoDB;
> ALTER TABLE oc2_plans ENGINE=InnoDB;
> ALTER TABLE oc2_orders ENGINE=InnoDB;
> ALTER TABLE oc2_messages ENGINE=InnoDB;
> ALTER TABLE oc2_locations ENGINE=InnoDB;
> ALTER TABLE oc2_forums ENGINE=InnoDB;
> ALTER TABLE oc2_favorites ENGINE=InnoDB;
> ALTER TABLE oc2_crontab ENGINE=InnoDB;
> ALTER TABLE oc2_coupons ENGINE=InnoDB;
> ALTER TABLE oc2_content ENGINE=InnoDB;
> ALTER TABLE oc2_config ENGINE=InnoDB;
> ALTER TABLE oc2_categories ENGINE=InnoDB;
> ALTER TABLE oc2_adsimport ENGINE=InnoDB;
> ALTER TABLE oc2_ads ENGINE=InnoDB;
> ALTER TABLE oc2_access ENGINE=InnoDB;
> ALTER TABLE `oc2_config` CHANGE `config_value` `config_value` MEDIUMTEXT;
> ALTER TABLE `oc2_content` CHANGE `description` `description` MEDIUMTEXT;
> ALTER TABLE `oc2_plans` CHANGE `description` `description` MEDIUMTEXT;
> ALTER TABLE `oc2_posts` CHANGE `description` `description` MEDIUMTEXT;
