### ISSUE TITLE
New free theme

### ISSUE THREAD

**Issue by neo22s** [open-classifieds/openclassifieds2#419]
We will launch 2.1 with a new free theme.

Called minimal, just one column, no sidebar, really simple using bs3.

**Comment by neo22s** [comment]
We will release basecamp free ;)

**Comment by emanwebdev** [comment]
@neo22s 
> can you please contact me? so we can find the best way of distribution? thanks!

HI Chema,
How ? / Where ? can i submit free oc2 themes based on https://html5up.net/ CC creative commons licencing scheme

**Comment by neo22s** [comment]
hello!

No prob we already have it, thanks a lot! :D

**Comment by emanwebdev** [comment]
Hola @neo22s  

sorry not sure we get the point. 

Do you mean i can distribute french version of OC2 using any CC creative commons theme?

**Comment by neo22s** [comment]
Yes you can! but I think we can discuss this privately if you want so we can have an understanding ;)

Can you email me your ideas and we discuss it internally? thanks :D
