### ISSUE TITLE
widget idea - "recently searched"

### ISSUE THREAD

**Issue by neo22s** [open-classifieds/openclassifieds2#581]
Hello,

this would be such a simple idea, but useful for returning visitors. Just create a widget that shows the customer the categories which he recently visited or where they landed on through their search queries.

Chris

**Comment by neo22s** [comment]
Store:

- Time, when was done
- Keyword, what was search or querystring of sent values
- URL where was

**Comment by neo22s** [comment]
I am getting some issues while testing this.

For example I search
http://reoc.lo/search.html?title=more&category=prueba&price-min=&price-max=&cfuser_buscable=&submit=

And stores
more - more --> http://reoc.lo/search.html?title=more&category=more

**Comment by oliverds** [comment]
Damn. It seems ok to me.

Need to review it then.

**Comment by oliverds** [comment]
What's your enabled theme?

**Comment by neo22s** [comment]
yummo

Saludos / Regards, Chema
GarridoDiaz.com <http://garridodiaz.com>
