### ISSUE TITLE
Automate regressions

### ISSUE THREAD

**Issue by neo22s** [open-classifieds/openclassifieds2#584]
https://chrome.google.com/webstore/detail/imacros-for-chrome/cplklnmnlbnpmjogncfgfijoopmnlemp

http://docs.seleniumhq.org/download/

http://codeception.com/docs/modules/Kohana

See: https://github.com/open-classifieds/openclassifieds2/issues/30

**Comment by neo22s** [comment]
whats the current status of this? how many more integrations are left?

**Comment by kotsios5** [comment]
There are a lot left (based on regressions-tests.xls before each release).. I am trying to cover as more use cases as I can.

**Comment by neo22s** [comment]
Can we prepare a document? Lets talk on the chat, thanks!
