### ISSUE TITLE
Keep images in publish new if not succeed

### ISSUE THREAD

**Issue by neo22s** [open-classifieds/openclassifieds2#839]
Ajax request validates captcha before posting.

**Comment by oliverds** [comment]
> Ajax request validates captcha before posting.

Since it's already [done](https://bitbucket.org/neo22s/open-classifieds-private/commits/588799f545f39e34f41a43e3d2ba2356e197d79d) on premium themes too this issue can be closed.

**Comment by neo22s** [comment]
Coool!! :dancer:
