### ISSUE TITLE
Form Orm using datatables

### ISSUE THREAD

**Issue by neo22s** [open-classifieds/openclassifieds2#88]
Will allow is to filter/search export to excel and paginate using ajax.

UPDATE: we will use http://www.jquery-bootgrid.com/

**Comment by neo22s** [comment]
New CRUD this means. Check for jquery plugins theres some really awesome stuff out there.

**Comment by neo22s** [comment]
Requirements:
- Open Source
- Well documented
- Updated
- Possible integrate with BS3
- Easy to integrate

ok, found like many many plugins, this ones are updated and look fine:

## https://datatables.net/
https://datatables.net/examples/styling/bootstrap.html bootstrap skin
Updated 2 months ago

## http://www.dynatable.com/ 
seems will get style from CSS, like the documentation seems simple
last update almost 2 years ago

## http://www.jtable.org/
last update 1.5years ago
good examples, not BS
Uses BS. 

## http://www.jquery-bootgrid.com/
Updated 2 months ago
Seems pretty simple to use http://www.jquery-bootgrid.com/Examples#data-api clear docs

## http://bootstrap-table.wenzhixin.net.cn/
really updated, already uses BS many stars on GH. seems more complex

**Comment by neo22s** [comment]
@oliverds what do you think?

**Comment by oliverds** [comment]
I would choose [jQuery Bootgrid](http://www.jquery-bootgrid.com). It seems easier to implement and designed for bootstrap already.

[Bootstrap Table](http://bootstrap-table.wenzhixin.net.cn/documentation/) would be a good choice too. It seems to have many more table options and designed for bootstrap too.

**Comment by neo22s** [comment]
Agree! ok I will start anytime this year xD http://www.jquery-bootgrid.com/

**Comment by neo22s** [comment]
ok, we need to find a way to filter by columns...maybe in the same table add selects? that would be the best.

investigate this ;)
